# Exploratory Modeling
- Look at total combined data, cut it down, and try some non-NN models

### Package loading

In [1]:
# load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import os

%matplotlib inline

## Data import

- Note: using .tsv on local machine, will upload to Google or Amazon S3 bucket for cloud usage.

In [2]:
PATH='~/Documents/UCBerkeleyMIDS/W210/Capstone_Project/Data'
#os.chdir(path)

In [3]:
!ls ~/Documents/UCBerkeleyMIDS/W210/Capstone_Project/Data

BR_categories_grouped.csv           Complaint_types_Master_sheet_v2.tsv
CHI_categories_grouped.csv          Complaint_types_Master_sheet_v3.tsv
CIN_categories_grouped.csv          combined_trainingdata_20181013.tsv
Complaint_types - Master_sheet.tsv

In [5]:
# import the data

storetype=1

if storetype==1:
    df=pd.read_csv(PATH+'/combined_trainingdata_20181013.tsv',sep='\t')
#elif storetype==2:
    #df=pd from S3

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (4,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df[df['CITY']=='IRELAND']

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
281116,281116,ireland_100,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholes in Allenwood South,"Hi, I live in Allenwood South (L70044), my hou..."
281117,281117,ireland_10000,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light not working
281118,281118,ireland_10001,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Ditch removal,Ditch trees and brambles recently removed by t...
281119,281119,ireland_10002,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light not working
281120,281120,ireland_10003,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light not working at this location
281121,281121,ireland_10004,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholr and a trip hazard on road between sund...,Please repair
281122,281122,ireland_10005,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Rubish left,Large bag of rubbish with cans and bottles lef...
281123,281123,ireland_10006,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Illegal Dumping,Two refuse sacks dumped here on the morning of...
281124,281124,ireland_10007,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Large Pothole,Large pothole has developed on the road to Pie...
281125,281125,ireland_10008,IRELAND,01/01/2018,general,graffiti,vandalism,vandalism_graffiti,Graffiti and generally looking bad,The wall surround the green space is covered i...
281126,281126,ireland_10009,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Damaged Street Tree,A branch on a street tree outside 74 Whiteclif...
281127,281127,ireland_1001,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Road surface,Road surface slippery at junction when turning...
281128,281128,ireland_10010,IRELAND,01/01/2018,general,street lighting,street,street_lighting,New street lights,New street lights only give out a small amount...
281129,281129,ireland_10011,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Dumping,This area is a disgrace with dumping of nappie...
281130,281130,ireland_10012,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Tree Pruning,Tree on footpath (between no 13 and no 15 Ardc...
281131,281131,ireland_10013,IRELAND,01/01/2018,general,street lighting,street,street_lighting,New street lights,New street lights only give out a small amount...
281132,281132,ireland_10014,IRELAND,01/01/2018,general,leaks and drainage,infrastructure,infrastructure_general,Drains become potholes,"Just west of the Vartry Bridge, the drains in ..."
281133,281133,ireland_10015,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street lights,Street lights outside my house is gone months ...
281134,281134,ireland_10016,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street light,Pole no 2 light not working
281135,281135,ireland_10017,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Hedging needs to be cut back,When coming out of the Bohernabreena cottages ...
281136,281136,ireland_10018,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Extremely lethal huge potholes on road in belg...,Urgent repairs required!!vv dangerous to public!!
281137,281137,ireland_10019,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Light not working,"The street light outside 6 Carlisle Terrace, C..."
281138,281138,ireland_10020,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Melted wheelie bin (post fire).,The base of a wheelie bin (mostly destroyed by...
281139,281139,ireland_10021,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Grass verges,I am aware that the grass verges outside the h...
281140,281140,ireland_10022,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Over flowing bin attracting rats,"The bin at the bottom of Towerview, next to th..."
281141,281141,ireland_10023,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Dead tree outside the house,Hello. One of the trees in our estate died a c...
281142,281142,ireland_10024,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Household rubbish dumped on street.,Bags of household rubbish dumped on the footpa...
281143,281143,ireland_10025,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Abandoned car,"Car has been there months now. No tax, insuran..."
281144,281144,ireland_10026,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Slow speed limit on national road,Hi
281145,281145,ireland_10027,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Litter on pedestrian footpath.,"Litter thrown on footpath outside number 31, t..."
...,...,...,...,...,...,...,...,...,...,...
304175,304175,ireland_9969,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light Not Working,Street LIght not working outside No.39 The Pri...
304176,304176,ireland_9970,IRELAND,01/01/2018,general,leaks and drainage,infrastructure,infrastructure_general,Water leak,There's a water leak at the entrance to The Pr...
304177,304177,ireland_9971,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Road Markings can't be seen,Double yellow lines need to be re-painted at t...
304178,304178,ireland_9972,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Manhole cover,The cover for a virgin telecom box in the path...
304179,304179,ireland_9973,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street light not working,"Hi, The street light right outside house numbe..."
304180,304180,ireland_9974,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Pot holes and speed ramp,Big potholes at entrance to road plus speed ra...
304181,304181,ireland_9976,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Grass Maintenance,I've noticed that the standards of Grass Maint...
304182,304182,ireland_9977,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Broken Street Light,The last and 3rd street light on the left hand...
304183,304183,ireland_9978,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholes,There are 4 potholes across the road joining R...
304184,304184,ireland_9979,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street lights gone.,No 9 and 12 of the street lights in Johnstown ...
304185,304185,ireland_9980,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Grass & Hedges on Green need to be maintained,The Grass on Warren Green badly needs to be cu...
304186,304186,ireland_9981,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Pothole,Pothole on road
304187,304187,ireland_9982,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholes,Potholes extending from old fire station headi...
304188,304188,ireland_9983,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Speed Limit Signs,Can't read the speed limit signs because of th...
304189,304189,ireland_9984,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,School Warning Sign,School warning sign is obscured by bushes.
304190,304190,ireland_9985,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Speed Limit Signs,Can't read speed limit sign as it's so dirty.
304191,304191,ireland_9986,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholes,Potholes from Tom Roe's point to Donor's Green.
304192,304192,ireland_9987,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street lighting,Half of Dunehaven estate has no lighting for s...
304193,304193,ireland_9988,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Pothole,Very severe pothole immediately after Speed Ra...
304194,304194,ireland_9989,IRELAND,01/01/2018,general,graffiti,vandalism,vandalism_graffiti,Multiple graffati tagging,"Top entrance hunterswood left side wall, all t..."
304195,304195,ireland_999,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Massive amount of rubbish,There is a massive amount of rubbish tipped at...
304196,304196,ireland_9990,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street light gone,Street light hone
304197,304197,ireland_9991,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Tree needs to be cut back,Tree outside 75 greentrees road really needs t...
304198,304198,ireland_9992,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Household waste dumped,Exit Ballaghaderreen via the old N5 [Dublin Ro...
304199,304199,ireland_9993,IRELAND,01/01/2018,general,litter and illegal dumping,environment,environment_dumping,Abandoned car,Black Peugout station wagon abandoned several ...
304200,304200,ireland_9995,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,"Grass, weeds along N5 through castlebar",The N5 through Castlebar(ring road) stretching...
304201,304201,ireland_9996,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,"Grass overgrown, not cut",The approach to Castlebar via the N5( dublin r...
304202,304202,ireland_9997,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light at the marked location not working
304203,304203,ireland_9998,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Lighting problem,Street light not working
304204,304204,ireland_9999,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light not working

In [11]:
for city in df['CITY'].unique():
    display(df[df['CITY']==city].head(3))

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
0,0,US_CHICAGO_1725,US_CHICAGO,10/03/2011,health_environment,permits issued by doe work order,environment,environment_general,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...,[INSPECTION LOG #: 1723 03-OCT-11 18:55:00] TH...
1,1,US_CHICAGO_600301602,US_CHICAGO,07/14/2017,health_environment,illegal dumping work order,environment,environment_dumping,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...,[INSPECTION LOG #: 3439804 14-JUL-17 09:45:00]...
2,2,US_CHICAGO_1106,US_CHICAGO,08/19/2011,health_environment,air pollution work order,environment,environment_air_pollution,REPLACING WINDOWS AND SANDBLASTING CAUSING DUS...,[INSPECTION LOG #: 1104 19-AUG-11 11:06:00] MY...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
48579,48579,US_BATON_ROUGE_220943,US_BATON_ROUGE,03/22/2016 04:40:00 PM,road maintenance issues,pothole,street,street_repair,POTHOLE ON THE SW CORNER OF HILMONT AND SPRING...,NaN
48580,48580,US_BATON_ROUGE_248677,US_BATON_ROUGE,07/27/2016 02:45:00 PM,street/traffic issues,road striping needed,street,street_repair,STREET NEEDS TO BE RE STRIPED AT THE CORNER SO...,NaN
48581,48581,US_BATON_ROUGE_251335,US_BATON_ROUGE,08/09/2016 07:48:00 AM,"drainage, erosion, flooding or holes",cave-in/sink hole (drainage related),infrastructure,infrastructure_general,"STORM DRAINS N FRONTOF HOMR ARE CAVING IN, LI...",NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
281116,281116,ireland_100,IRELAND,01/01/2018,general,road or path defects,street,street_repair,Potholes in Allenwood South,"Hi, I live in Allenwood South (L70044), my hou..."
281117,281117,ireland_10000,IRELAND,01/01/2018,general,street lighting,street,street_lighting,Street Light,Street light not working
281118,281118,ireland_10001,IRELAND,01/01/2018,general,tree and grass maintenance,environment,environment_overgrowth,Ditch removal,Ditch trees and brambles recently removed by t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
304205,304205,US_CINCINNATI_SR18080929,US_CINCINNATI,08/26/2018,police department,"default, police (and junk veh)",environment,environment_abandoned_vehicle,"""Request entered through the Web. Refer to Int...",NaN
304206,304206,US_CINCINNATI_SR18080942,US_CINCINNATI,08/26/2018,public services,"tires, special collection",environment,environment_garbage_collection,"""Request entered through the Web. Refer to Int...",NaN
304207,304207,US_CINCINNATI_SR16100686,US_CINCINNATI,12/04/2016,police department,"default, police (and junk veh)",environment,environment_abandoned_vehicle,"""Request entered through the Web. Refer to Int...",NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
822979,822979,US_BLOOMINGTON_470,US_BLOOMINGTON,2011-06-27T04:00:00-04:00,recycling,general,environment,environment_recycling,Recycables and non-recycables waste mixed. 949,NaN
822980,822980,US_BLOOMINGTON_471,US_BLOOMINGTON,2011-06-27T04:00:00-04:00,trash,general,environment,environment_garbage_collection,Exceeds weight Limit of 40 pounds.,NaN
822981,822981,US_BLOOMINGTON_472,US_BLOOMINGTON,2011-06-27T04:00:00-04:00,trash,general,environment,environment_garbage_collection,Bags/cans must have sticker attached. 956,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913427,0,SEECLICKFIX_0,City of Chicago,2014-01-09T12:33:52-05:00,NaN,graffiti removal,vandalism,vandalism_graffiti,Graffiti Removal,NaN
913428,1,SEECLICKFIX_6,City of Chicago,2014-01-09T12:23:23-05:00,NaN,building violation,planning,planning_unsafe_environment,Building Violation,Locked
913429,2,SEECLICKFIX_7,City of Chicago,2014-01-09T12:22:15-05:00,NaN,graffiti removal,vandalism,vandalism_graffiti,Graffiti Removal,Duplicate

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913431,4,SEECLICKFIX_10,City of Oakland - OLD,2014-01-09T11:54:22-05:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,NaN
913432,5,SEECLICKFIX_11,City of Oakland - OLD,2014-01-09T11:52:07-05:00,NaN,illegal dumping,environment,environment_dumping,Chair at the off ramp of Tunnel Road from the ...,Someone has left a chair near the off ramp fro...
913436,9,SEECLICKFIX_18,City of Oakland - OLD,2014-01-09T11:28:42-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on the center divider of 580 freeway ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913447,20,SEECLICKFIX_31,New Haven,2014-01-09T09:37:09-05:00,NaN,public space streets and drains,street,street_drainage,Public Space Streets and Drains,When will State be passable again?
913503,76,SEECLICKFIX_113,New Haven,2014-01-08T14:28:03-05:00,NaN,traffic/road safety,street,street_general,Speed bumps on Lyon St.?,Along with non-residential parkers Lyon St. is...
913528,101,SEECLICKFIX_145,New Haven,2014-01-08T10:39:31-05:00,NaN,potholes,street,street_repair,Potholes,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913500,73,SEECLICKFIX_108,City of Albuquerque - Signs & Markings,2014-01-08T15:00:19-05:00,NaN,traffic signs,street,street_urgent_repair,U-turn sign knocked down,u-turn sign is knocked down
913563,136,SEECLICKFIX_214,City of Albuquerque - Signs & Markings,2014-01-07T16:34:43-05:00,NaN,traffic signs,street,street_urgent_repair,Traffic Calming Circle Signage Destroyed,The traffic calming circle signage has been pu...
913589,162,SEECLICKFIX_261,City of Albuquerque - Signs & Markings,2014-01-07T08:58:15-05:00,NaN,traffic signs,street,street_urgent_repair,Traffic Signs,Not a sign but a burned out lamp in overhead g...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913507,80,SEECLICKFIX_118,SeeClickFix Debris Mapper,2014-01-08T13:28:28-05:00,NaN,other,governance,governance_general,No Heat!!!,Have been without heat since October
913508,81,SEECLICKFIX_119,SeeClickFix Debris Mapper,2014-01-08T13:24:24-05:00,NaN,other,governance,governance_general,insufficient heat,The heat comes on maybe 3 times a day fro a fe...
913538,111,SEECLICKFIX_176,SeeClickFix Debris Mapper,2014-01-07T23:13:58-05:00,NaN,other,governance,governance_general,No heat or hot water reported several times,I have reported no heat and hot water over 20 ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913553,126,SEECLICKFIX_204,OLD City of Richmond,2014-01-07T18:25:57-05:00,NaN,other,governance,governance_general,Alley in need of repair,The 600 block alley between 1st and St. James ...
913590,163,SEECLICKFIX_263,OLD City of Richmond,2014-01-07T08:43:23-05:00,NaN,other,governance,governance_general,Potholes in Alley,Please fill potholes in alley between Whitby R...
916484,3057,SEECLICKFIX_4846,OLD City of Richmond,2013-11-02T10:29:45-04:00,NaN,other,governance,governance_general,Other,Sidewalk

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913560,133,SEECLICKFIX_211,Go! Fix,2014-01-07T16:50:58-05:00,NaN,other,governance,governance_general,Delivery Drivers still using Cycleway as a loa...,It is still too common an occurrence that deli...
913606,179,SEECLICKFIX_286,Go! Fix,2014-01-06T22:33:25-05:00,NaN,report: pothole/road surface damage,street,street_repair,Shared Use Path not marked,The shared use path marked on Cycleway Info is...
913650,223,SEECLICKFIX_360,Go! Fix,2014-01-06T11:40:23-05:00,NaN,report: pothole/road surface damage,street,street_repair,Road surface badly broken,Road surface very rough near corner of William...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913588,161,SEECLICKFIX_260,New Haven Parks Department,2014-01-07T09:31:56-05:00,NaN,trimming - priority 2,environment,environment_overgrowth,Trim,large maple tree limbs falling located between...
913802,375,SEECLICKFIX_617,New Haven Parks Department,2014-01-03T08:54:22-05:00,NaN,stumps,environment,environment_overgrowth,TRIMMING,NaN
913843,416,SEECLICKFIX_687,New Haven Parks Department,2014-01-02T11:12:05-05:00,NaN,stumps,environment,environment_overgrowth,Stump,a/f 1863-1865 Chapel St

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913656,229,SEECLICKFIX_373,Quincy MA,2014-01-06T10:54:36-05:00,NaN,snow plowing,street,street_slippery,Question About Hilly Residential Streets,Is it normal in Quincy for hilly residential s...
913714,287,SEECLICKFIX_484,Quincy MA,2014-01-04T15:41:40-05:00,NaN,snow plowing,street,street_slippery,Business Piling Snow on Sidewalk,Air Graphics removed snow from their driveway ...
914097,670,SEECLICKFIX_1234,Quincy MA,2013-12-26T11:11:31-05:00,NaN,traffic - sign/crosswalk,street,street_urgent_repair,Aggressive Driver on the Loose Almost Killed T...,Note: video and additional photos will be adde...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913661,234,SEECLICKFIX_381,Coatesville,2014-01-06T09:53:55-05:00,NaN,fire issues,fire,fire_risks,danger doors blocked,car blocks entrance to apt doors
914112,685,SEECLICKFIX_1267,Coatesville,2013-12-25T15:28:58-05:00,NaN,pothole,street,street_repair,road pumps poteholes,every street ave alley needs fixed one way or ...
915277,1850,SEECLICKFIX_2707,Coatesville,2013-12-11T18:32:30-05:00,NaN,street light,street,street_lighting,Street Lights Out,Street Lights Out located N 5th Ave and Lumber...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913665,238,SEECLICKFIX_388,City of Miami,2014-01-06T08:20:00-05:00,NaN,road hazard,street,street_general,Road Hazard,Street sign down
961589,48162,SEECLICKFIX_119005,City of Miami,2018-09-19T22:03:42-04:00,NaN,road hazard,street,street_general,Growing sink hole,There was recently some construction on SW 11t...
983733,70306,SEECLICKFIX_146443,City of Miami,2018-08-29T14:56:18-04:00,NaN,road hazard,street,street_general,Road Hazard,There is a water puddle. The water puddle mus...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913692,265,SEECLICKFIX_431,Brentwood Borough,2014-01-05T15:37:07-05:00,NaN,traffic signal,street,street_urgent_repair,Traffic light not staying green for Brownsvill...,On Brownsville Road I travel past Giant Eagle ...
917137,3710,SEECLICKFIX_6022,Brentwood Borough,2013-10-15T11:36:23-04:00,NaN,other,governance,governance_general,Illegally Parked Vehicle on Clermont Ave/Glend...,There is a car that continually parks at the i...
917139,3712,SEECLICKFIX_6024,Brentwood Borough,2013-10-15T11:28:52-04:00,NaN,sidewalk hazard,street,street_sidewalk,Weeds covering sidewalk and person parking on ...,The sidewalk at the intersection of Glendale A...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913706,279,SEECLICKFIX_473,Midtown Alliance,2014-01-04T18:21:57-05:00,NaN,streetlight,street,street_lighting,Streetlight,Need a left turn signal to enter to ABG
915691,2264,SEECLICKFIX_3405,Midtown Alliance,2013-11-27T09:17:17-05:00,NaN,streetlight,street,street_lighting,Paint is chipping away at base,Two lamp posts on 6th and Peachtree (next to C...
916806,3379,SEECLICKFIX_5383,Midtown Alliance,2013-10-24T14:20:44-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,Grate needs to be repaired by the City. Hazard...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913747,320,SEECLICKFIX_525,City of Cambridge (Powered by Leland Cheung),2014-01-03T21:04:18-05:00,NaN,other,governance,governance_general,extremely uneven road,A few years ago Nstar tore apart Clinton Stree...
914111,684,SEECLICKFIX_1266,City of Cambridge (Powered by Leland Cheung),2013-12-25T16:04:46-05:00,NaN,other,governance,governance_general,I don't know,I am 82 years old. It's become difficult to cl...
915655,2228,SEECLICKFIX_3356,City of Cambridge (Powered by Leland Cheung),2013-11-29T00:34:31-05:00,NaN,other,governance,governance_general,Blind intersection when on Hancock and crossin...,Driving down Hancock and making the crossing a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913776,349,SEECLICKFIX_576,SeeClickFix,2014-01-03T12:24:31-05:00,NaN,other,governance,governance_general,Sunken area in road,Due to the Pike & Rose construction there is a...
915851,2424,SEECLICKFIX_3677,SeeClickFix,2013-11-22T10:56:24-05:00,NaN,other,governance,governance_general,Road is heavily damaged,Road is bulging and broken making cars jump in...
916375,2948,SEECLICKFIX_4641,SeeClickFix,2013-11-05T20:39:28-05:00,NaN,other,governance,governance_general,Construction of 1160 Hammond Apartments,Regarding the construction of 1160 Hammond Apa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913824,397,SEECLICKFIX_656,Bibb County,2014-01-02T17:08:30-05:00,NaN,pothole,street,street_repair,POTHOLE,Near Piedmont Orthopaedic Complex on Bowman Blvd
913825,398,SEECLICKFIX_657,Bibb County,2014-01-02T17:04:17-05:00,NaN,pothole,street,street_repair,POTHOLE,It's a huge pothole. My whole wheel fits in it...
914047,620,SEECLICKFIX_1140,Bibb County,2013-12-27T12:59:28-05:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913846,419,SEECLICKFIX_692,Boston 311,2014-01-02T10:39:05-05:00,NaN,other,governance,governance_general,Snow removal,Elderly woman (about 90 years old) lives alo...
913850,423,SEECLICKFIX_698,Boston 311,2014-01-02T10:08:51-05:00,NaN,other,governance,governance_general,Snow shoveling,I was injured in a bicycle accident in June a...
913852,425,SEECLICKFIX_701,Boston 311,2014-01-02T10:08:51-05:00,NaN,other,governance,governance_general,Snow shoveling,I was injured in a bicycle accident in June a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913902,475,SEECLICKFIX_812,City of Brookhaven,2013-12-31T12:42:49-05:00,NaN,parks,governance,governance_parks_and_rec,Parks Problem,Safety issue. Little kids could run through to...
915909,2482,SEECLICKFIX_3789,City of Brookhaven,2013-11-20T16:56:55-05:00,NaN,parks,governance,governance_parks_and_rec,Parks Problem,NaN
916232,2805,SEECLICKFIX_4365,City of Brookhaven,2013-11-11T10:00:50-05:00,NaN,parks,governance,governance_parks_and_rec,Fence Down along Path in Blackburn,The downed fence along the Path in Blackburn a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913908,481,SEECLICKFIX_821,Test,2013-12-31T10:45:57-05:00,NaN,potholes,street,street_repair,This is a test,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913914,487,SEECLICKFIX_845,Smith County TX,2013-12-31T09:32:45-05:00,NaN,pothole,street,street_repair,Hazardous road,This road is so bad it is going to mess up veh...
915417,1990,SEECLICKFIX_2941,Smith County TX,2013-12-06T14:23:25-05:00,NaN,other,governance,governance_general,ROUGH ROAD,ROAD IS NARROW AND HAS POT HOLES AND VERY ROUG...
915953,2526,SEECLICKFIX_3872,Smith County TX,2013-11-19T14:11:40-05:00,NaN,tree or tree limb hazard,environment,environment_overgrowth,Tree limb on power line,Dead tree limb is laying on power line at the ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913915,488,SEECLICKFIX_850,City of Chula Vista,2013-12-31T09:30:35-05:00,NaN,trees,environment,environment_overgrowth,Tree trimming needed K st. - between Broadway ...,Tree trimming needed on K st between Broadway ...
914037,610,SEECLICKFIX_1125,City of Chula Vista,2013-12-27T15:58:42-05:00,NaN,trees,environment,environment_overgrowth,Dead Palm Tree,Reporting dead palm tree between the sidewalk ...
914255,828,SEECLICKFIX_1497,City of Chula Vista,2013-12-20T20:12:51-05:00,NaN,trees,environment,environment_overgrowth,Roots Causing Damage,Tree needs to be trimmed or taken out as it’s ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913916,489,SEECLICKFIX_851,SF City Attorney's Office,2013-12-31T09:29:51-05:00,NaN,criminal activity,public_order,publicorder_general,974 Geneva,Dec 22nd SWAT action where prostitutes were ar...
1217122,303695,SEECLICKFIX_455647,SF City Attorney's Office,2015-08-02T12:43:29-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,There are two wires with red tape attached to ...
1217589,304162,SEECLICKFIX_456309,SF City Attorney's Office,2015-07-27T18:26:17-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Garbage dumped on MUNI platform. Has been here...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
913925,498,SEECLICKFIX_877,DC 311,2013-12-30T21:47:20-05:00,NaN,curb and gutter repair,street,street_drainage,Curb and Gutter Repair,Storm drains along corner of Longfellow St. NW...
914186,759,SEECLICKFIX_1385,DC 311,2013-12-23T08:13:08-05:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,NaN
914187,760,SEECLICKFIX_1386,DC 311,2013-12-23T06:35:33-05:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
914244,817,SEECLICKFIX_1478,City of Tontitown,2013-12-21T11:42:18-05:00,NaN,streets - pothole,street,street_repair,Streets - Pothole,While patrolling had three different citizens ...
918463,5036,SEECLICKFIX_8218,City of Tontitown,2013-09-20T12:37:06-04:00,NaN,overgrown grass/weed,environment,environment_overgrowth,Overgrown Grass/Weed,Overgrown area visible from 411
1223735,310308,SEECLICKFIX_465727,City of Tontitown,2015-05-01T16:02:03-04:00,NaN,overgrown grass/weed,environment,environment_overgrowth,Overgrown Grass/Weed,(E) Weeds . Owners or occupants of real ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
914303,876,SEECLICKFIX_1577,Newnan GA,2013-12-19T17:12:18-05:00,NaN,other can include anything that is not on list...,governance,governance_general,Parking Issue,Residents constantly park in the alleyway in a...
924148,10721,SEECLICKFIX_15346,Newnan GA,2013-08-08T15:27:20-04:00,NaN,illegal dumping,environment,environment_dumping,ILLEGAL DUMPING IN YARD,APPARENTLY NO ONE HAS ADDRESSSED THIS COMPLAIN...
947032,33605,SEECLICKFIX_100534,Newnan GA,2018-09-26T17:39:36-04:00,NaN,other can include anything that is not on list...,governance,governance_general,Parking and City Ordinance Violation/unsafe sh...,The residents at 218 Arlington Court have a sh...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
914311,884,SEECLICKFIX_1594,City of St. Paul,2013-12-19T12:38:46-05:00,NaN,pothole,street,street_repair,Pothole of doom,Before the northbound Rober St. stopsign there...
915043,1616,SEECLICKFIX_2341,City of St. Paul,2013-12-18T18:35:07-05:00,NaN,street lights,street,street_lighting,Street Lights,Flashing on and off intermittently too dark on...
916326,2899,SEECLICKFIX_4554,City of St. Paul,2013-11-07T10:06:32-05:00,NaN,traffic signals,street,street_urgent_repair,Traffic Signals,Need to leave left turn on til later on am. Wa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915141,1714,SEECLICKFIX_2494,City of Harrisburg,2013-12-16T14:49:29-05:00,NaN,street maintenance,street,street_general,Deep Pothole,Deep pothole in front of 220 Peffer; almost ap...
919471,6044,SEECLICKFIX_9495,City of Harrisburg,2013-09-11T23:08:35-04:00,NaN,street maintenance,street,street_general,Broken stop sign,Stop sign leaning into delaware street at susq...
930939,17512,SEECLICKFIX_25939,City of Harrisburg,2013-04-09T16:25:07-04:00,NaN,street maintenance,street,street_general,Broken Parking Meter,The meter just reads fail and will not accept ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915161,1734,SEECLICKFIX_2522,Sarasota County (Pilot),2013-12-16T09:38:03-05:00,NaN,street light,street,street_lighting,giant pothole,giant pothole in the intersection of Tarawa an...
915341,1914,SEECLICKFIX_2816,Sarasota County (Pilot),2013-12-09T16:57:41-05:00,NaN,pothole,street,street_repair,Street Light Working now,DONE
917011,3584,SEECLICKFIX_5799,Sarasota County (Pilot),2013-10-18T08:09:09-04:00,NaN,street light,street,street_lighting,Pothole,There is a pothole in the middle of the road o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915218,1791,SEECLICKFIX_2609,Go! Fix & Bike North,2013-12-13T17:59:00-05:00,NaN,report: pothole/surface damage,street,street_repair,Report: Pothole/surface damage,From Birdwood Avenue to Eastern Arterial Road ...
917189,3762,SEECLICKFIX_6113,Go! Fix & Bike North,2013-10-14T04:31:35-04:00,NaN,report: pothole/surface damage,street,street_repair,Magnolia Avenue and Plympton Rd pothole,Pothole at the corner of Magnolia Avenue and P...
917194,3767,SEECLICKFIX_6124,Go! Fix & Bike North,2013-10-13T18:12:57-04:00,NaN,report: pothole/surface damage,street,street_repair,Depressed road surface,Heath Street near North Road. The road surfac...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915248,1821,SEECLICKFIX_2653,City of Somerville,2013-12-12T22:04:19-05:00,NaN,other - city issues,governance,governance_signage,Illegal double utility pole,There is an illegal double utility pole at the...
915662,2235,SEECLICKFIX_3369,City of Somerville,2013-11-28T11:49:00-05:00,NaN,other - city issues,governance,governance_signage,3 double utility poles in a row,There are three double utility poles in a row ...
916025,2598,SEECLICKFIX_4030,City of Somerville,2013-11-16T23:41:53-05:00,NaN,other - city issues,governance,governance_signage,Illegal double utility pole,State law requires utility companies to remove...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915274,1847,SEECLICKFIX_2703,Town of Franklin,2013-12-11T20:47:07-05:00,NaN,traffic light,street,street_urgent_repair,state problem,as reportsd before You did follow up on it & g...
916413,2986,SEECLICKFIX_4713,Town of Franklin,2013-11-04T22:52:55-05:00,NaN,traffic light,street,street_urgent_repair,Pond Street/Oak Street intersection traffic li...,Vehicles traveling south on Pond Street and en...
916526,3099,SEECLICKFIX_4910,Town of Franklin,2013-11-01T12:16:51-04:00,NaN,pothole,street,street_repair,Whole Side of the Cul-de Sac,Whole Side of the Cul-de Sac is shredded. The ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915294,1867,SEECLICKFIX_2737,City of Lansing,2013-12-11T10:52:31-05:00,NaN,other,governance,governance_general,PARKING ON LAWN,RESIDENT PARKS HIS SUV ON HIS LAWN NEXT TO HIS...
915330,1903,SEECLICKFIX_2798,City of Lansing,2013-12-10T08:14:11-05:00,NaN,"grass & weeds over 8\ tall""",environment,environment_overgrowth,crap in yard,cut down tree in yard has been left in the yar...
915332,1905,SEECLICKFIX_2800,City of Lansing,2013-12-10T08:02:18-05:00,NaN,"grass & weeds over 8\ tall""",environment,environment_overgrowth,lawn trash,landlord refuses to take care of property. hig...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915387,1960,SEECLICKFIX_2892,Roosevelt Island,2013-12-07T21:01:46-05:00,NaN,other,governance,governance_general,NYPD/PSD running stop signs,"Bad enough that we have \regular\"" drivers blo..."
916414,2987,SEECLICKFIX_4714,Roosevelt Island,2013-11-04T22:19:20-05:00,NaN,other,governance,governance_general,Pot smoking,It has become difficult to walk along the Rive...
916889,3462,SEECLICKFIX_5561,Roosevelt Island,2013-10-22T17:21:28-04:00,NaN,parks,governance,governance_parks_and_rec,Fence Blowing in the Breeze,Fence separating main playground from swing ar...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915499,2072,SEECLICKFIX_3079,Saugus Town Hall,2013-12-04T11:25:56-05:00,NaN,tree issues,environment,environment_overgrowth,Tree destroying side-walk and now dangerous.,To Whom It May Concern: I have a tree dir...
916210,2783,SEECLICKFIX_4332,Saugus Town Hall,2013-11-11T19:28:19-05:00,NaN,sidewalk repair,street,street_sidewalk,Bowing sidewalk/uneven,Sidewalk at 22 Susan Drive is in need of repaving
917677,4250,SEECLICKFIX_7107,Saugus Town Hall,2013-09-30T11:06:44-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Roots Disturbed Sidewalk,The roots from the tree have lifted the sidewa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
915706,2279,SEECLICKFIX_3433,City of Holyoke,2013-11-26T15:46:39-05:00,NaN,other,governance,governance_general,Other,Hello this tree has grown at an angle and is n...
916726,3299,SEECLICKFIX_5244,City of Holyoke,2013-10-27T07:09:11-04:00,NaN,other,governance,governance_general,MICE AND MOUSES,YES THE LANDLORD BRONG SOME STUFF OVER BUT THE...
938594,25167,SEECLICKFIX_89859,City of Holyoke,2018-10-01T09:24:50-04:00,NaN,streets and sidewalks,street,street_sidewalk,Streets and Sidewalks,Pothole in left lane

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916008,2581,SEECLICKFIX_3990,Burlington VT,2013-11-17T19:37:48-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Moran Plant,The Moran Plant has been a city eye sore for y...
916160,2733,SEECLICKFIX_4243,Burlington VT,2013-11-13T08:43:49-05:00,NaN,graffiti on private property,vandalism,vandalism_graffiti,Fairpoint box on pole still not cleaned,This issue had been closed in SCF as I had con...
922171,8744,SEECLICKFIX_12751,Burlington VT,2013-08-26T11:00:50-04:00,NaN,graffiti on private property,vandalism,vandalism_graffiti,graffiti,graffiti on chimney of Blodgett Ovens building

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916023,2596,SEECLICKFIX_4018,Sacramento County,2013-11-17T11:23:55-05:00,NaN,other,governance,governance_general,Other,Code VIo
1086943,173516,SEECLICKFIX_283925,Sacramento County,2017-10-13T16:23:04-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal dumping,NaN
1087231,173804,SEECLICKFIX_284355,Sacramento County,2017-10-11T19:26:44-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal dumping,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916157,2730,SEECLICKFIX_4240,City of Malden,2013-11-13T09:11:16-05:00,NaN,sidewalk or curb repair,street,street_sidewalk,Asphalt Sidewalk Repair - 10 Webber Street,The asphalt sidewalk in front of 10 Webber is ...
917007,3580,SEECLICKFIX_5779,City of Malden,2013-10-18T14:39:30-04:00,NaN,sidewalk or curb repair,street,street_sidewalk,Sidewalk,Roots breaking asphalt sidewalk
919573,6146,SEECLICKFIX_9618,City of Malden,2013-09-11T15:05:40-04:00,NaN,tree - new tree request or stump removal,environment,environment_overgrowth,2 Trees Removed- When/Where is Replacement Sch...,Hi I live on Vernon street and yesterday 2 tre...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916391,2964,SEECLICKFIX_4676,SF311,2013-11-05T11:43:11-05:00,NaN,sidewalk defect,street,street_sidewalk,Sidewalk Defect,Broken PG&E cement high voltage box at corner ...
920667,7240,SEECLICKFIX_10924,SF311,2013-09-04T13:52:58-04:00,NaN,street or sidewalk cleaning,street,street_sidewalk,Street or Sidewalk Cleaning,may be damaging a tree
922532,9105,SEECLICKFIX_13234,SF311,2013-08-22T10:11:50-04:00,NaN,potholes and street defects,street,street_repair,Street Defect (Pothole),7 to 8AM Tuesday and Friday are the best times...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916455,3028,SEECLICKFIX_4796,Long Beach District 5,2013-11-03T14:21:31-05:00,NaN,other,governance,governance_general,No sidewalk,There is no sidewalk at all on the north west ...
916456,3029,SEECLICKFIX_4797,Long Beach District 5,2013-11-03T14:16:45-05:00,NaN,other,governance,governance_general,Handicapped access ramps,We have no. Handicapped access ramps within th...
916457,3030,SEECLICKFIX_4798,Long Beach District 5,2013-11-03T14:13:20-05:00,NaN,other,governance,governance_general,No handicapped access rampsj,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916557,3130,SEECLICKFIX_4974,City of Newton,2013-10-31T11:41:00-04:00,NaN,other,governance,governance_general,Running red light/ Sign change?,Drivers coming from Washington St are continua...
916993,3566,SEECLICKFIX_5757,City of Newton,2013-10-18T21:23:17-04:00,NaN,other,governance,governance_general,Street light out. Between 29 and 39 Marla circle.,Street light is off and on all day and night. ...
922753,9326,SEECLICKFIX_13527,City of Newton,2013-08-20T11:15:05-04:00,NaN,other,governance,governance_general,Poorly Marked Pedestrian Crossing,Hardly any markings designating this pedestria...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916594,3167,SEECLICKFIX_5034,City of Kenosha,2013-10-30T15:33:45-04:00,NaN,other,governance,governance_general,Large portion of concrete buckling on street,there is a large chunk of concrete that has bu...
916847,3420,SEECLICKFIX_5460,City of Kenosha,2013-10-23T16:38:21-04:00,NaN,other,governance,governance_general,Utility cover missing -,In the north-west section of this intersection...
916849,3422,SEECLICKFIX_5464,City of Kenosha,2013-10-23T16:15:23-04:00,NaN,other,governance,governance_general,R.R. X-ing gate at risk of failure -,Counterweights are improperly bolted to the RR...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916600,3173,SEECLICKFIX_5043,City of Toronto,2013-10-30T14:04:48-04:00,NaN,report minor pothole damage,street,street_repair,Water Flowing From Pipe,(This is not a pothole but no other category u...
930632,17205,SEECLICKFIX_25076,City of Toronto,2013-04-18T17:09:11-04:00,NaN,report minor pothole damage,street,street_repair,Carlaw Sinkhole,this has been filled about 5 times. Obviously ...
931789,18362,SEECLICKFIX_28293,City of Toronto,2013-03-05T22:24:18-05:00,NaN,graffiti on private property,vandalism,vandalism_graffiti,Graffiti on private property,On side of building - Lamb Av.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916793,3366,SEECLICKFIX_5357,Town of Westborough,2013-10-24T19:01:52-04:00,NaN,other,governance,governance_general,sinkhole in road,small hole in road surface looks open undernea...
917826,4399,SEECLICKFIX_7342,Town of Westborough,2013-09-26T17:52:43-04:00,NaN,other,governance,governance_general,sidewalk,NaN
917897,4470,SEECLICKFIX_7443,Town of Westborough,2013-09-25T19:00:58-04:00,NaN,other,governance,governance_general,Other,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
916950,3523,SEECLICKFIX_5673,City of Dunwoody,2013-10-21T11:26:06-04:00,NaN,sidewalk problem,street,street_sidewalk,Sidewalk Problem,Pavers settling
946038,32611,SEECLICKFIX_99259,City of Dunwoody,2018-09-27T09:00:10-04:00,NaN,sidewalk problem,street,street_sidewalk,Sidewalk Problem,I understand there is a large construction pro...
961732,48305,SEECLICKFIX_119167,City of Dunwoody,2018-09-19T20:29:23-04:00,NaN,street light problem,street,street_lighting,Street light malfunctioning,The street light located at 4926 leisure valle...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
917044,3617,SEECLICKFIX_5860,Kermit TX,2013-10-17T11:28:09-04:00,NaN,nuisance weed/ brush,environment,environment_overgrowth,Nuisance Weed/ Brush,NaN
917045,3618,SEECLICKFIX_5861,Kermit TX,2013-10-17T11:25:59-04:00,NaN,illegal dumping/ full dumpster,environment,environment_dumping,Illegal Dumping/ Full Dumpster,NaN
917046,3619,SEECLICKFIX_5862,Kermit TX,2013-10-17T11:25:01-04:00,NaN,illegal dumping/ full dumpster,environment,environment_dumping,Illegal Dumping/ Full Dumpster,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
917359,3932,SEECLICKFIX_6527,City of Fort Lauderdale,2013-10-09T08:05:19-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN
917361,3934,SEECLICKFIX_6532,City of Fort Lauderdale,2013-10-09T06:31:44-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN
917362,3935,SEECLICKFIX_6533,City of Fort Lauderdale,2013-10-09T06:28:58-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
917419,3992,SEECLICKFIX_6656,South Burlington,2013-10-07T13:36:20-04:00,NaN,sidewalks,street,street_sidewalk,Lack of pedestrian facilities at Rice High Sch...,The sidewalk that runs up the hill on Proctor ...
1019199,105772,SEECLICKFIX_191383,South Burlington,2018-07-03T10:11:40-04:00,NaN,other,governance,governance_general,retaining wall next to walkway deteriorated,I reported this problem two weeks ago in perso...
1019415,105988,SEECLICKFIX_191669,South Burlington,2018-07-02T20:45:11-04:00,NaN,sidewalks,street,street_sidewalk,Not Accessible,Bridge is not accessible to disabled.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
917603,4176,SEECLICKFIX_6963,Olathe,2013-10-02T09:48:04-04:00,NaN,other,governance,governance_general,Other,This week the crosswalk signal has been \stuc...
919712,6285,SEECLICKFIX_9771,Olathe,2013-09-10T23:13:48-04:00,NaN,weeds,environment,environment_overgrowth,Weeds,only one half of the lawn gets mowed. west si...
924266,10839,SEECLICKFIX_15501,Olathe,2013-08-07T20:14:54-04:00,NaN,other,governance,governance_general,Other,Tree partially blocking stop sign on SE corner...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
917635,4208,SEECLICKFIX_7036,Reconnect PA,2013-10-01T09:38:06-04:00,NaN,other,governance,governance_general,Road Patching,Roadway patching and overlays on Slaughterhous...
921103,7676,SEECLICKFIX_11412,Reconnect PA,2013-09-03T11:12:46-04:00,NaN,other,governance,governance_general,Obstructed sign. Sign needs replaced,Signs reflectivity is compromised. Sign is on ...
923635,10208,SEECLICKFIX_14685,Reconnect PA,2013-08-12T16:29:23-04:00,NaN,other,governance,governance_general,Florence and Pennsylvania,On Pennsylvania (East side of street) between...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
918861,5434,SEECLICKFIX_8720,Raleigh NC,2013-09-17T17:17:18-04:00,NaN,other,governance,governance_general,Extremely low shoulder,I just witnessed a tractor trailer trying to t...
930339,16912,SEECLICKFIX_24535,Raleigh NC,2013-04-28T08:20:21-04:00,NaN,other,governance,governance_general,complete job,On Friday April 26 the utility dept. fixed at ...
931255,17828,SEECLICKFIX_26932,Raleigh NC,2013-03-27T07:34:13-04:00,NaN,other,governance,governance_general,Cars Not Yielding to Pedestrians,After the pedestrian light is pushed and there...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
920182,6755,SEECLICKFIX_10336,City of Nevada,2013-09-07T00:33:12-04:00,NaN,street light,street,street_lighting,Street Light,Light L529 goes on and off on north east side ...
920183,6756,SEECLICKFIX_10337,City of Nevada,2013-09-07T00:30:51-04:00,NaN,street light,street,street_lighting,Street Light,Light L525 goes on and off in front of 1st Nat...
920185,6758,SEECLICKFIX_10339,City of Nevada,2013-09-07T00:24:03-04:00,NaN,street light,street,street_lighting,Street Light,Light 406 goes on and off middle of main in fr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
920398,6971,SEECLICKFIX_10597,Town of Ayer,2013-09-05T16:17:51-04:00,NaN,potholes,street,street_repair,Curb Cut problems,At the curb cuts on each side of Phil Berry's ...
921042,7615,SEECLICKFIX_11346,Town of Ayer,2013-09-03T13:34:54-04:00,NaN,signs,governance,governance_signage,Signs,Yield sign blocking pedestrians access to cros...
923156,9729,SEECLICKFIX_14034,Town of Ayer,2013-08-17T06:08:47-04:00,NaN,signs,governance,governance_signage,Signs,New street sign at Howard & Pearl has been taken

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
921976,8549,SEECLICKFIX_12474,Cudahy CA,2013-08-28T02:42:01-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Increase Police Presence,Salt Lake Market has been vandalized twice thi...
921977,8550,SEECLICKFIX_12475,Cudahy CA,2013-08-28T02:41:55-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Increase Police Presence,Salt Lake Market has been vandalized twice thi...
921978,8551,SEECLICKFIX_12476,Cudahy CA,2013-08-28T02:41:46-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Increase Police Presence,Salt Lake Market has been vandalized twice thi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
922280,8853,SEECLICKFIX_12899,City of Winston-Salem,2013-08-25T07:02:35-04:00,NaN,streets repair,street,street_repair,Streets Repair,Driveway exit with sizable chunks of displaced...
932186,18759,SEECLICKFIX_29188,City of Winston-Salem,2013-02-20T15:25:20-05:00,NaN,streets repair,street,street_repair,Multiple Potholes,NaN
932187,18760,SEECLICKFIX_29189,City of Winston-Salem,2013-02-20T15:18:19-05:00,NaN,streets repair,street,street_repair,Miserably Embarrassing Repaving Patchwork,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
922709,9282,SEECLICKFIX_13470,Georgetown County,2013-08-20T14:15:29-04:00,NaN,pothole,street,street_repair,Test - Data Management Committee,Test
996965,83538,SEECLICKFIX_163317,Georgetown County,2018-08-10T14:10:20-04:00,NaN,pothole,street,street_repair,Pothole,pot holes turning from Ocean Blvd onto provide...
996980,83553,SEECLICKFIX_163332,Georgetown County,2018-08-10T13:59:25-04:00,NaN,pothole,street,street_repair,Pothole,several large potholes on Otis Blvd . Lots of ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
922917,9490,SEECLICKFIX_13737,City of Stockbridge (City of Stockbridge GA),2013-08-19T12:39:30-04:00,NaN,traffic signals street lights & signs,street,street_urgent_repair,Crime/Safety Issues,There have been numerous vehicle break-ins in ...
946603,33176,SEECLICKFIX_99993,City of Stockbridge (City of Stockbridge GA),2018-09-26T21:13:37-04:00,NaN,traffic signals street lights & signs,street,street_urgent_repair,Traffic Signals Street Lights & Signs,The new street lights in the subdivision are v...
951641,38214,SEECLICKFIX_106457,City of Stockbridge (City of Stockbridge GA),2018-09-25T09:09:42-04:00,NaN,other,governance,governance_general,Other,This may be more of an issue for Code Enforcem...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
922948,9521,SEECLICKFIX_13772,Brookfield MA,2013-08-19T10:44:48-04:00,NaN,other,governance,governance_general,Double pole,This pole was broken in an MVA on March 5 2010
1264405,350978,SEECLICKFIX_520632,Brookfield MA,2014-04-18T18:58:03-04:00,NaN,other,governance,governance_general,Dead hazardous tree,Large dead tree within 15' of the road
1264449,351022,SEECLICKFIX_520684,Brookfield MA,2014-04-18T12:06:27-04:00,NaN,other,governance,governance_general,DOGS,WHY DONT WE FOLLOW Title 41 Code of Federal Re...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
923487,10060,SEECLICKFIX_14479,Torrance,2013-08-13T19:10:04-04:00,NaN,pothole,street,street_repair,Pothole,Test
1057355,143928,SEECLICKFIX_241400,Torrance,2018-04-04T11:59:00-04:00,NaN,pothole,street,street_repair,Pothole,New Graffiti on van ness south of Toyota way.
1061593,148166,SEECLICKFIX_247393,Torrance,2018-03-16T16:24:34-04:00,NaN,pothole,street,street_repair,Graffiti,Graffiti on bill bored corner of crenshaw & De...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
923608,10181,SEECLICKFIX_14647,Raton NM,2013-08-12T19:51:07-04:00,NaN,drainage,street,street_drainage,completely clogged gutter and break in WPA canal,The gutter at Park and S 3rd above the Post Of...
929990,16563,SEECLICKFIX_23883,Raton NM,2013-05-08T23:13:35-04:00,NaN,other,governance,governance_general,sage plants and medians in general,The dead part on the sage plants on main still...
1234363,320936,SEECLICKFIX_484234,Raton NM,2014-10-01T19:33:24-04:00,NaN,pothole,street,street_repair,Pothole,"3\ deep and several years old"""

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
923675,10248,SEECLICKFIX_14730,Gadsden County,2013-08-12T13:16:44-04:00,NaN,pothole,street,street_repair,home,Big pothole all long street and in front of dr...
925172,11745,SEECLICKFIX_16659,Gadsden County,2013-08-01T11:36:20-04:00,NaN,other,governance,governance_general,Mosquito Control,Please spray neighborhood for mosquitos. Rainf...
925173,11746,SEECLICKFIX_16661,Gadsden County,2013-08-01T11:30:45-04:00,NaN,other,governance,governance_general,Mosquitoes,Please come spray our area as the mosquitoes a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
924441,11014,SEECLICKFIX_15729,Voice of San Diego,2013-08-06T22:10:05-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,Non ADA accessible push to cross ped button
931591,18164,SEECLICKFIX_27784,Voice of San Diego,2013-03-13T18:26:07-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,3400 block of Villa Terrace San Diego Ca
931682,18255,SEECLICKFIX_28010,Voice of San Diego,2013-03-11T00:56:33-04:00,NaN,sidewalk repair,street,street_sidewalk,3400 block of villa terrace,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
924529,11102,SEECLICKFIX_15852,Town of Kearny,2013-08-06T10:23:35-04:00,NaN,illegal apartment,housing,housing_general,rent illegal apartment,In the number 166 Belgrove Dr. as well as many...
939592,26165,SEECLICKFIX_91227,Town of Kearny,2018-09-30T13:20:35-04:00,NaN,trees,environment,environment_overgrowth,Tree needs trimming,The tree at the curb in front of 50 Bennett Av...
943147,29720,SEECLICKFIX_95620,Town of Kearny,2018-09-28T10:27:43-04:00,NaN,potholes,street,street_repair,Pothole,Driving eastward As you make the right turn fr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
924660,11233,SEECLICKFIX_16015,Town of Enfield,2013-08-05T14:44:36-04:00,NaN,parks,governance,governance_parks_and_rec,Playground equipment,The plastic tic-tac-toe pieces on the large pl...
929918,16491,SEECLICKFIX_23732,Town of Enfield,2013-05-11T10:31:03-04:00,NaN,other,governance,governance_general,locker room benches,several lengths of bench are in serious shape ...
931704,18277,SEECLICKFIX_28072,Town of Enfield,2013-03-09T13:21:25-05:00,NaN,other,governance,governance_general,They are letting the public down...,Totally not acceptable from the USPS. This lo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
924795,11368,SEECLICKFIX_16195,Town of Medway,2013-08-04T16:48:37-04:00,NaN,pothole,street,street_repair,Pothole,Sidewalk hazard
924796,11369,SEECLICKFIX_16196,Town of Medway,2013-08-04T16:46:29-04:00,NaN,pothole,street,street_repair,Pothole,NaN
927883,14456,SEECLICKFIX_20186,Town of Medway,2013-07-12T10:09:07-04:00,NaN,pothole,street,street_repair,Pothole,Rim breaker

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
924863,11436,SEECLICKFIX_16279,City of Red Deer,2013-08-03T16:43:08-04:00,NaN,other,governance,governance_general,Outside noise of unknown behaviour people,Me and gf were at a movie till 11.45 got home ...
930848,17421,SEECLICKFIX_25666,City of Red Deer,2013-04-11T16:53:37-04:00,NaN,other,governance,governance_general,Back Lane - Poor Condition,The back lane between 38 Shaw Close and Suther...
930938,17511,SEECLICKFIX_25938,City of Red Deer,2013-04-09T16:33:17-04:00,NaN,other,governance,governance_general,Unkept Land,There used to be an Atco gas shed located at t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
925491,12064,SEECLICKFIX_17059,Redding CT,2013-07-30T16:36:30-04:00,NaN,trees,environment,environment_overgrowth,Trees,Branch needs trimming.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
925911,12484,SEECLICKFIX_17588,Missouri DOT,2013-07-28T17:09:58-04:00,NaN,pothole,street,street_repair,Pothole,Many large potholes from leonor Sullivan up to...
927944,14517,SEECLICKFIX_20284,Missouri DOT,2013-07-11T13:25:35-04:00,NaN,pothole,street,street_repair,Pothole,We break our dumpster wheels on this area at t...
928141,14714,SEECLICKFIX_20591,Missouri DOT,2013-07-08T11:58:10-04:00,NaN,pothole,street,street_repair,# Yr OLD Pothole/CRATER,Welp. Its July 2013 and the crater sized pot h...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
926571,13144,SEECLICKFIX_18420,City of Haverhill,2013-07-24T12:13:27-04:00,NaN,pothole,street,street_repair,Pothole,Many potholes and poor drainage. Looks like ...
927848,14421,SEECLICKFIX_20141,City of Haverhill,2013-07-12T14:54:55-04:00,NaN,pothole,street,street_repair,poor road,It's been almost 30 years since our culdesac h...
927981,14554,SEECLICKFIX_20347,City of Haverhill,2013-07-10T19:49:52-04:00,NaN,pothole,street,street_repair,paving,myrtle st needed to be paving last time this w...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
927049,13622,SEECLICKFIX_19039,Fall River MA,2013-07-20T22:15:10-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,Sidewalk completely overgrown it becomes a haz...
1198416,284989,SEECLICKFIX_427755,Fall River MA,2016-03-11T19:56:16-05:00,NaN,report a street light issue,street,street_lighting,Report a Street Light Issue,There are only 2 street lights in this area an...
1198729,285302,SEECLICKFIX_428191,Fall River MA,2016-03-09T17:57:42-05:00,NaN,pothole,street,street_repair,Major pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
927227,13800,SEECLICKFIX_19276,City of Albuquerque - PeopleSoft,2013-07-18T22:42:01-04:00,NaN,other,governance,governance_general,Illegal dog sales puppy mill,Someone (Diana Torres 505-440-3450) is posting...
931914,18487,SEECLICKFIX_28589,City of Albuquerque - PeopleSoft,2013-03-01T09:09:49-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,East side of Hahn arroyo
931915,18488,SEECLICKFIX_28590,City of Albuquerque - PeopleSoft,2013-03-01T09:08:43-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,All over both gates poles an arms. South side ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
927769,14342,SEECLICKFIX_20028,City of Palo Alto,2013-07-15T01:09:16-04:00,NaN,graffiti,vandalism,vandalism_graffiti,tagginh,Noticed the tagging today on my walk.
930977,17550,SEECLICKFIX_26019,City of Palo Alto,2013-04-08T20:10:39-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti on back of cvs,Two spots of graffiti on back loading area and...
931631,18204,SEECLICKFIX_27892,City of Palo Alto,2013-03-12T16:44:57-04:00,NaN,pothole,street,street_repair,Pothole,I need Jon to fix this

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
927914,14487,SEECLICKFIX_20233,Town of Stonington,2013-07-11T16:58:25-04:00,NaN,pothole,street,street_repair,Pothole,Pothole
929636,16209,SEECLICKFIX_23123,Town of Stonington,2013-05-24T07:01:18-04:00,NaN,street lights,street,street_lighting,dangerous utility pole,The utility pole at the corner of Courtland an...
929872,16445,SEECLICKFIX_23653,Town of Stonington,2013-05-13T12:21:23-04:00,NaN,pothole,street,street_repair,Pothole,Pothole near N Stonington Border

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
930852,17425,SEECLICKFIX_25679,Village Service Request,2013-04-11T14:18:48-04:00,NaN,other,governance,governance_general,bike lane ends abruptly,There is a section of Pearl Street that has a ...
931077,17650,SEECLICKFIX_26312,Village Service Request,2013-04-04T15:52:39-04:00,NaN,street light,street,street_lighting,Pedestrian crossing,The five corners lights need to be reprogramed...
931078,17651,SEECLICKFIX_26313,Village Service Request,2013-04-04T15:51:18-04:00,NaN,other,governance,governance_general,Bike lane,There are nice bike lanes on both sides of Pea...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
931173,17746,SEECLICKFIX_26575,Montgomery County,2013-04-01T13:08:59-04:00,NaN,street repair,street,street_repair,Worst repaving job in history,I gave up on this issue after writing a letter...
949832,36405,SEECLICKFIX_104149,Montgomery County,2018-09-25T17:52:04-04:00,NaN,street repair,street,street_repair,Street Repair,water is leaking out of a street light for a l...
959887,46460,SEECLICKFIX_116869,Montgomery County,2018-09-20T18:21:37-04:00,NaN,street repair,street,street_repair,Street Repair,Dead deer different location than other report

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
931698,18271,SEECLICKFIX_28061,City of Houston,2013-03-09T17:48:41-05:00,NaN,other,governance,governance_general,Pothole,Old skin patch needs fresh asphalt
932011,18584,SEECLICKFIX_28796,City of Houston,2013-02-26T19:07:27-05:00,NaN,traffic markings,street,street_general,Sinkhole,This concrete area is across from fire station...
932283,18856,SEECLICKFIX_29485,City of Houston,2013-02-16T01:17:01-05:00,NaN,other,governance,governance_general,Pothole,Pothole in left lane northbound at S Kirkwood ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
931749,18322,SEECLICKFIX_28200,City of North Adams,2013-03-07T11:46:21-05:00,NaN,pothole,street,street_repair,Serious pothole,Shakes my house every time someone drives by.
1272717,359290,SEECLICKFIX_531342,City of North Adams,2014-03-01T09:01:21-05:00,NaN,pothole,street,street_repair,Pothole,Potholes East Masin ST &Church St

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
931811,18384,SEECLICKFIX_28342,Southfield,2013-03-05T07:43:15-05:00,NaN,pothole,street,street_repair,Pot hole lane,There are hundreds of potholes on southbound G...
1222785,309358,SEECLICKFIX_464164,Southfield,2015-05-15T10:52:57-04:00,NaN,pothole,street,street_repair,Pothole,Lahser Road SB from Melrose to just before 8 M...
1222961,309534,SEECLICKFIX_464468,Southfield,2015-05-12T21:25:43-04:00,NaN,pothole,street,street_repair,Pothole,Hugh pothole- at night it is impossible to see...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
932509,19082,SEECLICKFIX_30112,City of Lake Elsinore,2013-02-07T17:38:05-05:00,NaN,pothole - not used,street,street_repair,Pothole,Pothole in front of my home
932538,19111,SEECLICKFIX_30190,City of Lake Elsinore,2013-02-06T16:07:29-05:00,NaN,pothole - not used,street,street_repair,Pothole,Huge pothole in middle of riverside dr on lane...
939003,25576,SEECLICKFIX_90489,City of Lake Elsinore,2018-09-30T20:06:01-04:00,NaN,storm drains,street,street_drainage,Storm Drains,Weeds growing out of and in front of storm drain

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
932788,19361,SEECLICKFIX_30719,City of Wilminton,2013-01-30T15:47:08-05:00,NaN,sidewalk repair,street,street_sidewalk,Large broken slat on sidewalk,Just as sidewalk dips down to meet 6th street ...
935151,21724,SEECLICKFIX_37271,City of Wilminton,2012-10-04T15:12:16-04:00,NaN,street light,street,street_lighting,Street Light,This a TEST issue for the pilot using the mobi...
1223416,309989,SEECLICKFIX_465219,City of Wilminton,2015-05-06T09:24:29-04:00,NaN,other,governance,governance_general,Wasted water,There is a man that hangs out in cool springs ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
933391,19964,SEECLICKFIX_32242,Town of Clarksburg,2013-01-04T12:21:56-05:00,NaN,tree issues,environment,environment_overgrowth,Tree issues,This is a test issue. Please ignore.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
933751,20324,SEECLICKFIX_33249,SCSU,2012-12-13T17:59:20-05:00,NaN,campus sidewalk issues,street,street_sidewalk,Pedestrian Bridge,The Pedestrian Bridge has multiple large pot h...
1128022,214595,SEECLICKFIX_340115,SCSU,2017-02-13T14:11:29-05:00,NaN,campus sidewalk issues,street,street_sidewalk,Campus Sidewalk Issues,Build up of slippery and dangerous ice on path...
1135923,222496,SEECLICKFIX_351210,SCSU,2016-11-28T13:12:58-05:00,NaN,indoor lighting issues - not dorm rooms,housing,housing_safety,Indoor Lighting Issue - flickering light in EN...,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
933764,20337,SEECLICKFIX_33307,Moore OK,2012-12-12T22:05:09-05:00,NaN,street maintenance (pot hole hotline 799-4653),street,street_repair,Lane too narrow,someone decided to redesign the lanes here to ...
939279,25852,SEECLICKFIX_90849,Moore OK,2018-09-30T16:38:30-04:00,NaN,"grass/weeds (over 12\ tall)""",environment,environment_overgrowth,"Grass/Weeds (over 12\ tall)""",Rental property on corner of NE 13th and Bryan...
941685,28258,SEECLICKFIX_93824,Moore OK,2018-09-28T18:04:02-04:00,NaN,"grass/weeds (over 12\ tall)""",environment,environment_overgrowth,"Grass/Weeds (over 12\ tall)""",same story another day. hasn't mowed in over a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
934617,21190,SEECLICKFIX_35742,Stamford,2012-10-30T10:17:05-04:00,NaN,other,governance,governance_general,no power,Old people.. need power
934618,21191,SEECLICKFIX_35743,Stamford,2012-10-30T10:16:49-04:00,NaN,other,governance,governance_general,no power,Old people.. need power
937056,23629,SEECLICKFIX_47256,Stamford,2012-03-21T17:12:17-04:00,NaN,street maintenance,street,street_general,Dengerous Elm St. exit ramp intersection,At the end of the Elm St. exit ramp there are ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
935533,22106,SEECLICKFIX_38998,Union City,2012-08-28T11:45:40-04:00,NaN,fallen tree branches,environment,environment_overgrowth,Fallen tree branches,NaN
935887,22460,SEECLICKFIX_40811,Union City,2012-07-20T12:17:13-04:00,NaN,fallen tree branches,environment,environment_overgrowth,Fallen tree branches,NaN
936264,22837,SEECLICKFIX_42757,Union City,2012-06-09T18:19:52-04:00,NaN,other,governance,governance_general,raised manhole covers,The manholes are above street-level.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
935712,22285,SEECLICKFIX_39997,City of Lansing (Pilot),2012-08-07T14:01:54-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,This is a pilot test issue. Please ignore. Tha...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
935881,22454,SEECLICKFIX_40764,Maryland,2012-07-21T18:17:11-04:00,NaN,tree down,environment,environment_overgrowth,Tree down,tree down on sidewalk
937924,24497,SEECLICKFIX_58062,Maryland,2011-09-07T16:13:40-04:00,NaN,tree down,environment,environment_overgrowth,Tree strike to the house,On 8/27/11 at 710pm a large oak tree fell onto...
937948,24521,SEECLICKFIX_58581,Maryland,2011-08-28T11:21:29-04:00,NaN,tree down,environment,environment_overgrowth,4 trees down,power out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
935885,22458,SEECLICKFIX_40788,City of Snellville,2012-07-20T22:20:40-04:00,NaN,street sign/signal,street,street_urgent_repair,Street Sign/Signal,This is a pilot test issue only.
935886,22459,SEECLICKFIX_40789,City of Snellville,2012-07-20T22:16:56-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,This is a pilot test issue only.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
936508,23081,SEECLICKFIX_44244,Greenfield MA,2012-05-18T12:53:40-04:00,NaN,other,governance,governance_general,Greening Greenfield link,The link to Greening Greenfield doesn't work. ...
936596,23169,SEECLICKFIX_44677,Greenfield MA,2012-05-09T22:36:17-04:00,NaN,other,governance,governance_general,excessive noise,for @ least a month there has been a young man...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
936514,23087,SEECLICKFIX_44272,City of Airdrie,2012-05-17T23:33:18-04:00,NaN,other,governance,governance_general,Capital Project 3 - Bert Church Theatre,Bert Church Theatre expansion
936515,23088,SEECLICKFIX_44273,City of Airdrie,2012-05-17T23:14:13-04:00,NaN,other,governance,governance_general,Capital project 2 - Genesis Place Phase 3,Twin hockey arena
936540,23113,SEECLICKFIX_44390,City of Airdrie,2012-05-16T10:52:11-04:00,NaN,other,governance,governance_general,Garbage is overflowing with dog poop,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
936547,23120,SEECLICKFIX_44451,City of Coral Gables,2012-05-15T14:05:39-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,This is a test request. Please ignore.
936613,23186,SEECLICKFIX_44755,City of Coral Gables,2012-05-08T10:09:04-04:00,NaN,graffiti,vandalism,vandalism_graffiti,USPS,There is graffiti on the mailbox
936856,23429,SEECLICKFIX_46031,City of Coral Gables,2012-04-13T14:19:12-04:00,NaN,graffiti,vandalism,vandalism_graffiti,FPL,There is graffiti on the cement FPL post in fr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
936744,23317,SEECLICKFIX_45458,O'Fallon,2012-04-24T11:55:44-04:00,NaN,nuisance (junk & vehicles weeds),environment,environment_overgrowth,Junk Car,My neighbor have a junk penguin in his yard.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
937250,23823,SEECLICKFIX_48787,City of Palm Springs,2012-02-23T19:20:50-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,qwerty
937253,23826,SEECLICKFIX_48823,City of Palm Springs,2012-02-23T16:16:23-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Test
937254,23827,SEECLICKFIX_48825,City of Palm Springs,2012-02-23T15:54:39-05:00,NaN,pothole,street,street_repair,Test issue - pothole request,This is a test request.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
937895,24468,SEECLICKFIX_57401,North Central Commission Categories,2011-09-21T22:08:41-04:00,NaN,other,governance,governance_general,road needs patched and paved,very rough road. safety concerns.
938063,24636,SEECLICKFIX_62586,North Central Commission Categories,2011-05-06T13:13:00-04:00,NaN,other,governance,governance_general,2.1.16 Kinzua Bridge Investment Area Transport..., There is a need for improved signage along U...
938069,24642,SEECLICKFIX_63017,North Central Commission Categories,2011-04-27T14:37:43-04:00,NaN,other,governance,governance_general,Needs a traffic light when coming off I-80 eas...,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938025,24598,SEECLICKFIX_61413,Manor SeeClickFix,2011-06-13T12:05:03-04:00,NaN,streetlight,street,street_lighting,Streetlight,street light appears to have broken friday nig...
938071,24644,SEECLICKFIX_63127,Manor SeeClickFix,2011-04-26T11:06:43-04:00,NaN,streetlight,street,street_lighting,Streetlight,NaN
938113,24686,SEECLICKFIX_66166,Manor SeeClickFix,2011-03-03T01:08:15-05:00,NaN,streetlight,street,street_lighting,Streetlight,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938101,24674,SEECLICKFIX_65044,Town of Brookline,2011-03-22T14:54:35-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,It says a bad word!

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938187,24760,SEECLICKFIX_73163,SCF Plus Gov,2010-08-27T11:05:09-04:00,NaN,street light,street,street_lighting,Street Light,Testing for SCF Plus

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938197,24770,SEECLICKFIX_74949,Prospect CT,2010-07-14T16:49:01-04:00,NaN,pothole,street,street_repair,Pothole,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938211,24784,SEECLICKFIX_78091,Town of Lexington,2010-05-15T13:07:19-04:00,NaN,trash/recycling,environment,environment_garbage_collection,Trash and Debris on Off Ramp,Is this the town dump - no you could have fool...
1207137,293710,SEECLICKFIX_440896,Town of Lexington,2015-12-14T13:35:00-05:00,NaN,pothole,street,street_repair,Pothole,Pothole in street for over a year.
1214767,301340,SEECLICKFIX_452017,Town of Lexington,2015-09-03T10:09:16-04:00,NaN,street signs,governance,governance_signage,Street Signs,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938213,24786,SEECLICKFIX_79098,City of Russell Springs,2010-04-28T17:53:57-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938216,24789,SEECLICKFIX_81888,Wrentham MA,2010-03-16T14:30:10-04:00,NaN,internal only pothole,street,street_repair,Multi Potholes!,Large potholes have been filled but still very...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938220,24793,SEECLICKFIX_87002,City of Medford,2009-11-19T06:20:42-05:00,NaN,other,governance,governance_general,Stop Sign,Stop Sign Required at Intersection of Hooker S...
938617,25190,SEECLICKFIX_89894,City of Medford,2018-10-01T09:12:24-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,Dead possum in front yard at 86 Bristol rd
938642,25215,SEECLICKFIX_89948,City of Medford,2018-10-01T08:53:13-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,About a year ago Tree Warden Tuden said she wo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938246,24819,SEECLICKFIX_89344,City of Detroit,2018-10-01T11:45:15-04:00,NaN,rodent extermination - bseed only,public_health,publichealth_pests,Rodent Extermination - BSEED Only,LAST BAITED ON 8-30-18
938250,24823,SEECLICKFIX_89350,City of Detroit,2018-10-01T11:43:54-04:00,NaN,dpw - other environmental - dpw use only,environment,environment_general,DPW - Other environmental - DPW USE ONLY,REPEAT OFFENDER
938252,24825,SEECLICKFIX_89352,City of Detroit,2018-10-01T11:43:12-04:00,NaN,dpw - other environmental - dpw use only,environment,environment_general,DPW - Other environmental - DPW USE ONLY,DEBRIS

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938247,24820,SEECLICKFIX_89346,City of Albuquerque,2018-10-01T11:45:04-04:00,NaN,street light - white bulb,street,street_lighting,Street Light - White Bulb,This area is very dark when High school studen...
938294,24867,SEECLICKFIX_89409,City of Albuquerque,2018-10-01T11:25:13-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Next to parking only sign there is graffiti. m...
938304,24877,SEECLICKFIX_89421,City of Albuquerque,2018-10-01T11:22:59-04:00,NaN,weed & litter complaint,environment,environment_overgrowth,Weed & Litter Complaint,Weeds in front yard over 1 foot high.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938248,24821,SEECLICKFIX_89347,City of Hammond,2018-10-01T11:44:27-04:00,NaN,other,governance,governance_general,Other,Reported this as tree overgrown on the utility...
938627,25200,SEECLICKFIX_89914,City of Hammond,2018-10-01T09:04:00-04:00,NaN,damaged/fallen tree or branches,environment,environment_overgrowth,Damaged/Fallen Tree or Branches,There is a large tree branch and misc. trash i...
938681,25254,SEECLICKFIX_90009,City of Hammond,2018-10-01T08:26:37-04:00,NaN,code violation,planning,planning_general,High grass,Needs cutting

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938249,24822,SEECLICKFIX_89348,City of Jersey City,2018-10-01T11:44:10-04:00,NaN,trash: litter/debris/bulk waste,environment,environment_litter,Trash: Litter/debris/bulk waste,can some please pick up the bags on the sidewalk?
938276,24849,SEECLICKFIX_89384,City of Jersey City,2018-10-01T11:34:44-04:00,NaN,trash: litter/debris/bulk waste,environment,environment_litter,Trash: Litter/debris/bulk waste,NaN
938290,24863,SEECLICKFIX_89405,City of Jersey City,2018-10-01T11:26:19-04:00,NaN,trash: litter/debris/bulk waste,environment,environment_litter,Trash: Litter/debris/bulk waste,PEOPLE ARE LEAVING GARBAGE IN THE LOT. PLEASE...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938251,24824,SEECLICKFIX_89351,City of St. Petersburg,2018-10-01T11:43:32-04:00,NaN,abandoned / inoperative vehicle (on private pr...,environment,environment_abandoned_vehicle,Sitting for many years,Old car sitting in driveway with blue tarp ove...
938259,24832,SEECLICKFIX_89361,City of St. Petersburg,2018-10-01T11:40:21-04:00,NaN,stormwater issue,street,street_drainage,Stormwater Issue,Still waiting on action from city to fix this ...
938277,24850,SEECLICKFIX_89385,City of St. Petersburg,2018-10-01T11:34:27-04:00,NaN,alley clearing,environment,environment_general,Alley Clearing,both side of alley need clearing the one side ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938254,24827,SEECLICKFIX_89356,Neighborhoods,2018-10-01T11:42:18-04:00,NaN,yard and/or structure concern (high grass junk...,environment,environment_overgrowth,Yard and/or Structure Concern (High Grass Junk...,Corner of Barrington Dr. and Central Avenue. S...
938451,25024,SEECLICKFIX_89633,Neighborhoods,2018-10-01T10:29:01-04:00,NaN,yard and/or structure concern (high grass junk...,environment,environment_overgrowth,Yard and/or Structure Concern (High Grass Junk...,NaN
938674,25247,SEECLICKFIX_89996,Neighborhoods,2018-10-01T08:31:30-04:00,NaN,yard and/or structure concern (high grass junk...,environment,environment_overgrowth,Yard and/or Structure Concern (High Grass Junk...,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938255,24828,SEECLICKFIX_89357,Newark Service Department,2018-10-01T11:42:16-04:00,NaN,pothole,street,street_repair,Hard to travel alley,Alley. Is full of ruts and potholes making exi...
957843,44416,SEECLICKFIX_114286,Newark Service Department,2018-09-21T19:54:20-04:00,NaN,pothole,street,street_repair,Pothole,There is a pothole here that needs to be fixed...
1008826,95399,SEECLICKFIX_178419,Newark Service Department,2018-07-22T09:21:25-04:00,NaN,other,governance,governance_general,Trees & shrubs need trimmed,There is an alley that runs between Mt. Vernon...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938256,24829,SEECLICKFIX_89358,City of Memphis,2018-10-01T11:41:44-04:00,NaN,curbside trash,environment,environment_dumping,Curbside Trash,Yard waste. Tree branches
938308,24881,SEECLICKFIX_89425,City of Memphis,2018-10-01T11:22:30-04:00,NaN,other,governance,governance_general,Street Sweeper needed,The street sweeper avoids the street directly ...
938351,24924,SEECLICKFIX_89487,City of Memphis,2018-10-01T11:12:09-04:00,NaN,weeds vacant lots,environment,environment_overgrowth,Vines and Weeds Vacant Lots,Vines growing from rear of lot to front of lot...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938257,24830,SEECLICKFIX_89359,City of Alameda,2018-10-01T11:41:42-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Tag #39058 Concern install temp S/W raised 4\....
938264,24837,SEECLICKFIX_89366,City of Alameda,2018-10-01T11:38:40-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Tag #39053 Concern install temp S/W. Cause of ...
938272,24845,SEECLICKFIX_89378,City of Alameda,2018-10-01T11:36:02-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Tag #39059 Concern install temp S/W raised 3\....

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938261,24834,SEECLICKFIX_89363,Code Enforcement Area 5,2018-10-01T11:39:13-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,Tall weeds and grass
938262,24835,SEECLICKFIX_89364,Code Enforcement Area 5,2018-10-01T11:38:42-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,Tall weeds and grass
938265,24838,SEECLICKFIX_89367,Code Enforcement Area 5,2018-10-01T11:38:19-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,Tall weeds and grass

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938266,24839,SEECLICKFIX_89369,City of Canton OH,2018-10-01T11:37:39-04:00,NaN,health hazard,public_health,publichealth_general,Health Hazard,10012018 - Received complaint for trash and de...
938310,24883,SEECLICKFIX_89428,City of Canton OH,2018-10-01T11:22:03-04:00,NaN,health hazard,public_health,publichealth_general,Health Hazard,10012018 - Complaint received for dumped tires...
938322,24895,SEECLICKFIX_89446,City of Canton OH,2018-10-01T11:20:16-04:00,NaN,health hazard,public_health,publichealth_general,Health Hazard,Parcel Number: 10005728 Debris being dumped a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938268,24841,SEECLICKFIX_89371,South San Francisco,2018-10-01T11:37:30-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,miller/westview - couch on the sidewalk
938301,24874,SEECLICKFIX_89418,South San Francisco,2018-10-01T11:23:08-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,cypress park - ON THE EIGHT LANE SIDE - MULTIP...
938309,24882,SEECLICKFIX_89426,South San Francisco,2018-10-01T11:22:30-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,FOURTH LN/MAPLE- VEHICLE SEATS

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938270,24843,SEECLICKFIX_89375,City of Berkeley,2018-10-01T11:36:22-04:00,NaN,other,governance,governance_general,Other,Plants are growing into the bike path through ...
938387,24960,SEECLICKFIX_89542,City of Berkeley,2018-10-01T10:56:15-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Cardboard and trash piled under the fig Tree o...
938522,25095,SEECLICKFIX_89739,City of Berkeley,2018-10-01T09:59:49-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on bollard and sign

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938271,24844,SEECLICKFIX_89377,Fayetteville - Service Request,2018-10-01T11:36:06-04:00,NaN,other,governance,governance_general,Other,Citizen at 2120 Coffman St noticed a leaning t...
938716,25289,SEECLICKFIX_90067,Fayetteville - Service Request,2018-10-01T07:45:10-04:00,NaN,street light repair,street,street_lighting,Street Light Repair,Street light does not work/illuminate.
938717,25290,SEECLICKFIX_90069,Fayetteville - Service Request,2018-10-01T07:43:37-04:00,NaN,street light repair,street,street_lighting,Street Light Repair,Street light does not work/illuminate.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938278,24851,SEECLICKFIX_89387,City of Albany,2018-10-01T11:31:40-04:00,NaN,illegal trash,environment,environment_dumping,Illegal Trash,couch and other debris dumped here at closed V...
938325,24898,SEECLICKFIX_89451,City of Albany,2018-10-01T11:19:57-04:00,NaN,illegal trash,environment,environment_dumping,Illegal Trash,Trash left on street
938437,25010,SEECLICKFIX_89614,City of Albany,2018-10-01T10:34:04-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,the city removed tree but didnt remove the stump

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938279,24852,SEECLICKFIX_89390,City of Oakland,2018-10-01T11:30:50-04:00,NaN,illegal dumping - debris appliances etc.,environment,environment_dumping,Illegal Dumping - debris appliances etc.,Construction site with an overwhelming amount ...
938339,24912,SEECLICKFIX_89472,City of Oakland,2018-10-01T11:15:26-04:00,NaN,illegal dumping - debris appliances etc.,environment,environment_dumping,Illegal Dumping - debris appliances etc.,Tires on road at Bus Stop.
938346,24919,SEECLICKFIX_89481,City of Oakland,2018-10-01T11:13:14-04:00,NaN,illegal dumping - debris appliances etc.,environment,environment_dumping,Illegal Dumping - debris appliances etc.,Tires and trash.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938281,24854,SEECLICKFIX_89393,City of Vallejo,2018-10-01T11:29:23-04:00,NaN,illegal dumping,environment,environment_dumping,Rv’s garbage & human excrement,The white bus/RV that has been parked here al...
938306,24879,SEECLICKFIX_89423,City of Vallejo,2018-10-01T11:22:48-04:00,NaN,abandoned / inoperative vehicle parked on priv...,environment,environment_abandoned_vehicle,Abandoned / Inoperative Vehicle Parked on Priv...,This vehicle has been here three weeks. It is ...
938332,24905,SEECLICKFIX_89463,City of Vallejo,2018-10-01T11:16:23-04:00,NaN,abandoned / inoperative vehicle parked on publ...,environment,environment_abandoned_vehicle,Abandoned / Inoperative Vehicle Parked on Publ...,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938282,24855,SEECLICKFIX_89394,Redford Township MI,2018-10-01T11:29:07-04:00,NaN,high grass / vegetation,environment,environment_overgrowth,High Grass / Vegetation,Only once have they cut there grass garbage ju...
939100,25673,SEECLICKFIX_90611,Redford Township MI,2018-09-30T18:54:37-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,A car had been abandoned in the White Castle p...
940528,27101,SEECLICKFIX_92368,Redford Township MI,2018-09-29T16:37:48-04:00,NaN,water & sewer,infrastructure,infrastructure_water,Filled sewer drainage with dirt,Drainage filled with dirtcausing flooding when...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938284,24857,SEECLICKFIX_89396,Cambridge MA,2018-10-01T11:28:25-04:00,NaN,overflowing public trash/recycling receptacle,environment,environment_garbage_collection,Overflowing Public Trash/Recycling Receptacle,Resident called to report that residents of 21...
938286,24859,SEECLICKFIX_89398,Cambridge MA,2018-10-01T11:27:40-04:00,NaN,other,governance,governance_general,Other,Cambridge Public Works packer truck number 28 ...
938292,24865,SEECLICKFIX_89407,Cambridge MA,2018-10-01T11:26:00-04:00,NaN,tree pruning request,environment,environment_overgrowth,Tree Pruning Request,Please prune tree on the Elm Street side of 21...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938287,24860,SEECLICKFIX_89399,City of Huntsville,2018-10-01T11:27:22-04:00,NaN,high grass/weeds,environment,environment_overgrowth,High Grass/Weeds,Grass in the backyard is way overgrown. Has no...
938607,25180,SEECLICKFIX_89878,City of Huntsville,2018-10-01T09:17:18-04:00,NaN,other,governance,governance_general,Other,Why has this request not had a response in THR...
938693,25266,SEECLICKFIX_90029,City of Huntsville,2018-10-01T08:17:17-04:00,NaN,street light repair,street,street_lighting,Street Light Repair,Street light staying on 247

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938288,24861,SEECLICKFIX_89402,Sarasota County Government,2018-10-01T11:27:06-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,There is n RV converted into a food truck.It i...
938473,25046,SEECLICKFIX_89667,Sarasota County Government,2018-10-01T10:20:01-04:00,NaN,stormwater issue,street,street_drainage,Stormwater Issue,Storm water intake box in ditch at south end o...
938480,25053,SEECLICKFIX_89676,Sarasota County Government,2018-10-01T10:17:55-04:00,NaN,stormwater issue,street,street_drainage,Stormwater Issue,There was work done on the canal that crosses ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938289,24862,SEECLICKFIX_89403,Pinellas County,2018-10-01T11:26:59-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,GRASS OVER 1 FOOT TALL. HAS NOT BEEN MOWED IN ...
938526,25099,SEECLICKFIX_89743,Pinellas County,2018-10-01T09:59:12-04:00,NaN,road issue,street,street_general,Road Issue,We have 4 children and there are many other ch...
938600,25173,SEECLICKFIX_89866,Pinellas County,2018-10-01T09:22:28-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,Camper/ RV parked in front yard partially bloc...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938293,24866,SEECLICKFIX_89408,City of New Britain,2018-10-01T11:25:28-04:00,NaN,pothole,street,street_repair,Pothole,At the intersection of Monroe & Corbin Ave lar...
938698,25271,SEECLICKFIX_90037,City of New Britain,2018-10-01T08:14:41-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Abandoned Vehicle / was first abandoned on Nor...
940451,27024,SEECLICKFIX_92276,City of New Britain,2018-09-29T17:17:48-04:00,NaN,pothole,street,street_repair,Pothole,Measures 4-5ft long by 12” wide. It’s getting ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938296,24869,SEECLICKFIX_89412,Police Non-Emergency,2018-10-01T11:24:31-04:00,NaN,parked vehicle concern,environment,environment_abandoned_vehicle,Parked Vehicle Concern,Illegal street parking. Homeowners are parking...
938444,25017,SEECLICKFIX_89621,Police Non-Emergency,2018-10-01T10:32:25-04:00,NaN,parked vehicle concern,environment,environment_abandoned_vehicle,Parked Vehicle Concern,The car is parked on Royal Haven just south of...
938445,25018,SEECLICKFIX_89624,Police Non-Emergency,2018-10-01T10:31:46-04:00,NaN,parked vehicle concern,environment,environment_abandoned_vehicle,Parked Vehicle Concern,Multiple vehicles parked on grass

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938299,24872,SEECLICKFIX_89416,Private Property,2018-10-01T11:23:26-04:00,NaN,overgrown grass/weeds on private property,environment,environment_overgrowth,Overgrown Grass/Weeds on Private Property,Overgrown Weeds on backside of property facing...
938581,25154,SEECLICKFIX_89839,Private Property,2018-10-01T09:29:52-04:00,NaN,overgrown grass/weeds on private property,environment,environment_overgrowth,Overgrown Grass/Weeds on Private Property,NaN
938690,25263,SEECLICKFIX_90022,Private Property,2018-10-01T08:19:45-04:00,NaN,overgrown grass/weeds on private property,environment,environment_overgrowth,Uncut grass,Grass needs cutting both front and back. Don’t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938302,24875,SEECLICKFIX_89419,City of Fort Dodge,2018-10-01T11:23:08-04:00,NaN,pothole,street,street_repair,Pothole,large hole in the street
940047,26620,SEECLICKFIX_91805,City of Fort Dodge,2018-09-29T23:43:42-04:00,NaN,pothole,street,street_repair,Pothole,street is extremely damaged in multiple places...
941419,27992,SEECLICKFIX_93491,City of Fort Dodge,2018-09-28T21:26:38-04:00,NaN,tall grass/weeds/vegetation,environment,environment_overgrowth,Tall grass/weeds/vegetation,These people are making it hard for me to get ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938313,24886,SEECLICKFIX_89432,City of Chicopee,2018-10-01T11:21:43-04:00,NaN,pothole,street,street_repair,Pothole,NaN
938315,24888,SEECLICKFIX_89434,City of Chicopee,2018-10-01T11:21:18-04:00,NaN,pothole,street,street_repair,Pothole,NaN
938320,24893,SEECLICKFIX_89440,City of Chicopee,2018-10-01T11:20:41-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938321,24894,SEECLICKFIX_89444,Westfield MA,2018-10-01T11:20:21-04:00,NaN,curbside - regular trash/recycling collection,environment,environment_garbage_collection,Curbside - Regular Trash/Recycling Collection,CALLER CLAIMS RECYCLING BIN STILL 3/4 FULL OF ...
938384,24957,SEECLICKFIX_89537,Westfield MA,2018-10-01T10:58:10-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,RESIDENT CLAIMS THE TREE IS TRIMMED EACH YEAR ...
938682,25255,SEECLICKFIX_90010,Westfield MA,2018-10-01T08:24:39-04:00,NaN,road repair (other than pothole),street,street_repair,Road Repair (other than Pothole),CALLER CLAIMS THE SIDEWALK NEEDS REPAIR

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938324,24897,SEECLICKFIX_89450,City of Ferndale MI,2018-10-01T11:19:58-04:00,NaN,street light outage,street,street_lighting,Street Light Outage,The light has been off for a few months.
938389,24962,SEECLICKFIX_89544,City of Ferndale MI,2018-10-01T10:55:20-04:00,NaN,grass & weeds,environment,environment_overgrowth,Grass & Weeds,I left a phone message and requested this a mo...
938597,25170,SEECLICKFIX_89863,City of Ferndale MI,2018-10-01T09:22:59-04:00,NaN,other,governance,governance_general,Other,Drain at Fielding and Farmdale is clogged. Far...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938333,24906,SEECLICKFIX_89464,National City,2018-10-01T11:16:21-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,front axle is damaged not moving for days. Loo...
938946,25519,SEECLICKFIX_90418,National City,2018-09-30T20:43:41-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,NaN
939350,25923,SEECLICKFIX_90934,National City,2018-09-30T15:50:43-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,On tan stucco wall next to busstop.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938341,24914,SEECLICKFIX_89476,Howard County MD,2018-10-01T11:14:37-04:00,NaN,roadway & drainage concern,street,street_drainage,Roadway & Drainage Concern,Storm Drain between the houses the pipes could...
938413,24986,SEECLICKFIX_89581,Howard County MD,2018-10-01T10:44:45-04:00,NaN,roadway & drainage concern,street,street_drainage,Roadway & Drainage Concern,Storm drain behind house is clogged and needs ...
938415,24988,SEECLICKFIX_89585,Howard County MD,2018-10-01T10:43:05-04:00,NaN,roadway & drainage concern,street,street_drainage,Roadway & Drainage Concern,There are two pot holes that have recently bee...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938343,24916,SEECLICKFIX_89478,Town of Hopkinton,2018-10-01T11:13:38-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,Two very large trees on the side of the road a...
945633,32206,SEECLICKFIX_98732,Town of Hopkinton,2018-09-27T10:48:09-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,Broken tree resting on guardrail and extending...
979410,65983,SEECLICKFIX_141136,Town of Hopkinton,2018-09-04T15:13:19-04:00,NaN,other,governance,governance_general,Verizon FIOS box damaged,During the road work on Valentine Road last su...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938345,24918,SEECLICKFIX_89480,City of Lincoln,2018-10-01T11:13:28-04:00,NaN,pothole,street,street_repair,Pothole,Please grind poor asphalt repair on 27th Stree...
938357,24930,SEECLICKFIX_89496,City of Lincoln,2018-10-01T11:09:18-04:00,NaN,pothole,street,street_repair,Pothole,Thank you for grinding this section of pavemen...
938371,24944,SEECLICKFIX_89519,City of Lincoln,2018-10-01T11:03:08-04:00,NaN,street light problem (not traffic signal),street,street_lighting,Street Light Problem (Not Traffic Signal),Residential street light out at the corner of ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938352,24925,SEECLICKFIX_89488,Roadway,2018-10-01T11:11:38-04:00,NaN,pothole,street,street_repair,Pothole,"Not sure if it's considered a \pothole\"" or if..."
938579,25152,SEECLICKFIX_89837,Roadway,2018-10-01T09:31:31-04:00,NaN,traffic signals,street,street_urgent_repair,Traffic Signals,Neighbor keeps putting out orange cones to sav...
938631,25204,SEECLICKFIX_89921,Roadway,2018-10-01T09:01:57-04:00,NaN,other roadway issues,street,street_general,Other Roadway Issues,Work truck spilled loads of papers and plastic...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938362,24935,SEECLICKFIX_89504,City of Taunton,2018-10-01T11:07:07-04:00,NaN,pothole,street,street_repair,Pothole,NaN
938426,24999,SEECLICKFIX_89600,City of Taunton,2018-10-01T10:40:23-04:00,NaN,brush cutting requests,environment,environment_overgrowth,Brush Cutting Requests,Please clear brush
938529,25102,SEECLICKFIX_89748,City of Taunton,2018-10-01T09:57:44-04:00,NaN,pothole,street,street_repair,Pothole,Myrtle and Myrtle place erosion around manhole.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938363,24936,SEECLICKFIX_89506,City of Antioch,2018-10-01T11:06:54-04:00,NaN,other,governance,governance_general,Other,NaN
938396,24969,SEECLICKFIX_89556,City of Antioch,2018-10-01T10:51:22-04:00,NaN,overgrown vegetation,environment,environment_overgrowth,Overgrown Vegetation,this is across the street from Lowe's original...
938486,25059,SEECLICKFIX_89684,City of Antioch,2018-10-01T10:15:56-04:00,NaN,trash / dumping,environment,environment_dumping,Trash dumped,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938364,24937,SEECLICKFIX_89507,Macon-Bibb County,2018-10-01T11:06:22-04:00,NaN,s-waste: garbage - cart replacement,environment,environment_garbage_collection,S-WASTE: Garbage - Cart Replacement,Customer needs a trash cart.
938394,24967,SEECLICKFIX_89552,Macon-Bibb County,2018-10-01T10:53:29-04:00,NaN,s-waste: debris,street,street_cleaning,S-WASTE: Debris,Bags have been out for two cycles of trash pic...
938491,25064,SEECLICKFIX_89691,Macon-Bibb County,2018-10-01T10:11:45-04:00,NaN,s-waste: debris,street,street_cleaning,S-WASTE: Debris,Large pile of branches and limbs by the side o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938367,24940,SEECLICKFIX_89512,Clayton County,2018-10-01T11:04:33-04:00,NaN,dead tree/limbs,environment,environment_overgrowth,Dead Tree/Limbs,This tree Dead for 6 Months... Many Green Vine...
940401,26974,SEECLICKFIX_92222,Clayton County,2018-09-29T17:51:53-04:00,NaN,dead animal pickup,environment,environment_dead_animal,Dead Animal Pickup,Have reported. Can't get county to come out. ...
940880,27453,SEECLICKFIX_92820,Clayton County,2018-09-29T12:26:03-04:00,NaN,overgrown grass/weeds,environment,environment_overgrowth,Overgrown Grass/Weeds,Also trash in front yard

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938368,24941,SEECLICKFIX_89515,WCRC Yard 2,2018-10-01T11:04:04-04:00,NaN,pothole,street,street_repair,Pothole,NaN
942132,28705,SEECLICKFIX_94376,WCRC Yard 2,2018-09-28T15:28:30-04:00,NaN,pothole,street,street_repair,Pothole,Resident called to report a pothole right on t...
942830,29403,SEECLICKFIX_95230,WCRC Yard 2,2018-09-28T11:52:00-04:00,NaN,pothole,street,street_repair,Pothole,manhole is sinking and there is deterioration ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938369,24942,SEECLICKFIX_89517,City of Memphis.,2018-10-01T11:03:50-04:00,NaN,other,governance,governance_general,Dead dog pickup,large white dog has been dead on interstate fo...
938372,24945,SEECLICKFIX_89520,City of Memphis.,2018-10-01T11:03:02-04:00,NaN,other,governance,governance_general,Other,Waste carts left in front of home & blocking s...
938405,24978,SEECLICKFIX_89569,City of Memphis.,2018-10-01T10:48:42-04:00,NaN,other,governance,governance_general,Potholes,Exit 3 Watkins. Several potholes before exit...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938377,24950,SEECLICKFIX_89529,Raleigh City Hall,2018-10-01T11:00:08-04:00,NaN,tree issue in right of way,environment,environment_overgrowth,Tree Issue in Right of Way,Tree is growing on city property and is growin...
938470,25043,SEECLICKFIX_89664,Raleigh City Hall,2018-10-01T10:20:36-04:00,NaN,dead animal collection,environment,environment_dead_animal,Dead Animal Collection,Dead Raccoon - After making a right on to West...
938502,25075,SEECLICKFIX_89706,Raleigh City Hall,2018-10-01T10:06:54-04:00,NaN,other,governance,governance_general,Other,Abandoned vehicle in no parking zone

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938380,24953,SEECLICKFIX_89533,Princeton - Request a Service,2018-10-01T10:59:16-04:00,NaN,clogged storm drain,street,street_drainage,Clogged storm drain,Dorann Ave Princeton NJ 08540
938385,24958,SEECLICKFIX_89540,Princeton - Request a Service,2018-10-01T10:56:52-04:00,NaN,high grass,environment,environment_overgrowth,High grass,yard is a mess and the grass and weeds are ove...
939664,26237,SEECLICKFIX_91313,Princeton - Request a Service,2018-09-30T12:37:40-04:00,NaN,other,governance,governance_general,Other,Loud music. It’s Sunday. Turn it down.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938382,24955,SEECLICKFIX_89535,City of Attleboro,2018-10-01T10:58:36-04:00,NaN,sewer / roadway drain,street,street_drainage,Sewer / Roadway Drain,IT WAS REPORTED THAT THE DRAIN IN FRONT OF 151...
938450,25023,SEECLICKFIX_89632,City of Attleboro,2018-10-01T10:29:02-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,This newly repaired fence was extended out to ...
938704,25277,SEECLICKFIX_90048,City of Attleboro,2018-10-01T08:03:30-04:00,NaN,pothole,street,street_repair,Pothole,large pothole getting bigger . needs to be fi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938383,24956,SEECLICKFIX_89536,City of Shawnee,2018-10-01T10:58:12-04:00,NaN,other,governance,governance_general,Other,Shoes hanging from power lines on the north si...
938578,25151,SEECLICKFIX_89836,City of Shawnee,2018-10-01T09:31:33-04:00,NaN,trees & tree limbs,environment,environment_overgrowth,Trees & Tree Limbs,Tree/bush hanging out into the street. at this...
938843,25416,SEECLICKFIX_90263,City of Shawnee,2018-09-30T23:08:13-04:00,NaN,street lights,street,street_lighting,Street Lights,Lights out at Widmer rd and 58th place in Lake...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938386,24959,SEECLICKFIX_89541,Animal Control - Jersey City,2018-10-01T10:56:26-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,injured squirrel on sidewalk looks like it's d...
941750,28323,SEECLICKFIX_93904,Animal Control - Jersey City,2018-09-28T17:34:19-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,NaN
943674,30247,SEECLICKFIX_96309,Animal Control - Jersey City,2018-09-28T00:29:26-04:00,NaN,animal issue other than attack,public_health,publichealth_animal,Cat feeding,Outside cats being feed. Over 2 dozen cats. My...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938388,24961,SEECLICKFIX_89543,City of Topeka,2018-10-01T10:56:00-04:00,NaN,other,governance,governance_general,Parking violation,Multiple vehicles parked on front yard and sid...
938483,25056,SEECLICKFIX_89679,City of Topeka,2018-10-01T10:17:37-04:00,NaN,pothole,street,street_repair,Pothole,The Gas Company cut holes out of the pavement ...
938601,25174,SEECLICKFIX_89867,City of Topeka,2018-10-01T09:21:27-04:00,NaN,property maintenance & code violations,planning,planning_general,Dumped tires,Several tires were dumped along Florence on bo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938397,24970,SEECLICKFIX_89558,Arlington Heights,2018-10-01T10:50:50-04:00,NaN,tree trim,environment,environment_overgrowth,Tree Trim,Good morning please let us know if you can tri...
944213,30786,SEECLICKFIX_96954,Arlington Heights,2018-09-27T18:13:35-04:00,NaN,dead animal pickup,environment,environment_dead_animal,Dead Animal Pickup,NaN
951380,37953,SEECLICKFIX_106112,Arlington Heights,2018-09-25T10:24:10-04:00,NaN,dead animal pickup,environment,environment_dead_animal,Dead Animal Pickup,Very large dead raccoon in median just south o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938404,24977,SEECLICKFIX_89568,Village of Oswego,2018-10-01T10:48:45-04:00,NaN,sidewalk/path,street,street_sidewalk,Sidewalk/Path,The side walk in my front yard appears to be s...
939123,25696,SEECLICKFIX_90640,Village of Oswego,2018-09-30T18:38:02-04:00,NaN,storm drains,street,street_drainage,Storm Drains,NaN
940046,26619,SEECLICKFIX_91804,Village of Oswego,2018-09-29T23:44:16-04:00,NaN,street light,street,street_lighting,Street Light,Street light out.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938420,24993,SEECLICKFIX_89591,Garden City,2018-10-01T10:41:24-04:00,NaN,tree maintenance,environment,environment_overgrowth,Tree Maintenance,village tree needs trimming very dangerous bra...
938528,25101,SEECLICKFIX_89747,Garden City,2018-10-01T09:57:49-04:00,NaN,parks/playgrounds,governance,governance_parks_and_rec,Parks/Playgrounds,NaN
939011,25584,SEECLICKFIX_90498,Garden City,2018-09-30T20:00:28-04:00,NaN,street light,street,street_lighting,Street Light,The street light on Cambridge and Middleton is...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938423,24996,SEECLICKFIX_89594,Austin 311,2018-10-01T10:40:47-04:00,NaN,other,governance,governance_general,Other,Clogged toilet between room 105
951090,37663,SEECLICKFIX_105724,Austin 311,2018-09-25T11:58:55-04:00,NaN,"grass/weeds over 12\ tall""",environment,environment_overgrowth,Tree Branches Blocking Street,On Meriden between 9th and 10th street the bus...
951284,37857,SEECLICKFIX_105992,Austin 311,2018-09-25T10:51:38-04:00,NaN,other,governance,governance_general,Restroom accident,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938425,24998,SEECLICKFIX_89597,Other,2018-10-01T10:40:29-04:00,NaN,tree trimming,environment,environment_overgrowth,Tree Trimming,The branches are hanging over and onto the str...
938481,25054,SEECLICKFIX_89677,Other,2018-10-01T10:17:49-04:00,NaN,overgrown grass,environment,environment_overgrowth,Overgrown Grass,This is a rental. The backyard grass is not cu...
938563,25136,SEECLICKFIX_89808,Other,2018-10-01T09:41:11-04:00,NaN,other concerns,governance,governance_general,Other Concerns,On Bluewater Blvd in the Seven Oaks neighborho...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938430,25003,SEECLICKFIX_89605,Gloucester MA,2018-10-01T10:38:01-04:00,NaN,private property issue,housing,housing_general,Private Property Issue,This house at 11 Forest St has been foreclosed...
938677,25250,SEECLICKFIX_90004,Gloucester MA,2018-10-01T08:28:54-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Police called to report a bunch of constructio...
939048,25621,SEECLICKFIX_90544,Gloucester MA,2018-09-30T19:30:40-04:00,NaN,brush,environment,environment_overgrowth,Brush,There is a city parking lot across from 27 War...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938439,25012,SEECLICKFIX_89616,Yerba Buena Community Benefit District,2018-10-01T10:33:33-04:00,NaN,cleaning,street,street_cleaning,Cleaning,NaN
941102,27675,SEECLICKFIX_93098,Yerba Buena Community Benefit District,2018-09-29T10:11:23-04:00,NaN,cleaning,street,street_cleaning,Cleaning,101 needs to be picked up by88
941103,27676,SEECLICKFIX_93100,Yerba Buena Community Benefit District,2018-09-29T10:09:06-04:00,NaN,graffiti on public property ybcbd,vandalism,vandalism_graffiti,Graffiti on Public Property YBCBD,Needs paint by88

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938448,25021,SEECLICKFIX_89630,City of Edinburg,2018-10-01T10:29:26-04:00,NaN,sewer backups,infrastructure,infrastructure_water,Sewer Backups,9/30/18 @ 1212 - Sewer backup. Reported to Al...
938464,25037,SEECLICKFIX_89653,City of Edinburg,2018-10-01T10:22:48-04:00,NaN,sewer backups,infrastructure,infrastructure_water,Sewer Backups,9/29/18 1800 - Sewer backup. Reported to Alex.
938566,25139,SEECLICKFIX_89811,City of Edinburg,2018-10-01T09:39:38-04:00,NaN,sewer backups,infrastructure,infrastructure_water,Sewer Backups,9/29/18 @ 813 - Customer called in reporting a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938454,25027,SEECLICKFIX_89637,Town of Braintree,2018-10-01T10:27:57-04:00,NaN,tree concern,environment,environment_overgrowth,Tree Concern,Tree has large hole in it totally hollow and ...
938985,25558,SEECLICKFIX_90468,Town of Braintree,2018-09-30T20:17:19-04:00,NaN,traffic lights,street,street_urgent_repair,Traffic Lights,Traffic Lights are only letting 3-4 cars go on...
940857,27430,SEECLICKFIX_92792,Town of Braintree,2018-09-29T12:41:44-04:00,NaN,street lights,street,street_lighting,Street Lights,Metal cover on light near crosswalk to French ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938458,25031,SEECLICKFIX_89645,City of Summit,2018-10-01T10:26:15-04:00,NaN,parks and public spaces,governance,governance_parks_and_rec,Parks and Public Spaces,Please complete job--chain link fencing betwee...
938468,25041,SEECLICKFIX_89657,City of Summit,2018-10-01T10:21:34-04:00,NaN,roads,street,street_general,Pothole,Deep narrow pothole in front of 18 Prospect St...
938509,25082,SEECLICKFIX_89719,City of Summit,2018-10-01T10:03:17-04:00,NaN,tree(s),environment,environment_overgrowth,Tree(s),Tree branches tangled with cable/telephone li...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938474,25047,SEECLICKFIX_89668,Code Enforcement,2018-10-01T10:19:58-04:00,NaN,overgrown grass/weeds/vegetation/trees,environment,environment_overgrowth,Overgrown Grass/Weeds/Vegetation/Trees,Residential
944818,31391,SEECLICKFIX_97699,Code Enforcement,2018-09-27T14:37:11-04:00,NaN,overgrown grass/weeds/vegetation/trees,environment,environment_overgrowth,Overgrown Grass/Weeds/Vegetation/Trees,NaN
944828,31401,SEECLICKFIX_97710,Code Enforcement,2018-09-27T14:34:13-04:00,NaN,overgrown grass/weeds/vegetation/trees,environment,environment_overgrowth,Overgrown Grass/Weeds/Vegetation/Trees,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938487,25060,SEECLICKFIX_89685,Agoura Hills,2018-10-01T10:15:22-04:00,NaN,graffiti - public property,vandalism,vandalism_graffiti,Graffiti - Public Property,On Saturday September 29 2018 witnessed graffi...
940287,26860,SEECLICKFIX_92086,Agoura Hills,2018-09-29T19:45:58-04:00,NaN,landscape - parks or streets,governance,governance_parks_and_rec,Landscape - Parks or Streets,OAK TREE DIED :( ON AGOURA ROAD SOUTH SIDE 50 ...
942308,28881,SEECLICKFIX_94593,Agoura Hills,2018-09-28T14:40:06-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Abandoned couch left on sidewalk in front of 2...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938488,25061,SEECLICKFIX_89686,Town of Wake Forest,2018-10-01T10:15:07-04:00,NaN,tree issue,environment,environment_overgrowth,Tree damaged from car crash,I filed a police report last evening around 6:...
938927,25500,SEECLICKFIX_90389,Town of Wake Forest,2018-09-30T21:00:58-04:00,NaN,area light out,environment,environment_general,Street lights out,2 street lights are out in Oakwood Estates. On...
942934,29507,SEECLICKFIX_95357,Town of Wake Forest,2018-09-28T11:25:11-04:00,NaN,area light out,environment,environment_general,Area Light Out,Street light out on stone chapel side.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938490,25063,SEECLICKFIX_89690,Public Property,2018-10-01T10:12:21-04:00,NaN,other public property issues,environment,environment_general,abandoned shopping cart,abandoned shopping cart
941992,28565,SEECLICKFIX_94211,Public Property,2018-09-28T16:00:31-04:00,NaN,other public property issues,environment,environment_general,Other Public Property Issues,Bird motor scooters. Can't walk down a sidewal...
942857,29430,SEECLICKFIX_95264,Public Property,2018-09-28T11:42:57-04:00,NaN,other public property issues,environment,environment_general,Other Public Property Issues,Collection of mud/debree from runoff from neig...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938495,25068,SEECLICKFIX_89696,East Point GA,2018-10-01T10:10:21-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,This has been a 'problem' property for more th...
938517,25090,SEECLICKFIX_89732,East Point GA,2018-10-01T10:01:07-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Shed on vacant lot broken into again by squatt...
938621,25194,SEECLICKFIX_89903,East Point GA,2018-10-01T09:09:38-04:00,NaN,water and sewer issue,infrastructure,infrastructure_water,Water and Sewer Issue,Water meter cavity full of water. And it looks...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938496,25069,SEECLICKFIX_89698,Zoning,2018-10-01T10:10:07-04:00,NaN,unregistered or inoperable vehicle,environment,environment_abandoned_vehicle,Unregistered or Inoperable Vehicle,Located on side of Magothy Beach Rd and Pine D...
938897,25470,SEECLICKFIX_90348,Zoning,2018-09-30T21:24:46-04:00,NaN,unregistered or inoperable vehicle,environment,environment_abandoned_vehicle,Unregistered or Inoperable Vehicle,VEHICLES ARE UNTAGGED AND UN OPERABLE. THE CAR...
940479,27052,SEECLICKFIX_92307,Zoning,2018-09-29T17:05:13-04:00,NaN,unregistered or inoperable vehicle,environment,environment_abandoned_vehicle,Unregistered or Inoperable Vehicle,Been reported twice. Resident is running a us...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938505,25078,SEECLICKFIX_89709,City of Bexley,2018-10-01T10:05:27-04:00,NaN,street / sidewalk,street,street_sidewalk,Street / Sidewalk,The bridge next to Tim Horton on Livingston Av...
941617,28190,SEECLICKFIX_93729,City of Bexley,2018-09-28T18:50:13-04:00,NaN,code enforcement,planning,planning_general,Street / Sidewalk,Bush blocking the sidewalk.
943596,30169,SEECLICKFIX_96215,City of Bexley,2018-09-28T06:20:53-04:00,NaN,traffic signal / streetlight,street,street_urgent_repair,Traffic Signal / Streetlight,S. Roosevelt just south of Broad on east side ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938508,25081,SEECLICKFIX_89715,Wilton CT,2018-10-01T10:04:06-04:00,NaN,mowing trimming overgrown vegetation (roads),environment,environment_overgrowth,Mowing Trimming Overgrown Vegetation (Roads),Mowing needed on Pipers Hill. Overgrowth in ro...
938912,25485,SEECLICKFIX_90367,Wilton CT,2018-09-30T21:15:02-04:00,NaN,pothole or pavement issue,street,street_repair,Pothole or Pavement Issue,Large cut out area in Wilton station parking l...
939243,25816,SEECLICKFIX_90798,Wilton CT,2018-09-30T17:00:56-04:00,NaN,pothole or pavement issue,street,street_repair,Pothole or Pavement Issue,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938518,25091,SEECLICKFIX_89733,Minneapolis 311,2018-10-01T10:01:03-04:00,NaN,traffic signal trouble,street,street_urgent_repair,Traffic Signal Trouble,All traffic lights out
938840,25413,SEECLICKFIX_90259,Minneapolis 311,2018-09-30T23:10:12-04:00,NaN,parking violation,public_order,publicorder_general,Parking Violation,in front of hydrant
938841,25414,SEECLICKFIX_90260,Minneapolis 311,2018-09-30T23:08:54-04:00,NaN,parking violation,public_order,publicorder_general,Parking Violation,Car appears to be abandoned. Has been parked ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938520,25093,SEECLICKFIX_89736,City of Ann Arbor,2018-10-01T10:00:36-04:00,NaN,streetlight repair,street,street_lighting,Streetlight repair,NaN
938568,25141,SEECLICKFIX_89814,City of Ann Arbor,2018-10-01T09:39:14-04:00,NaN,other issue,governance,governance_general,Other issue,Fiber optic cover broken in lawn
938602,25175,SEECLICKFIX_89871,City of Ann Arbor,2018-10-01T09:20:42-04:00,NaN,other issue,governance,governance_general,Trash and recycling bins in bike lane,Many recycling and trash bins are positioned i...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938533,25106,SEECLICKFIX_89754,Inspection and Permits,2018-10-01T09:56:40-04:00,NaN,building violation,planning,planning_unsafe_environment,Building Violation,The house was SUPPOSED to have a mother in law...
938564,25137,SEECLICKFIX_89809,Inspection and Permits,2018-10-01T09:41:07-04:00,NaN,building violation,planning,planning_unsafe_environment,Building Violation,building deck on back of house w/o permit
939077,25650,SEECLICKFIX_90585,Inspection and Permits,2018-09-30T19:05:16-04:00,NaN,building violation,planning,planning_unsafe_environment,Building Violation,Working on a stop work order on a Sunday to av...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938534,25107,SEECLICKFIX_89755,Missouri City,2018-10-01T09:55:58-04:00,NaN,vegetation,environment,environment_overgrowth,Vegetation,Neighbors have reported the back yard of this ...
938788,25361,SEECLICKFIX_90191,Missouri City,2018-10-01T00:44:40-04:00,NaN,trash screening,environment,environment_garbage_collection,Couch,There’s a couch left out in street.
942304,28877,SEECLICKFIX_94589,Missouri City,2018-09-28T14:40:21-04:00,NaN,trash screening,environment,environment_garbage_collection,Trash Screening,Trash can at curb since Monday 9/24

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938536,25109,SEECLICKFIX_89762,City of Beaumont,2018-10-01T09:54:16-04:00,NaN,code enforcement - litter/weeds/junk car/etc,environment,environment_overgrowth,Code Enforcement - Litter/Weeds/Junk Car/Etc,tree limbs over hanging into the roadway and c...
938551,25124,SEECLICKFIX_89785,City of Beaumont,2018-10-01T09:48:13-04:00,NaN,code enforcement - litter/weeds/junk car/etc,environment,environment_overgrowth,Code Enforcement - Litter/Weeds/Junk Car/Etc,junk SUV sitting in the driveway of 153 Orgain...
941330,27903,SEECLICKFIX_93384,City of Beaumont,2018-09-28T23:09:25-04:00,NaN,other,governance,governance_general,Other,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938540,25113,SEECLICKFIX_89768,City of Salem,2018-10-01T09:52:06-04:00,NaN,other - city issues,governance,governance_signage,Other - City Issues,Illegally parked boat trailer.
938873,25446,SEECLICKFIX_90316,City of Salem,2018-09-30T21:55:12-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,small dead animal in the middle of the street ...
938909,25482,SEECLICKFIX_90364,City of Salem,2018-09-30T21:18:18-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,There has been a long-standing pothole next to...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938542,25115,SEECLICKFIX_89772,The Burlington Electric,2018-10-01T09:51:19-04:00,NaN,street light out,street,street_lighting,Street Light Out,NaN
944872,31445,SEECLICKFIX_97760,The Burlington Electric,2018-09-27T14:21:19-04:00,NaN,street light out,street,street_lighting,Street Light Out,Pole 03461 on Edinborough at Appletree Park.
960079,46652,SEECLICKFIX_117108,The Burlington Electric,2018-09-20T16:44:49-04:00,NaN,street light too bright,street,street_lighting,Too many street lights,Why are there so many street lights in the Bir...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938557,25130,SEECLICKFIX_89800,Inkster MI,2018-10-01T09:43:55-04:00,NaN,other,governance,governance_general,Other,On the corner of Carlysle St. and Inkster Rd. ...
939394,25967,SEECLICKFIX_90985,Inkster MI,2018-09-30T15:22:47-04:00,NaN,other,governance,governance_general,city tree,city tree on property growing into owners pine...
939407,25980,SEECLICKFIX_90998,Inkster MI,2018-09-30T15:12:48-04:00,NaN,grass or noxious weeds,environment,environment_overgrowth,Grass or Noxious Weeds,grass not cut

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938570,25143,SEECLICKFIX_89817,Utah DOT,2018-10-01T09:37:43-04:00,NaN,animal carcass,environment,environment_dead_animal,Animal Carcass,Deer in shoulder
938926,25499,SEECLICKFIX_90388,Utah DOT,2018-09-30T21:02:08-04:00,NaN,traffic signals,street,street_urgent_repair,Traffic Signals,A lot of traffic lights on 12300 S are complet...
941304,27877,SEECLICKFIX_93355,Utah DOT,2018-09-28T23:49:41-04:00,NaN,traffic signals,street,street_urgent_repair,Traffic Signals,In the mornings these lights last about 2 seco...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938572,25145,SEECLICKFIX_89823,Town of Needham,2018-10-01T09:35:21-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,Bushes covering sidewalk
938606,25179,SEECLICKFIX_89877,Town of Needham,2018-10-01T09:17:50-04:00,NaN,street lights,street,street_lighting,Street Lights,Street light at this intersection is out.
938608,25181,SEECLICKFIX_89879,Town of Needham,2018-10-01T09:16:26-04:00,NaN,street lights,street,street_lighting,Street Lights,The street light on the lot line of the above ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938573,25146,SEECLICKFIX_89824,City of St. Albert,2018-10-01T09:35:16-04:00,NaN,street lights utility boxes,street,street_lighting,Traffic Lights,The lights are not working... the north lights...
939007,25580,SEECLICKFIX_90494,City of St. Albert,2018-09-30T20:03:09-04:00,NaN,trees,environment,environment_overgrowth,Trees,There’s a tree hanging over the road at #33 th...
939556,26129,SEECLICKFIX_91179,City of St. Albert,2018-09-30T13:40:27-04:00,NaN,trees,environment,environment_overgrowth,Trees,Tree branch is broken and hanging into yard. N...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938583,25156,SEECLICKFIX_89841,City of Pembroke Pines,2018-10-01T09:29:27-04:00,NaN,issues within a private property,public_order,publicorder_general,Issues within a Private Property,Pool is green inside open for mosquitoes and m...
938584,25157,SEECLICKFIX_89842,City of Pembroke Pines,2018-10-01T09:29:27-04:00,NaN,issues within a private property,public_order,publicorder_general,Issues within a Private Property,Pool is green inside open for mosquitoes and m...
939679,26252,SEECLICKFIX_91330,City of Pembroke Pines,2018-09-30T12:27:30-04:00,NaN,traffic lights (not street lights),street,street_urgent_repair,Traffic Lights (Not Street Lights),The traffic light at Pines Blvd. and Dykes Roa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938592,25165,SEECLICKFIX_89855,City of Portsmouth,2018-10-01T09:26:05-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Caller reports that a cat gym (scratching post...
938718,25291,SEECLICKFIX_90070,City of Portsmouth,2018-10-01T07:43:26-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Caller reports that there is a mattress at the...
939170,25743,SEECLICKFIX_90701,City of Portsmouth,2018-09-30T18:02:43-04:00,NaN,storm drains,street,street_drainage,Storm Drains,Open storm drain

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938611,25184,SEECLICKFIX_89882,Engineering,2018-10-01T09:15:36-04:00,NaN,sidewalk obstructions,street,street_sidewalk,Sidewalk Damage,Sidewalk impassable because of plantings
939883,26456,SEECLICKFIX_91595,Engineering,2018-09-30T09:49:40-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Damage,the handicap ramp is broken at the spring glen...
948361,34934,SEECLICKFIX_102225,Engineering,2018-09-26T11:54:36-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,The sidewalks are badly need of repair. Recen...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938614,25187,SEECLICKFIX_89886,Natick MA,2018-10-01T09:14:36-04:00,NaN,water or sanitary sewer inquiry,infrastructure,infrastructure_water,Water or Sanitary Sewer Inquiry,Please call me and let me know when the water ...
939736,26309,SEECLICKFIX_91405,Natick MA,2018-09-30T11:38:51-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,NaN
940852,27425,SEECLICKFIX_92783,Natick MA,2018-09-29T12:46:40-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938624,25197,SEECLICKFIX_89907,Corona,2018-10-01T09:08:27-04:00,NaN,street light issues (not traffic signals),street,street_lighting,Light out,Light pole on corner of olive and garretson is...
938676,25249,SEECLICKFIX_90000,Corona,2018-10-01T08:29:42-04:00,NaN,parkway maintenance (including landscape maint...,environment,environment_overgrowth,Parkway Maintenance (including Landscape Maint...,There are two city trees in front of my proper...
938775,25348,SEECLICKFIX_90171,Corona,2018-10-01T02:28:13-04:00,NaN,other,governance,governance_general,Other,There is more than one home on Hemlock Circle ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938625,25198,SEECLICKFIX_89908,Village of Flossmoor,2018-10-01T09:08:19-04:00,NaN,sewer,infrastructure,infrastructure_water,Sewer,Hydrant meter request
949170,35743,SEECLICKFIX_103304,Village of Flossmoor,2018-09-26T07:04:29-04:00,NaN,property maintenance,housing,housing_general,Property Maintenance,NaN
949171,35744,SEECLICKFIX_103305,Village of Flossmoor,2018-09-26T07:04:29-04:00,NaN,property maintenance,housing,housing_general,Property Maintenance,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938633,25206,SEECLICKFIX_89924,Trash/Recycling,2018-10-01T09:01:24-04:00,NaN,request a new recycling container,environment,environment_recycling,Request a new Recycling Container,New Development Pondview 8341 Kippis Rd Need...
938846,25419,SEECLICKFIX_90267,Trash/Recycling,2018-09-30T23:04:32-04:00,NaN,request a new recycling container,environment,environment_recycling,Need a larger recycling cart,We currently have an old and small square recy...
938885,25458,SEECLICKFIX_90330,Trash/Recycling,2018-09-30T21:40:29-04:00,NaN,request a new recycling container,environment,environment_recycling,18 Gallon Bin,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938635,25208,SEECLICKFIX_89927,Framingham MA,2018-10-01T09:00:25-04:00,NaN,other (non-police related issues),governance,governance_general,Other (Non-Police Related Issues),There is a strong smell of gas on the street.
938986,25559,SEECLICKFIX_90469,Framingham MA,2018-09-30T20:17:01-04:00,NaN,street/sidewalk repair,street,street_sidewalk,Street/Sidewalk Repair,Hello I'd like to draw attention to Parmenter...
941157,27730,SEECLICKFIX_93175,Framingham MA,2018-09-29T09:24:17-04:00,NaN,streetlights,street,street_lighting,Streetlights,Hi it looks like the street light is not worki...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938649,25222,SEECLICKFIX_89962,Jekyll Island GA (Authority Use Only),2018-10-01T08:48:38-04:00,NaN,other,governance,governance_general,broken mini fridge,our employee mini fridge started leaking oil
944757,31330,SEECLICKFIX_97620,Jekyll Island GA (Authority Use Only),2018-09-27T14:51:40-04:00,NaN,other,governance,governance_general,Other,Custodial cleaning needed for the changing roo...
945892,32465,SEECLICKFIX_99067,Jekyll Island GA (Authority Use Only),2018-09-27T09:40:31-04:00,NaN,other,governance,governance_general,Chair pickup,Will someone please come pick up the extra cha...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938650,25223,SEECLICKFIX_89964,Code Enforcement Area 6,2018-10-01T08:47:43-04:00,NaN,other,governance,governance_general,Other,The Rise at Northgate has not been able to pro...
943682,30255,SEECLICKFIX_96317,Code Enforcement Area 6,2018-09-28T00:25:08-04:00,NaN,other,governance,governance_general,Other,Clock does not work. “N” is also missing from ...
943761,30334,SEECLICKFIX_96406,Code Enforcement Area 6,2018-09-27T22:55:47-04:00,NaN,street lights,street,street_lighting,Street Lights,Street lamp on southwest corner of intersectio...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938661,25234,SEECLICKFIX_89979,City of Portage,2018-10-01T08:38:35-04:00,NaN,other,governance,governance_general,Rusty colored water,Nasty brown/rusty color water in some residenc...
939554,26127,SEECLICKFIX_91177,City of Portage,2018-09-30T13:40:51-04:00,NaN,tree inspection,environment,environment_general,Dead Trees,Multiple large dead trees in the back yard tha...
940450,27023,SEECLICKFIX_92275,City of Portage,2018-09-29T17:19:01-04:00,NaN,other,governance,governance_general,Other,Crosswalk signal does not operate.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938662,25235,SEECLICKFIX_89980,Traffic Signals - Chapel Hill & Carrboro,2018-10-01T08:37:29-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,When turning left from Seawell School onto Hom...
938688,25261,SEECLICKFIX_90017,Traffic Signals - Chapel Hill & Carrboro,2018-10-01T08:21:50-04:00,NaN,traffic signal,street,street_urgent_repair,Stuck crosswalk button,The crosswalk button on the Wallgreens corner ...
953031,39604,SEECLICKFIX_108282,Traffic Signals - Chapel Hill & Carrboro,2018-09-24T16:00:57-04:00,NaN,traffic signal,street,street_urgent_repair,Damaged Pushbutton,Caller reports a damaged pushbutton when cross...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938665,25238,SEECLICKFIX_89984,City of Sandy Springs,2018-10-01T08:36:48-04:00,NaN,code enforcement problem,planning,planning_general,Code Enforcement Problem,It appears that interior renovations are being...
939332,25905,SEECLICKFIX_90912,City of Sandy Springs,2018-09-30T16:01:52-04:00,NaN,roadway issues,street,street_general,Roadway Issues,There is a broken limb in the ground that hang...
939961,26534,SEECLICKFIX_91695,City of Sandy Springs,2018-09-30T08:04:26-04:00,NaN,code enforcement problem,planning,planning_general,Code Enforcement Problem,8:00 AM on Sunday morning. Extremely loud nois...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938671,25244,SEECLICKFIX_89992,Detroit Water & Sewerage Dept.,2018-10-01T08:32:50-04:00,NaN,blocked catch basin,street,street_drainage,Blocked Catch Basin,Water over half the street
938691,25264,SEECLICKFIX_90023,Detroit Water & Sewerage Dept.,2018-10-01T08:19:38-04:00,NaN,blocked catch basin,street,street_drainage,Blocked Catch Basin,Water bridging both sides of Pickford west of ...
938861,25434,SEECLICKFIX_90295,Detroit Water & Sewerage Dept.,2018-09-30T22:17:58-04:00,NaN,fire hydrant issue,fire,fire_equipment_broken,Fire Hydrant Issue,fire hydrant is broken. water running

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938695,25268,SEECLICKFIX_90032,Folly Beach SC,2018-10-01T08:15:40-04:00,NaN,beach walkovers accesses & paths,governance,governance_parks_and_rec,Beach Walkovers Accesses & Paths,NaN
978343,64916,SEECLICKFIX_139851,Folly Beach SC,2018-09-05T13:26:59-04:00,NaN,public properties (parks & facilities),governance,governance_parks_and_rec,Public Properties (Parks & Facilities),The water spigot at the back door of the Commu...
981788,68361,SEECLICKFIX_144075,Folly Beach SC,2018-08-31T17:35:00-04:00,NaN,parking violation,public_order,publicorder_general,Parking Violation,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938705,25278,SEECLICKFIX_90051,City of Pinellas Park,2018-10-01T08:01:58-04:00,NaN,overgrown property/brush piles,environment,environment_overgrowth,Overgrown lawn,House appears abandoned and the lawn is out co...
939009,25582,SEECLICKFIX_90496,City of Pinellas Park,2018-09-30T20:02:48-04:00,NaN,parks maintenance issues,governance,governance_parks_and_rec,Stinging Insects!,Wasp/hornet nest in gate on East end of main a...
939199,25772,SEECLICKFIX_90738,City of Pinellas Park,2018-09-30T17:41:48-04:00,NaN,other,governance,governance_general,Other,tree on city property branching out around ele...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938711,25284,SEECLICKFIX_90060,City of Alpharetta,2018-10-01T07:53:32-04:00,NaN,traffic issue,street,street_general,Traffic Issue,Two elementary school age children obstructing...
940598,27171,SEECLICKFIX_92445,City of Alpharetta,2018-09-29T15:57:50-04:00,NaN,pothole / road repair,street,street_repair,Pothole / Road Repair,There is 2 possible potholes are forming at th...
941316,27889,SEECLICKFIX_93369,City of Alpharetta,2018-09-28T23:22:43-04:00,NaN,street light outage,street,street_lighting,Street Light Outage,Street light #0027 is out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938712,25285,SEECLICKFIX_90061,City of Portland,2018-10-01T07:51:10-04:00,NaN,streets,street,street_general,Street Lights,Hi It appears that the Franlin Street lights ...
938740,25313,SEECLICKFIX_90112,City of Portland,2018-10-01T06:54:48-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,squirrel in planting bed
939102,25675,SEECLICKFIX_90614,City of Portland,2018-09-30T18:52:23-04:00,NaN,repair street light,street,street_lighting,Repair Street Light,The reporting of this particular street light ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938723,25296,SEECLICKFIX_90078,Roswell Georgia,2018-10-01T07:30:10-04:00,NaN,streets (overhead street lighting concern),street,street_lighting,Streets (Overhead Street Lighting Concern),Our light is no longer functioning. I presume ...
938863,25436,SEECLICKFIX_90298,Roswell Georgia,2018-09-30T22:15:16-04:00,NaN,streets (overhead street lighting concern),street,street_lighting,Streets (Overhead Street Lighting Concern),Street light out
941032,27605,SEECLICKFIX_93003,Roswell Georgia,2018-09-29T11:12:42-04:00,NaN,streets (overhead street lighting concern),street,street_lighting,Streets (Overhead Street Lighting Concern),Street lamp is completely burned out.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938730,25303,SEECLICKFIX_90087,City of Carbondale,2018-10-01T07:18:55-04:00,NaN,private property - weeds/grass,environment,environment_overgrowth,Private Property - Weeds/Grass,NaN
938906,25479,SEECLICKFIX_90360,City of Carbondale,2018-09-30T21:18:59-04:00,NaN,traffic signals,street,street_urgent_repair,Traffic Signals,Left Turn Signal at intersection allows only o...
941777,28350,SEECLICKFIX_93936,City of Carbondale,2018-09-28T17:22:29-04:00,NaN,private property - weeds/grass,environment,environment_overgrowth,Private Property - Weeds/Grass,Overgrowth

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938731,25304,SEECLICKFIX_90088,City of Manchester,2018-10-01T07:18:35-04:00,NaN,other,governance,governance_general,Other,Right travel lane North bound. Gravel has mig...
939060,25633,SEECLICKFIX_90562,City of Manchester,2018-09-30T19:16:21-04:00,NaN,pothole,street,street_repair,Pothole,North Street 50 feet east of Elm Street
939064,25637,SEECLICKFIX_90567,City of Manchester,2018-09-30T19:14:54-04:00,NaN,pothole,street,street_repair,Pothole,Carpenter Street 100 feet east of Union Street

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938735,25308,SEECLICKFIX_90096,Town of Whitman,2018-10-01T07:12:02-04:00,NaN,other,governance,governance_general,OTHER-SOUNDS OF STENTS UNLODGING EVERYWHERE,STENTS are popping out of the cricknation hear...
938738,25311,SEECLICKFIX_90104,Town of Whitman,2018-10-01T07:03:22-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,Rich no mo jo Rosen and pathetic excuse of a W...
938747,25320,SEECLICKFIX_90126,Town of Whitman,2018-10-01T06:28:54-04:00,NaN,other,governance,governance_general,ABUSIVE RENTERS NEXT DOOR threats made to all ...,218 pleasant first second and third floor extr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938760,25333,SEECLICKFIX_90145,City of Manchester - Parking,2018-10-01T05:59:37-04:00,NaN,parking enforcement,public_order,publicorder_general,Parking Enforcement,Car has been parked here for 3 days and has no...
943595,30168,SEECLICKFIX_96213,City of Manchester - Parking,2018-09-28T06:24:09-04:00,NaN,parking enforcement,public_order,publicorder_general,Parking Enforcement,Parking too close to a corner
945836,32409,SEECLICKFIX_98998,City of Manchester - Parking,2018-09-27T09:54:00-04:00,NaN,parking enforcement,public_order,publicorder_general,Parking Enforcement,Abandoned Vehicle that has been taking up stre...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938763,25336,SEECLICKFIX_90151,Gilbert AZ,2018-10-01T05:36:15-04:00,NaN,street light outage/malfunction,street,street_lighting,Street Light Outage/Malfunction,Intermittent streetlight
938772,25345,SEECLICKFIX_90167,Gilbert AZ,2018-10-01T02:52:34-04:00,NaN,street light outage/malfunction,street,street_lighting,Street Light Outage/Malfunction,light out residential area
938812,25385,SEECLICKFIX_90219,Gilbert AZ,2018-10-01T00:08:52-04:00,NaN,street light outage/malfunction,street,street_lighting,Street Light Outage/Malfunction,Street light is out.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938767,25340,SEECLICKFIX_90158,Sterling Heights MI,2018-10-01T04:39:26-04:00,NaN,general inquiry,governance,governance_general,Why is there no response to this?,Acknowledged 9/12 and then nothing. I'd like a...
938781,25354,SEECLICKFIX_90182,Sterling Heights MI,2018-10-01T01:23:07-04:00,NaN,general inquiry,governance,governance_general,General Inquiry,Trees on berm 19 Mike Rd north of Saal are int...
939107,25680,SEECLICKFIX_90621,Sterling Heights MI,2018-09-30T18:49:25-04:00,NaN,general inquiry,governance,governance_general,Goldberg Dr.,Are there plans in the future to resurface Gol...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938768,25341,SEECLICKFIX_90162,City of Bridgeport,2018-10-01T03:47:39-04:00,NaN,other,governance,governance_general,Dumping,I came back from vacation and found a couch on...
939517,26090,SEECLICKFIX_91135,City of Bridgeport,2018-09-30T14:03:28-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,This tree is tilting on it side. It has uproot...
939866,26439,SEECLICKFIX_91574,City of Bridgeport,2018-09-30T10:03:47-04:00,NaN,fire hydrant in need of repair,fire,fire_equipment_broken,Fire Hydrant in Need of Repair,Fire hydrant needs a face lift

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938779,25352,SEECLICKFIX_90177,Ferguson MO,2018-10-01T01:38:14-04:00,NaN,high weeds / tall grass,environment,environment_overgrowth,High Weeds / Tall Grass,Abandoned house wirh foot tall grass
938780,25353,SEECLICKFIX_90178,Ferguson MO,2018-10-01T01:36:16-04:00,NaN,high weeds / tall grass,environment,environment_overgrowth,High Weeds / Tall Grass,Well once again the supposed owner showed up a...
938817,25390,SEECLICKFIX_90224,Ferguson MO,2018-09-30T23:59:24-04:00,NaN,high weeds / tall grass,environment,environment_overgrowth,High Weeds / Tall Grass,the property that is on track side needs to be...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938783,25356,SEECLICKFIX_90184,Menlo Park,2018-10-01T01:22:11-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Old bike and other items illegally dumped on t...
939191,25764,SEECLICKFIX_90729,Menlo Park,2018-09-30T17:47:31-04:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Parks and Playgrounds,Bee swarm in tree. Nest may have been disturbed?
939567,26140,SEECLICKFIX_91194,Menlo Park,2018-09-30T13:32:48-04:00,NaN,other,governance,governance_general,Other,A house at 1107 Madera is building a structure...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938805,25378,SEECLICKFIX_90211,City of Folsom,2018-10-01T00:18:11-04:00,NaN,street light out/damaged,street,street_lighting,Street Light Out/Damaged,Street sign slipped down
938814,25387,SEECLICKFIX_90221,City of Folsom,2018-10-01T00:06:13-04:00,NaN,street light out/damaged,street,street_lighting,Street Light Out/Damaged,I have noticed several street lights out or fl...
938890,25463,SEECLICKFIX_90337,City of Folsom,2018-09-30T21:34:55-04:00,NaN,park maintenance,governance,governance_parks_and_rec,Park Maintenance,lots of trash in kemp park parking lot. there...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938810,25383,SEECLICKFIX_90216,City of Dixon,2018-10-01T00:12:15-04:00,NaN,street light,street,street_lighting,Street Light,These come on for a few minutes like they are ...
938813,25386,SEECLICKFIX_90220,City of Dixon,2018-10-01T00:07:54-04:00,NaN,street light,street,street_lighting,Street Light,The last number on the first one entered is il...
942028,28601,SEECLICKFIX_94254,City of Dixon,2018-09-28T15:51:38-04:00,NaN,street light,street,street_lighting,Street Light,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938830,25403,SEECLICKFIX_90245,Leland NC,2018-09-30T23:36:24-04:00,NaN,other,governance,governance_general,Other,water from tap is discolored comes out yellowish
938854,25427,SEECLICKFIX_90279,Leland NC,2018-09-30T22:48:15-04:00,NaN,other,governance,governance_general,Other,Yellow water coming out of all faucets. Brunsw...
938858,25431,SEECLICKFIX_90287,Leland NC,2018-09-30T22:33:25-04:00,NaN,other,governance,governance_general,Yellow water,Yellow tap water

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938832,25405,SEECLICKFIX_90250,City of Ypsilanti,2018-09-30T23:28:17-04:00,NaN,abandoned vehicles in street,environment,environment_abandoned_vehicle,Abandoned Vehicles in Street,Left on the street for over 5 days. Has multip...
944537,31110,SEECLICKFIX_97348,City of Ypsilanti,2018-09-27T16:12:41-04:00,NaN,fire code violations,fire,fire_code_violation,Fire Code Violations,Sidetracks' auxiliary parking has had yellow c...
954479,41052,SEECLICKFIX_110064,City of Ypsilanti,2018-09-24T10:36:47-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,On the west side of Rice street about 50-75 fe...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938835,25408,SEECLICKFIX_90254,City of Valdosta,2018-09-30T23:21:29-04:00,NaN,street light outages,street,street_lighting,Street Light Outages,The street light is out in front of my house a...
941024,27597,SEECLICKFIX_92993,City of Valdosta,2018-09-29T11:19:12-04:00,NaN,overgrown grass & weeds,environment,environment_overgrowth,Overgrown Grass & Weeds,Neighbors at 2309 S. Sherwood Dr. Valdosta Ga ...
942381,28954,SEECLICKFIX_94684,City of Valdosta,2018-09-28T14:13:10-04:00,NaN,abandoned or junk vehicles on public streets,environment,environment_abandoned_vehicle,Abandoned or Junk Vehicles on Public Streets,Two vehicles. One Mazda Miata and one Toyota f...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938836,25409,SEECLICKFIX_90255,Sanitation / Litter,2018-09-30T23:21:07-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Apparently either residents or landscapers are...
939496,26069,SEECLICKFIX_91108,Sanitation / Litter,2018-09-30T14:23:40-04:00,NaN,weeds,environment,environment_overgrowth,Weeds,The area with over grown Weeds is located on J...
944117,30690,SEECLICKFIX_96838,Sanitation / Litter,2018-09-27T19:00:17-04:00,NaN,weeds,environment,environment_overgrowth,Weeds,We need the clean team once again. The vacant...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938850,25423,SEECLICKFIX_90273,City of New Bedford,2018-09-30T22:56:21-04:00,NaN,potholes,street,street_repair,Potholes,There are multiple pot holes and uneven ground...
939801,26374,SEECLICKFIX_91497,City of New Bedford,2018-09-30T10:49:28-04:00,NaN,other city issue,governance,governance_general,Other City Issue,City owned property is located next to 32 Soci...
940815,27388,SEECLICKFIX_92731,City of New Bedford,2018-09-29T13:09:07-04:00,NaN,potholes,street,street_repair,Potholes,Large pot hole on front of ABC Disposal

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938853,25426,SEECLICKFIX_90278,City of Champaign,2018-09-30T22:49:52-04:00,NaN,repair to a streetlight needed,street,street_lighting,Repair to a streetlight needed,The streetlight at the SW corner of 4th and Wa...
940818,27391,SEECLICKFIX_92736,City of Champaign,2018-09-29T13:05:38-04:00,NaN,pothole repair,street,street_repair,Pothole repair,Pothole seems to be growing by the week
947556,34129,SEECLICKFIX_101170,City of Champaign,2018-09-26T15:13:15-04:00,NaN,pick up dead animal(s),environment,environment_dead_animal,Pick up dead animal(s),Dead animal in the parkway on the north side o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938883,25456,SEECLICKFIX_90328,City of Bainbridge Island,2018-09-30T21:42:15-04:00,NaN,other,governance,governance_general,construction material not secured,mega projext on madrona way ne has cinstructio...
939016,25589,SEECLICKFIX_90504,City of Bainbridge Island,2018-09-30T19:54:12-04:00,NaN,road issue,street,street_general,Road Drainage - Agate Street NE,When it rains storm water runs off Agate Stree...
941714,28287,SEECLICKFIX_93857,City of Bainbridge Island,2018-09-28T17:53:45-04:00,NaN,road issue,street,street_general,Road Issue,EAGLE HARBOR DRIVE BETWEEN TAYLOR AND ROCKAWAY...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938889,25462,SEECLICKFIX_90336,American Canyon CA,2018-09-30T21:35:15-04:00,NaN,litter,environment,environment_litter,Litter,garbage can under powerlines full for two week...
939560,26133,SEECLICKFIX_91185,American Canyon CA,2018-09-30T13:37:46-04:00,NaN,other,governance,governance_general,Other,Panties on fire hydrant corner of Ventana/Broa...
942216,28789,SEECLICKFIX_94483,American Canyon CA,2018-09-28T15:07:15-04:00,NaN,other,governance,governance_general,Other,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938941,25514,SEECLICKFIX_90411,Trees,2018-09-30T20:47:27-04:00,NaN,tree or stump maintainence request,environment,environment_overgrowth,Tree or Stump Maintainence Request,NaN
943462,30035,SEECLICKFIX_96032,Trees,2018-09-28T08:28:50-04:00,NaN,tree or stump maintainence request,environment,environment_overgrowth,Tree or Stump Maintainence Request,NaN
945268,31841,SEECLICKFIX_98256,Trees,2018-09-27T12:24:08-04:00,NaN,tree or stump maintainence request,environment,environment_overgrowth,Tree or Stump Maintainence Request,Stump needs removed people are tripping over it.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938947,25520,SEECLICKFIX_90419,Encinitas CA,2018-09-30T20:43:34-04:00,NaN,flooding,street,street_drainage,Flooding,Irrigation lines along Leucadia blvd are broke...
939691,26264,SEECLICKFIX_91346,Encinitas CA,2018-09-30T12:22:36-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN
939696,26269,SEECLICKFIX_91353,Encinitas CA,2018-09-30T12:14:21-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,Entire vault in sidewalk sinking. very dangero...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938958,25531,SEECLICKFIX_90436,City of Brockton MA,2018-09-30T20:33:12-04:00,NaN,pothole,street,street_repair,Pothole,hi so many on this street whole street needs t...
939965,26538,SEECLICKFIX_91701,City of Brockton MA,2018-09-30T07:49:01-04:00,NaN,pothole,street,street_repair,Pothole,Between 21 and 22 Simmons Ave there’s a huge p...
941215,27788,SEECLICKFIX_93243,City of Brockton MA,2018-09-29T07:05:12-04:00,NaN,pothole,street,street_repair,Pothole,Numerous large deep potholes. Someone is going...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938995,25568,SEECLICKFIX_90481,City of Tucson,2018-09-30T20:11:01-04:00,NaN,pothole,street,street_repair,Pothole,intersection of E Paseo Grande and Longfellow
939040,25613,SEECLICKFIX_90536,City of Tucson,2018-09-30T19:34:11-04:00,NaN,pothole,street,street_repair,Large Pothole,located on Boojum St approx 20 feet from Panta...
939672,26245,SEECLICKFIX_91321,City of Tucson,2018-09-30T12:32:44-04:00,NaN,pothole,street,street_repair,Pothole,1 pothole on Prudence north of Broadway

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
938996,25569,SEECLICKFIX_90482,City of Vista,2018-09-30T20:10:28-04:00,NaN,traffic sign problem,street,street_urgent_repair,Traffic Sign Problem,stop sign at corner of promontory and Landing ...
939376,25949,SEECLICKFIX_90963,City of Vista,2018-09-30T15:34:28-04:00,NaN,graffiti on private property,vandalism,vandalism_graffiti,Graffiti on Private Property,Gang related graffiti.
939892,26465,SEECLICKFIX_91608,City of Vista,2018-09-30T09:33:53-04:00,NaN,fire hazard,fire,fire_risks,Fire Hazard,On tenant in number 29 uses fire wood in her b...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939049,25622,SEECLICKFIX_90545,Newport RI,2018-09-30T19:30:25-04:00,NaN,tree or vegetation issue,environment,environment_overgrowth,Roadway or Sidewalk Issue,House has vegetation that takes over the sidew...
939050,25623,SEECLICKFIX_90546,Newport RI,2018-09-30T19:29:21-04:00,NaN,tree or vegetation issue,environment,environment_overgrowth,Roadway or Sidewalk Issue,House has vegetation that takes over the sidew...
944066,30639,SEECLICKFIX_96768,Newport RI,2018-09-27T19:32:50-04:00,NaN,roadway or sidewalk issue,street,street_sidewalk,Roadway or Sidewalk Issue,Delivery truck forces pedestrians into traffic...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939056,25629,SEECLICKFIX_90554,Mankato 311,2018-09-30T19:24:03-04:00,NaN,streetlight,street,street_lighting,Streetlight,Since the construction on Adams began this int...
939238,25811,SEECLICKFIX_90790,Mankato 311,2018-09-30T17:06:14-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,This sidewalk situation is on Carney Ave next ...
941860,28433,SEECLICKFIX_94049,Mankato 311,2018-09-28T16:46:20-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,cross walk huge uneven spot and it crosses to ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939072,25645,SEECLICKFIX_90580,City of New Westminster,2018-09-30T19:07:10-04:00,NaN,street light out,street,street_lighting,Street Light Out,NaN
939526,26099,SEECLICKFIX_91147,City of New Westminster,2018-09-30T13:58:35-04:00,NaN,street/sidewalk issues,street,street_sidewalk,Street/Sidewalk Issues,NaN
940120,26693,SEECLICKFIX_91892,City of New Westminster,2018-09-29T22:06:26-04:00,NaN,park maintenance,governance,governance_parks_and_rec,Park Maintenance,The rocks in the Queens park dog area along th...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939103,25676,SEECLICKFIX_90615,Harford County MD,2018-09-30T18:51:59-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,Trees planted by county in front of my home ar...
939382,25955,SEECLICKFIX_90971,Harford County MD,2018-09-30T15:27:50-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,NaN
940057,26630,SEECLICKFIX_91817,Harford County MD,2018-09-29T23:23:51-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939104,25677,SEECLICKFIX_90616,Blackfalds Alberta,2018-09-30T18:51:40-04:00,NaN,roads & sidewalks,street,street_sidewalk,Roads & Sidewalks,Our back alley is in desperate need of a grade...
951165,37738,SEECLICKFIX_105825,Blackfalds Alberta,2018-09-25T11:35:55-04:00,NaN,litter & dumping,environment,environment_litter,Litter & Dumping,On the SE of the school there is some broken g...
955114,41687,SEECLICKFIX_110894,Blackfalds Alberta,2018-09-24T01:43:55-04:00,NaN,roads & sidewalks,street,street_sidewalk,Roads & Sidewalks,With this back road (RR 272 and 40-0) it has m...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939120,25693,SEECLICKFIX_90635,Sammamish WA,2018-09-30T18:41:15-04:00,NaN,tree/vegetation issue in public right-of-way,environment,environment_overgrowth,Tree/Vegetation Issue in Public Right-of-Way,Along the narrow paved path connecting SE 14th...
939728,26301,SEECLICKFIX_91396,Sammamish WA,2018-09-30T11:46:01-04:00,NaN,tree/vegetation issue in public right-of-way,environment,environment_overgrowth,Tree/Vegetation Issue in Public Right-of-Way,NaN
940964,27537,SEECLICKFIX_92924,Sammamish WA,2018-09-29T11:35:39-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,The Side walk in front of our home is very uns...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939124,25697,SEECLICKFIX_90641,Planning & Zoning,2018-09-30T18:37:17-04:00,NaN,blight - illegal dumping,environment,environment_dumping,Blight - Illegal Dumping,Furniture and mattresses dumped on Treadwell b...
939125,25698,SEECLICKFIX_90642,Planning & Zoning,2018-09-30T18:37:17-04:00,NaN,blight - illegal dumping,environment,environment_dumping,Blight - Illegal Dumping,Furniture and mattresses dumped on Treadwell b...
939534,26107,SEECLICKFIX_91156,Planning & Zoning,2018-09-30T13:52:54-04:00,NaN,blight - graffiti,vandalism,vandalism_graffiti,Blight - Graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939207,25780,SEECLICKFIX_90756,City of Eden Prairie,2018-09-30T17:28:07-04:00,NaN,tree,environment,environment_overgrowth,Tree,On the path in Edenbrook Conservation Area rig...
939333,25906,SEECLICKFIX_90914,City of Eden Prairie,2018-09-30T16:00:24-04:00,NaN,animal,public_health,publichealth_animal,Animal,Dead animal remains on Dell Road
939878,26451,SEECLICKFIX_91587,City of Eden Prairie,2018-09-30T09:54:47-04:00,NaN,street light,street,street_lighting,Street Light,Two lights on this street missed the lightning...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939208,25781,SEECLICKFIX_90757,Landings Association,2018-09-30T17:27:57-04:00,NaN,tree maintenance request on common property,environment,environment_overgrowth,Tree Maintenance Request on Common Property,Please trim the live oak tree up so branches o...
947296,33869,SEECLICKFIX_100872,Landings Association,2018-09-26T16:05:07-04:00,NaN,tree maintenance request on common property,environment,environment_overgrowth,Tree Maintenance Request on Common Property,A large oak limb has fallen adjacent to the pa...
955313,41886,SEECLICKFIX_111128,Landings Association,2018-09-23T21:22:29-04:00,NaN,street light outage,street,street_lighting,Street Light Outage,On Tidewater at Anderson

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939233,25806,SEECLICKFIX_90785,Clovis NM,2018-09-30T17:11:25-04:00,NaN,weeds (cc),environment,environment_overgrowth,Weeds (CC),Yard and alley is tall and full of weeds
941787,28360,SEECLICKFIX_93951,Clovis NM,2018-09-28T17:16:41-04:00,NaN,weeds (cc),environment,environment_overgrowth,Weeds (CC),Extremely tall in ALLEY
941791,28364,SEECLICKFIX_93955,Clovis NM,2018-09-28T17:14:09-04:00,NaN,weeds (cc),environment,environment_overgrowth,Weeds (CC),Weeds

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939237,25810,SEECLICKFIX_90789,Edina MN,2018-09-30T17:07:11-04:00,NaN,other,governance,governance_general,Other,This trash area faces Cahill and the residents...
939450,26023,SEECLICKFIX_91055,Edina MN,2018-09-30T14:41:33-04:00,NaN,overgrown vegetation near street or sidewalk,environment,environment_overgrowth,Overgrown Vegetation Near Street or Sidewalk,There is overgrown weeds and thistles hanging ...
947048,33621,SEECLICKFIX_100550,Edina MN,2018-09-26T17:34:33-04:00,NaN,streets (pothole road salt or standing water),street,street_repair,Streets (Pothole Road Salt or Standing Water),The pothole is on the north side of Fuller abo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939280,25853,SEECLICKFIX_90850,Venice FL,2018-09-30T16:37:23-04:00,NaN,city property or city parks,governance,governance_parks_and_rec,City Property or City Parks,trees overgrown blocking road
939602,26175,SEECLICKFIX_91239,Venice FL,2018-09-30T13:14:35-04:00,NaN,city property or city parks,governance,governance_parks_and_rec,City Property or City Parks,Mundy Park users request that the basketball c...
939645,26218,SEECLICKFIX_91293,Venice FL,2018-09-30T12:48:13-04:00,NaN,city property or city parks,governance,governance_parks_and_rec,City Property or City Parks,Mandy Park bench has broken wood

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939293,25866,SEECLICKFIX_90863,City of Richmond,2018-09-30T16:30:26-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal dumping,There are a bunch of old tires stashed in the ...
940089,26662,SEECLICKFIX_91854,City of Richmond,2018-09-29T22:36:44-04:00,NaN,pothole,street,street_repair,Pothole,Large pothole on Strawberry St between Grace a...
940097,26670,SEECLICKFIX_91863,City of Richmond,2018-09-29T22:31:11-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal dumping,2 sofas were illegally dumped

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939304,25877,SEECLICKFIX_90875,Chelsea MA,2018-09-30T16:23:32-04:00,NaN,sidewalk conditions (other than snow & ice rem...,street,street_slippery,Sidewalk Conditions (other than Snow & Ice Rem...,Someone put plywood over all the tree spots on...
939345,25918,SEECLICKFIX_90928,Chelsea MA,2018-09-30T15:55:20-04:00,NaN,other,governance,governance_general,Other,Gate latch broken on children’s area at voke park
939544,26117,SEECLICKFIX_91166,Chelsea MA,2018-09-30T13:47:44-04:00,NaN,trash on public property,environment,environment_litter,Trash on Public Property,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939308,25881,SEECLICKFIX_90879,City of Westland,2018-09-30T16:20:53-04:00,NaN,forestry - tree removal,environment,environment_overgrowth,Forestry - Tree Removal,Sycamore on front easement/boulevard is leanin...
939705,26278,SEECLICKFIX_91364,City of Westland,2018-09-30T12:06:26-04:00,NaN,forestry - clean up trees or tree limbs,environment,environment_overgrowth,Forestry - Clean Up Trees or Tree Limbs,Neighor’s cottonwood tree dropped a huge limb ...
944714,31287,SEECLICKFIX_97560,City of Westland,2018-09-27T15:07:30-04:00,NaN,sanitation - missed recycling,environment,environment_recycling,Sanitation - Missed Recycling,Doesn't look like they picked up my recycling

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939325,25898,SEECLICKFIX_90901,Village of Algonquin,2018-09-30T16:08:03-04:00,NaN,tree dead/damaged/broken,environment,environment_overgrowth,Tree Dead/Damaged/Broken,tree limbs from storm put out by the curb
940340,26913,SEECLICKFIX_92149,Village of Algonquin,2018-09-29T18:51:29-04:00,NaN,sidewalk/bike path,street,street_sidewalk,Sidewalk/Bike Path,Sidewalk hazard
940628,27201,SEECLICKFIX_92484,Village of Algonquin,2018-09-29T15:41:35-04:00,NaN,sidewalk/bike path,street,street_sidewalk,Sidewalk/Bike Path,Love our new sidewalk! Unfortunately there is ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939349,25922,SEECLICKFIX_90933,Surfside FL,2018-09-30T15:51:32-04:00,NaN,other,governance,governance_general,Other,Lane directive sign is peeling making it risky...
946734,33307,SEECLICKFIX_100148,Surfside FL,2018-09-26T19:52:47-04:00,NaN,other,governance,governance_general,Garbage / debris in Indian creek,There is a traffic cone on the floor of Indian...
955542,42115,SEECLICKFIX_111396,Surfside FL,2018-09-23T18:48:17-04:00,NaN,drainage/flooding (pw),street,street_drainage,Drainage/Flooding (PW),Storm drain clogged with garbage. Not maintained

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939391,25964,SEECLICKFIX_90981,City of Emeryville,2018-09-30T15:23:28-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,There are 3 dead trees in the alley they have ...
940194,26767,SEECLICKFIX_91981,City of Emeryville,2018-09-29T20:43:27-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,The tree branches overgrew and hit and scratch...
940585,27158,SEECLICKFIX_92430,City of Emeryville,2018-09-29T16:02:31-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Burned out abandoned vehicle in parking lot. H...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939408,25981,SEECLICKFIX_91001,Town of Randolph,2018-09-30T15:11:16-04:00,NaN,housing - trash/overgrown lawn,environment,environment_overgrowth,Housing - Trash/Overgrown Lawn,Whole yard overgrown
940508,27081,SEECLICKFIX_92343,Town of Randolph,2018-09-29T16:49:42-04:00,NaN,other,governance,governance_general,Other,18 wheeler parked in residential zone. have wa...
941365,27938,SEECLICKFIX_93428,Town of Randolph,2018-09-28T22:24:28-04:00,NaN,street light,street,street_lighting,Street Light,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939446,26019,SEECLICKFIX_91051,Broken Arrow OK,2018-09-30T14:44:07-04:00,NaN,trees,environment,environment_overgrowth,Trees,At the entrance of Union Station on N Willow a...
940184,26757,SEECLICKFIX_91969,Broken Arrow OK,2018-09-29T20:50:42-04:00,NaN,parks request,governance,governance_parks_and_rec,Mosquito Spraying,There is a large wasp nest underneath the todd...
941447,28020,SEECLICKFIX_93521,Broken Arrow OK,2018-09-28T21:01:47-04:00,NaN,sewer or water utility issue,infrastructure,infrastructure_water,Sewer or Water Utility Issue,Hello! For the past few weeks our water has ta...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939464,26037,SEECLICKFIX_91072,Parks,2018-09-30T14:35:44-04:00,NaN,tree pruning,environment,environment_overgrowth,Tree Pruning,the tree in question is off the entrance of a ...
942001,28574,SEECLICKFIX_94222,Parks,2018-09-28T15:58:09-04:00,NaN,other (parks),governance,governance_parks_and_rec,Other (Parks),Vandalism - inappropriate Grafitti at the skat...
943255,29828,SEECLICKFIX_95759,Parks,2018-09-28T09:50:31-04:00,NaN,other (parks),governance,governance_parks_and_rec,Other (Parks),Leaves in Greenbrook green space by skate park...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939484,26057,SEECLICKFIX_91094,Public Works,2018-09-30T14:26:41-04:00,NaN,road & pothole repair,street,street_repair,Road & Pothole Repair,NaN
939792,26365,SEECLICKFIX_91480,Public Works,2018-09-30T10:58:39-04:00,NaN,street sweeping,street,street_cleaning,Street Sweeping,I know you are currently a bit overwhelmed but...
942310,28883,SEECLICKFIX_94595,Public Works,2018-09-28T14:39:24-04:00,NaN,pothole,street,street_repair,Pothole,By the brick

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939499,26072,SEECLICKFIX_91112,City of Tukwila,2018-09-30T14:22:16-04:00,NaN,overgrown brush/trees,environment,environment_overgrowth,Overgrown Brush/Trees,Overgrown tree resting on my fence. I've conta...
939512,26085,SEECLICKFIX_91128,City of Tukwila,2018-09-30T14:09:55-04:00,NaN,overgrown brush/trees,environment,environment_overgrowth,Overgrown Brush/Trees,There is a large cedar tree that is resting on...
939804,26377,SEECLICKFIX_91501,City of Tukwila,2018-09-30T10:45:44-04:00,NaN,other,governance,governance_general,Theft-auto prowling,During the night of Saturday September 29th a ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939564,26137,SEECLICKFIX_91191,Town of Swampscott,2018-09-30T13:34:30-04:00,NaN,other,governance,governance_general,Other,Utility line down
946460,33033,SEECLICKFIX_99821,Town of Swampscott,2018-09-26T22:48:39-04:00,NaN,pothole,street,street_repair,Pothole,NaN
946576,33149,SEECLICKFIX_99955,Town of Swampscott,2018-09-26T21:31:37-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939627,26200,SEECLICKFIX_91272,Edgewood KY,2018-09-30T12:58:04-04:00,NaN,other,governance,governance_general,Theft,Sometime over the past week or so someone stol...
953415,39988,SEECLICKFIX_108757,Edgewood KY,2018-09-24T14:38:08-04:00,NaN,sidewalk defect/issue,street,street_sidewalk,Sidewalk Defect/Issue,low hanging tree branches and overgrown shrubs...
964545,51118,SEECLICKFIX_122805,Edgewood KY,2018-09-18T08:50:49-04:00,NaN,other,governance,governance_general,Other,Rain water drainage backing into our garage

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939639,26212,SEECLICKFIX_91286,Town of Chelmsford,2018-09-30T12:52:19-04:00,NaN,pothole,street,street_repair,Pothole,There are numerous potholes at the end of Wave...
941936,28509,SEECLICKFIX_94139,Town of Chelmsford,2018-09-28T16:21:25-04:00,NaN,pothole,street,street_repair,Pothole,Small diameter but deep pothole in the eastbo...
946132,32705,SEECLICKFIX_99376,Town of Chelmsford,2018-09-27T08:26:25-04:00,NaN,tree service on public road ways,environment,environment_overgrowth,Tree Service on Public Road Ways,Heather Blake called (803) 414-5364. Tree nex...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939661,26234,SEECLICKFIX_91310,Streets Alleys Sidewalks and Traffic,2018-09-30T12:39:37-04:00,NaN,street pothole concern,street,street_repair,Street Pothole Concern,3 potholes needing patched
939999,26572,SEECLICKFIX_91746,Streets Alleys Sidewalks and Traffic,2018-09-30T03:13:37-04:00,NaN,street pothole concern,street,street_repair,Street Pothole Concern,The potholes need to be fixed asap
940002,26575,SEECLICKFIX_91749,Streets Alleys Sidewalks and Traffic,2018-09-30T03:06:18-04:00,NaN,street pothole concern,street,street_repair,Street Pothole Concern,Potholes need to be taking care of asap.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939676,26249,SEECLICKFIX_91326,Alachua County FL - Rural Service Area,2018-09-30T12:30:25-04:00,NaN,dead animal pickup,environment,environment_dead_animal,Dead deer on side of road,Not sure if address is correct (app did not al...
944209,30782,SEECLICKFIX_96949,Alachua County FL - Rural Service Area,2018-09-27T18:15:02-04:00,NaN,other,governance,governance_general,Other,I live across from Holden Pond Park. During Hu...
956198,42771,SEECLICKFIX_112213,Alachua County FL - Rural Service Area,2018-09-23T10:13:52-04:00,NaN,traffic sign,street,street_urgent_repair,Street Signage needed,May we get a slow down children at play sign f...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939752,26325,SEECLICKFIX_91430,City of Decatur,2018-09-30T11:23:39-04:00,NaN,city trees and park maintenance,governance,governance_parks_and_rec,City Trees and Park Maintenance,Very tall flowers at intersection of College A...
939833,26406,SEECLICKFIX_91534,City of Decatur,2018-09-30T10:29:02-04:00,NaN,street signs,governance,governance_signage,Street Signs,This temporary stop sign has been here for mon...
942955,29528,SEECLICKFIX_95385,City of Decatur,2018-09-28T11:19:47-04:00,NaN,city trees and park maintenance,governance,governance_parks_and_rec,City Trees and Park Maintenance,Big limb down blocking half on Mead

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939843,26416,SEECLICKFIX_91548,North Port FL,2018-09-30T10:17:25-04:00,NaN,tall grass - weeds,environment,environment_overgrowth,Tall Grass - Weeds,Tall grass and weeds
940790,27363,SEECLICKFIX_92699,North Port FL,2018-09-29T13:28:09-04:00,NaN,other,governance,governance_general,Other,Installed new windows without permit
942254,28827,SEECLICKFIX_94527,North Port FL,2018-09-28T14:55:39-04:00,NaN,other,governance,governance_general,Broke Down Vehicle In Backyard,There is a broke down white car in the backyar...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939900,26473,SEECLICKFIX_91619,Reading MA,2018-09-30T09:21:20-04:00,NaN,other,governance,governance_general,Rat,Dead rat
939967,26540,SEECLICKFIX_91705,Reading MA,2018-09-30T07:44:08-04:00,NaN,parks/fields,governance,governance_parks_and_rec,Parks/Fields,Looks like someone either left the lock box op...
941604,28177,SEECLICKFIX_93711,Reading MA,2018-09-28T18:57:41-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,There is a large hole in the tree lawn between...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939943,26516,SEECLICKFIX_91671,City of Cooper City,2018-09-30T08:36:35-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,Black olive tree has a whitefly infestation. D...
950675,37248,SEECLICKFIX_105203,City of Cooper City,2018-09-25T13:43:35-04:00,NaN,abandoned properties,environment,environment_abandoned_site,Abandoned Properties,The property is a mess. It looks like no one l...
966149,52722,SEECLICKFIX_124831,City of Cooper City,2018-09-17T08:52:46-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,8950 SW 52 place- Have been calling you guys f...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939947,26520,SEECLICKFIX_91678,Trash,2018-09-30T08:31:28-04:00,NaN,recycling collection,environment,environment_recycling,Removal of can,My husband and I have called in our blue recyc...
941252,27825,SEECLICKFIX_93294,Trash,2018-09-29T02:58:14-04:00,NaN,recycling collection,environment,environment_recycling,Recycling Collection,NaN
941369,27942,SEECLICKFIX_93433,Trash,2018-09-28T22:21:23-04:00,NaN,recycling collection,environment,environment_recycling,Recycling Collection,recycling not picked up in 3 weeks

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939949,26522,SEECLICKFIX_91680,City Service Area,2018-09-30T08:30:21-04:00,NaN,tree/limbs,environment,environment_overgrowth,Tree/Limbs,Stump growth blocking mailbox accessibility
940772,27345,SEECLICKFIX_92673,City Service Area,2018-09-29T13:42:03-04:00,NaN,tree/limbs,environment,environment_overgrowth,Tree/Limbs,Large limb blocking EB access to NW 11th Ave
940985,27558,SEECLICKFIX_92948,City Service Area,2018-09-29T11:30:03-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,See pictures

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939954,26527,SEECLICKFIX_91687,City of Saline,2018-09-30T08:22:19-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,Mud/dirt on the road. Inadequate soil erosion ...
945144,31717,SEECLICKFIX_98096,City of Saline,2018-09-27T13:00:22-04:00,NaN,other,governance,governance_general,Other,Tree in front of my house is dropping unusual ...
957798,44371,SEECLICKFIX_114231,City of Saline,2018-09-21T20:23:26-04:00,NaN,other,governance,governance_general,Other,Wood pile has been in the front yard for month...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939968,26541,SEECLICKFIX_91706,City of Marlborough,2018-09-30T07:43:07-04:00,NaN,other,governance,governance_general,Other,Malfunctioning Car Alarm--Horn starts honking ...
941202,27775,SEECLICKFIX_93230,City of Marlborough,2018-09-29T07:40:35-04:00,NaN,street light,street,street_lighting,Street Light,There is a street light out at the intersectio...
947995,34568,SEECLICKFIX_101734,City of Marlborough,2018-09-26T13:39:07-04:00,NaN,pothole,street,street_repair,Pothole,Potholes all along Route 20 entering and exiti...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939982,26555,SEECLICKFIX_91725,Eufaula AL,2018-09-30T06:46:00-04:00,NaN,other,governance,governance_general,Water Pressure,There are no leaks at 288 Gammage road. Inside...
943100,29673,SEECLICKFIX_95558,Eufaula AL,2018-09-28T10:42:23-04:00,NaN,other,governance,governance_general,Other,grate on storm drain bent and dangerous report...
945490,32063,SEECLICKFIX_98546,Eufaula AL,2018-09-27T11:24:33-04:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,Paint can spilled and needs picked up

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
939991,26564,SEECLICKFIX_91737,Town of Amherst MA,2018-09-30T05:00:39-04:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,Greetings and felicitations. As of tonight th...
942188,28761,SEECLICKFIX_94449,Town of Amherst MA,2018-09-28T15:14:53-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,Clogged storm drain between 599 and 613 S Plea...
943452,30025,SEECLICKFIX_96020,Town of Amherst MA,2018-09-28T08:33:46-04:00,NaN,pothole,street,street_repair,Pothole,Received call there is a sink hole forming eas...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940032,26605,SEECLICKFIX_91787,City of Manassas VA,2018-09-30T00:04:58-04:00,NaN,tree limb on or near power line,environment,environment_overgrowth,Tree Limb on or near power line,NaN
940033,26606,SEECLICKFIX_91789,City of Manassas VA,2018-09-30T00:03:05-04:00,NaN,streetlight outage,street,street_lighting,Streetlight Outage,NaN
940035,26608,SEECLICKFIX_91792,City of Manassas VA,2018-09-30T00:00:45-04:00,NaN,overgrown grass,environment,environment_overgrowth,Overgrown Grass,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940054,26627,SEECLICKFIX_91814,WCRC Yard 5,2018-09-29T23:33:06-04:00,NaN,pothole,street,street_repair,Pothole,Several potholes over a span of 300 ft
953622,40195,SEECLICKFIX_109021,WCRC Yard 5,2018-09-24T13:46:49-04:00,NaN,pothole,street,street_repair,Pothole,Asphalt area of Judd road before dirt area
969586,56159,SEECLICKFIX_129127,WCRC Yard 5,2018-09-13T12:51:18-04:00,NaN,flooding,street,street_drainage,Flooding,Caller stated that the pavement in front of hi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940214,26787,SEECLICKFIX_92004,Residential,2018-09-29T20:33:02-04:00,NaN,trash- extra black container,environment,environment_garbage_collection,Other,I need 2 extra recycling containers. The Gilbe...
940823,27396,SEECLICKFIX_92741,Residential,2018-09-29T13:03:51-04:00,NaN,trash & recycling (we missed your pickup),environment,environment_garbage_collection,Trash & Recycling (We missed your pickup),NaN
940826,27399,SEECLICKFIX_92744,Residential,2018-09-29T13:03:51-04:00,NaN,trash & recycling (we missed your pickup),environment,environment_garbage_collection,Trash & Recycling (We missed your pickup),NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940274,26847,SEECLICKFIX_92071,Fitchburg MA,2018-09-29T19:55:47-04:00,NaN,pothole,street,street_repair,Pothole,Between flashing yellow light and United Way o...
941550,28123,SEECLICKFIX_93641,Fitchburg MA,2018-09-28T19:34:47-04:00,NaN,streetlights,street,street_lighting,Streetlights,Three or four street lights are out on this st...
941551,28124,SEECLICKFIX_93642,Fitchburg MA,2018-09-28T19:34:47-04:00,NaN,streetlights,street,street_lighting,Streetlights,Three or four street lights are out on this st...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940281,26854,SEECLICKFIX_92078,Public Property and Parks,2018-09-29T19:52:31-04:00,NaN,other,governance,governance_general,furniture deposited,abandoned furniture by roadside
940284,26857,SEECLICKFIX_92082,Public Property and Parks,2018-09-29T19:48:25-04:00,NaN,other,governance,governance_general,junk dumped,dumped junk
940493,27066,SEECLICKFIX_92324,Public Property and Parks,2018-09-29T16:57:20-04:00,NaN,other,governance,governance_general,Other,Abandoned truck bed liner blocking part of str...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940308,26881,SEECLICKFIX_92108,City of Hartsville,2018-09-29T19:26:35-04:00,NaN,stormwater drainage problem (catch basin ditch),street,street_drainage,Stormwater drainage problem (catch basin ditch),The storm drains on Kenwood are not draining a...
951021,37594,SEECLICKFIX_105638,City of Hartsville,2018-09-25T12:17:19-04:00,NaN,road or sidewalk repair problem (pothole debri...,street,street_repair,Road or sidewalk repair problem (pothole debri...,On the corner of Rose Ave and 11th Street nex...
956265,42838,SEECLICKFIX_112301,City of Hartsville,2018-09-23T08:26:40-04:00,NaN,road or sidewalk repair problem (pothole debri...,street,street_repair,Road or sidewalk repair problem (pothole debri...,Hole in street with hollow area beneath

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940312,26885,SEECLICKFIX_92112,City of Mount Pleasant,2018-09-29T19:25:38-04:00,NaN,out streetlight,street,street_lighting,Out Streetlight,Street light at Washington and Michigan is out...
940313,26886,SEECLICKFIX_92113,City of Mount Pleasant,2018-09-29T19:25:38-04:00,NaN,out streetlight,street,street_lighting,Out Streetlight,Street light out at intersection
941087,27660,SEECLICKFIX_93079,City of Mount Pleasant,2018-09-29T10:20:58-04:00,NaN,accumulation of trash on lawn,environment,environment_dumping,Accumulation of Trash on Lawn,There is a fair amount of trash towards the ba...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940325,26898,SEECLICKFIX_92129,Richfield,2018-09-29T19:05:13-04:00,NaN,street maintenance,street,street_general,Street Maintenance,On 77th street between Portland Ave and Chicag...
941290,27863,SEECLICKFIX_93338,Richfield,2018-09-29T00:16:27-04:00,NaN,other,governance,governance_general,street light out,Path light in the park behind City Hall is wor...
943519,30092,SEECLICKFIX_96107,Richfield,2018-09-28T08:03:36-04:00,NaN,street maintenance,street,street_general,Street light,I had reported this light out and I think the ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940363,26936,SEECLICKFIX_92180,Walnut Creek,2018-09-29T18:25:16-04:00,NaN,tree/landscaping encroachment,environment,environment_overgrowth,Tree/Landscaping Encroachment,This tree hangs low over the path from San Mig...
940364,26937,SEECLICKFIX_92181,Walnut Creek,2018-09-29T18:25:06-04:00,NaN,tree/landscaping encroachment,environment,environment_overgrowth,Tree/Landscaping Encroachment,This tree hangs low over the path from San Mig...
956975,43548,SEECLICKFIX_113159,Walnut Creek,2018-09-22T14:40:02-04:00,NaN,potholes and sidewalks,street,street_repair,rudgear walking signal,the cross walk signal across rudgear doesnt sh...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940378,26951,SEECLICKFIX_92196,Littleton CO,2018-09-29T18:06:55-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on green control box at this location.
940386,26959,SEECLICKFIX_92204,Littleton CO,2018-09-29T18:01:13-04:00,NaN,traffic signs,street,street_urgent_repair,Traffic Signs,Crosswalk sign on W Alamo Ave @ Elks Club is a...
940402,26975,SEECLICKFIX_92223,Littleton CO,2018-09-29T17:51:08-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on control box at the north side of t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940523,27096,SEECLICKFIX_92361,Report It! NFO,2018-09-29T16:40:08-04:00,NaN,illegal dumping in road,environment,environment_dumping,Dumped Couch,Couch dump in Street on 9th Ave at Bay Road Re...
944713,31286,SEECLICKFIX_97559,Report It! NFO,2018-09-27T15:07:40-04:00,NaN,graffiti in nfo,vandalism,vandalism_graffiti,Graffiti in NFO,Graffiti
944717,31290,SEECLICKFIX_97563,Report It! NFO,2018-09-27T15:07:03-04:00,NaN,illegal dumping on sidewalk (outside the roadway),environment,environment_dumping,Illegal Dumping on Sidewalk (outside the roadway),NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940541,27114,SEECLICKFIX_92382,Recreation and Parks,2018-09-29T16:29:52-04:00,NaN,regional/community parks,governance,governance_parks_and_rec,Regional/Community Parks,Thank u for fixing the fence. Three posts hav...
946322,32895,SEECLICKFIX_99658,Recreation and Parks,2018-09-27T05:11:32-04:00,NaN,regional/community parks,governance,governance_parks_and_rec,Broken Glass,I reported broken glass on the trail twice las...
952140,38713,SEECLICKFIX_107110,Recreation and Parks,2018-09-24T22:17:00-04:00,NaN,regional/community parks,governance,governance_parks_and_rec,Regional/Community Parks,my young son was reading the sign discussing a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940551,27124,SEECLICKFIX_92392,Town of North Attleboro,2018-09-29T16:24:16-04:00,NaN,pothole,street,street_repair,Pot hole,The entire length of the dirt Charles Road has...
945563,32136,SEECLICKFIX_98638,Town of North Attleboro,2018-09-27T11:05:40-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,The bricks in front of the library are pulled ...
953272,39845,SEECLICKFIX_108569,Town of North Attleboro,2018-09-24T15:15:54-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,Fence along the E'ly side of East St between B...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940681,27254,SEECLICKFIX_92551,Humboldt IA,2018-09-29T15:05:51-04:00,NaN,other,governance,governance_general,Other,Tall Weeds Cockoburrs weeds at Mid American Si...
947473,34046,SEECLICKFIX_101079,Humboldt IA,2018-09-26T15:26:18-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,camper in yard
948553,35126,SEECLICKFIX_102469,Humboldt IA,2018-09-26T11:08:46-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940721,27294,SEECLICKFIX_92607,Ecorse MI,2018-09-29T14:30:44-04:00,NaN,other,governance,governance_general,Other,Missing brick
944951,31524,SEECLICKFIX_97858,Ecorse MI,2018-09-27T13:57:44-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,testing
947264,33837,SEECLICKFIX_100827,Ecorse MI,2018-09-26T16:21:49-04:00,NaN,water - street flooding,street,street_drainage,Water - Street Flooding,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940829,27402,SEECLICKFIX_92747,San Mateo County,2018-09-29T13:02:39-04:00,NaN,illegal dumping on private property,environment,environment_dumping,Illegal Dumping on Private Property,dead bird at front door (to the right on groun...
975920,62493,SEECLICKFIX_136837,San Mateo County,2018-09-07T14:18:38-04:00,NaN,illegal dumping on sidewalk (outside the roadway),environment,environment_dumping,Illegal Dumping on Sidewalk (outside the roadway),Someone has illegally dumped two shelving unit...
985714,72287,SEECLICKFIX_148934,San Mateo County,2018-08-27T14:43:15-04:00,NaN,illegal dumping in road,environment,environment_dumping,dumping into stream/creek,a basket ball net with stand and base has been...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
940927,27500,SEECLICKFIX_92876,Town Service Request,2018-09-29T11:49:56-04:00,NaN,tree down or vegetation in right of way,environment,environment_overgrowth,Tree down or Vegetation in right of way,Vegetation on the inside of the 128 curve at t...
973399,59972,SEECLICKFIX_133763,Town Service Request,2018-09-10T14:02:58-04:00,NaN,tree down or vegetation in right of way,environment,environment_overgrowth,Tree down or Vegetation in right of way,Tree hanging over the road about 30 feet off t...
980385,66958,SEECLICKFIX_142329,Town Service Request,2018-09-03T16:20:13-04:00,NaN,illegal dumping trash or dead animal,environment,environment_dumping,Illegal Dumping Trash or Dead Animal,Panhandlers are leaving garbage and needles at...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941089,27662,SEECLICKFIX_93082,City of Edinburg Water & Sewer Department,2018-09-29T10:20:06-04:00,NaN,water and sewer locates,infrastructure,infrastructure_water,Water and Sewer Locates,Mark water and sewer 250’ radius of intersecti...
941896,28469,SEECLICKFIX_94091,City of Edinburg Water & Sewer Department,2018-09-28T16:34:22-04:00,NaN,sewer backups and lift station maintenance (in...,infrastructure,infrastructure_water,Sewer Backups and Lift Station Maintenance (IN...,Water coming out either from the manhole or ne...
941958,28531,SEECLICKFIX_94168,City of Edinburg Water & Sewer Department,2018-09-28T16:11:41-04:00,NaN,water and sewer locates,infrastructure,infrastructure_water,Water and Sewer Locates,area is 4168 ft from intersection going west ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941118,27691,SEECLICKFIX_93123,Indian Rocks Beach FL,2018-09-29T09:58:40-04:00,NaN,parks requests,governance,governance_parks_and_rec,Broken/Missing Exercise Equipment,The padding/cushion on the back extension equi...
974673,61246,SEECLICKFIX_135355,Indian Rocks Beach FL,2018-09-09T07:40:33-04:00,NaN,other,governance,governance_general,Other,Curious to know who is supposed to maintain is...
975285,61858,SEECLICKFIX_136076,Indian Rocks Beach FL,2018-09-08T09:29:53-04:00,NaN,flooding,street,street_drainage,Flooding,Corner of Maxwell and Harbor Dr S floods with ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941128,27701,SEECLICKFIX_93135,Henry County GA,2018-09-29T09:49:44-04:00,NaN,cracked sidewalks,street,street_sidewalk,Uneven and cracked sidewalk,There is a visible trip hazard from an uneven ...
941630,28203,SEECLICKFIX_93747,Henry County GA,2018-09-28T18:39:03-04:00,NaN,pothole,street,street_repair,Road deterioration,Northtowne Cove needs road patching or complet...
942081,28654,SEECLICKFIX_94319,Henry County GA,2018-09-28T15:37:34-04:00,NaN,trees (fallen tree hanging tree limbs etc.),environment,environment_overgrowth,Trees (fallen tree hanging tree limbs etc.),Dead tree has fallen on ROW and partially into...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941155,27728,SEECLICKFIX_93173,City of Burlington,2018-09-29T09:25:34-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Broken glass,Smashed bottles on the ground near the water f...
941161,27734,SEECLICKFIX_93181,City of Burlington,2018-09-29T09:20:23-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Permanent marker has been used to write hate s...
943006,29579,SEECLICKFIX_95447,City of Burlington,2018-09-28T11:06:36-04:00,NaN,traffic sign maintenance,street,street_urgent_repair,Traffic Sign Maintenance,black paint defacing signage

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941353,27926,SEECLICKFIX_93415,Belleair FL,2018-09-28T22:35:37-04:00,NaN,sidewalk repair requests,street,street_sidewalk,Sidewalk Repair Requests,several cracks along Pensacola and in front al...
950006,36579,SEECLICKFIX_104354,Belleair FL,2018-09-25T16:52:58-04:00,NaN,street light requests,street,street_lighting,Street Light Requests,The street light at the intersection of Pine R...
951791,38364,SEECLICKFIX_106655,Belleair FL,2018-09-25T08:25:54-04:00,NaN,streets and drainage requests,street,street_drainage,Streets and Drainage Requests,Storm drains number 436437 and 437 contain con...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941374,27947,SEECLICKFIX_93438,Atlantic IA,2018-09-28T22:14:59-04:00,NaN,water & electrical issues,infrastructure,infrastructure_water,Water & Electrical Issues,NaN
943624,30197,SEECLICKFIX_96252,Atlantic IA,2018-09-28T03:14:54-04:00,NaN,pothole,street,street_repair,Pothole,It is the alley between 8th and 9th St and pal...
945359,31932,SEECLICKFIX_98374,Atlantic IA,2018-09-27T11:54:55-04:00,NaN,parking violation,public_order,publicorder_general,Parking Violation,camper isn't parked according to city codes

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941406,27979,SEECLICKFIX_93476,City of Danville,2018-09-28T21:37:49-04:00,NaN,other,governance,governance_general,Other,Please perform a health and welfare check at 5...
944891,31464,SEECLICKFIX_97783,City of Danville,2018-09-27T14:14:30-04:00,NaN,other,governance,governance_general,Trees down,Apple Bottom Creek has trees down and blocking...
944912,31485,SEECLICKFIX_97806,City of Danville,2018-09-27T14:08:30-04:00,NaN,other,governance,governance_general,Street is breaking apart over creek,Arnett Blvd - Apple Bottom Creek has been sp...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941489,28062,SEECLICKFIX_93570,City of Grande Prairie,2018-09-28T20:32:18-04:00,NaN,pothole,street,street_repair,Pothole,There is a hole in the field behind the alleyw...
941789,28362,SEECLICKFIX_93953,City of Grande Prairie,2018-09-28T17:15:53-04:00,NaN,sidewalk/curb problem,street,street_sidewalk,Sidewalk/Curb Problem,trees are hanging over sidewalk creating a hazard
947888,34461,SEECLICKFIX_101596,City of Grande Prairie,2018-09-26T14:10:55-04:00,NaN,pothole,street,street_repair,Potholes,116ave WB at Lakeland Dr. The right lane has ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941692,28265,SEECLICKFIX_93831,Revelstoke BC,2018-09-28T18:01:13-04:00,NaN,street light,street,street_lighting,Street Light,NaN
942644,29217,SEECLICKFIX_94998,Revelstoke BC,2018-09-28T12:50:41-04:00,NaN,tree,environment,environment_overgrowth,Tree,Large spruce tree touching power lines and roo...
944258,30831,SEECLICKFIX_97014,Revelstoke BC,2018-09-27T17:47:58-04:00,NaN,tree,environment,environment_overgrowth,Dead tree,Dead tree next to our garage. I believe it’s o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941718,28291,SEECLICKFIX_93861,Private Property and Code Enforcement,2018-09-28T17:52:36-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Car has not moved for two weeks and Is parked ...
942679,29252,SEECLICKFIX_95044,Private Property and Code Enforcement,2018-09-28T12:39:28-04:00,NaN,other,governance,governance_general,Noise conplaint,For two weeks there has been workers behind my...
944684,31257,SEECLICKFIX_97521,Private Property and Code Enforcement,2018-09-27T15:19:31-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,tabs expired may 2018 neighbor says it hasn't ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941761,28334,SEECLICKFIX_93917,Smithville TX,2018-09-28T17:29:51-04:00,NaN,trim overgrown brush or tree,environment,environment_overgrowth,Trim Overgrown Brush or Tree,Customer following up on a work order to cut d...
947225,33798,SEECLICKFIX_100774,Smithville TX,2018-09-26T16:40:10-04:00,NaN,other,governance,governance_general,Other,Boat & Covered Trailer parked on City street f...
948298,34871,SEECLICKFIX_102143,Smithville TX,2018-09-26T12:13:15-04:00,NaN,other,governance,governance_general,Fallen tree,Tree has broken and fallen over

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941785,28358,SEECLICKFIX_93947,Crockett TX,2018-09-28T17:19:03-04:00,NaN,sewer issue,infrastructure,infrastructure_water,Sewer Issue,CPD backed up again.
944147,30720,SEECLICKFIX_96874,Crockett TX,2018-09-27T18:43:59-04:00,NaN,sewer issue,infrastructure,infrastructure_water,Sewer Issue,Men's bathroom
947662,34235,SEECLICKFIX_101289,Crockett TX,2018-09-26T14:59:52-04:00,NaN,overgrowth,environment,environment_overgrowth,Overgrowth,Ditches at Oak and Ralph Bunch need to be mowed.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941790,28363,SEECLICKFIX_93954,Windsor CT,2018-09-28T17:15:06-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk repair,This is a repeat. On the edge of the sidewalk...
962263,48836,SEECLICKFIX_119836,Windsor CT,2018-09-19T14:45:12-04:00,NaN,other,governance,governance_general,Zoning Violation-Illegal car sales,Resident has up to 5 cars in his driveway at a...
971034,57607,SEECLICKFIX_130893,Windsor CT,2018-09-12T11:46:39-04:00,NaN,streetlight,street,street_lighting,Streetlight,Light has not turned off it's on 24 hrs. only ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941866,28439,SEECLICKFIX_94057,Crockett TX (Water Only),2018-09-28T16:45:10-04:00,NaN,water leak,infrastructure,infrastructure_water,Water Leak,Caller reported a big leak
947046,33619,SEECLICKFIX_100548,Crockett TX (Water Only),2018-09-26T17:35:15-04:00,NaN,water leak,infrastructure,infrastructure_water,Water Leak,Leak at meter.
948226,34799,SEECLICKFIX_102053,Crockett TX (Water Only),2018-09-26T12:32:27-04:00,NaN,water line locate,infrastructure,infrastructure_water,Water Line Locate,Both sides of the street before Friday 9/28/2018.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941898,28471,SEECLICKFIX_94093,WCRC Yard 6,2018-09-28T16:34:09-04:00,NaN,pothole,street,street_repair,Pothole,Large hole on southeast corner
942458,29031,SEECLICKFIX_94774,WCRC Yard 6,2018-09-28T13:50:30-04:00,NaN,pothole,street,street_repair,Pothole,NaN
942954,29527,SEECLICKFIX_95382,WCRC Yard 6,2018-09-28T11:20:04-04:00,NaN,flooding,street,street_drainage,Flooding,Caller is reporting a large washout in front o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941904,28477,SEECLICKFIX_94101,Chatham County Public Works,2018-09-28T16:32:11-04:00,NaN,pothole,street,street_repair,Pothole,Pothole in roadway of Carlisle Lane between 11...
943800,30373,SEECLICKFIX_96451,Chatham County Public Works,2018-09-27T22:21:51-04:00,NaN,pothole,street,street_repair,Pothole,Our street requests that the center of the cul...
950213,36786,SEECLICKFIX_104618,Chatham County Public Works,2018-09-25T15:43:08-04:00,NaN,pothole,street,street_repair,Pothole,Large rough bump of concrete

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941929,28502,SEECLICKFIX_94130,City of Johns Creek,2018-09-28T16:24:31-04:00,NaN,dead animal - on public property,environment,environment_dead_animal,Dead Animal - on Public Property,NaN
963466,50039,SEECLICKFIX_121373,City of Johns Creek,2018-09-18T18:25:40-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,Traffic light on the Dynamo & Dojo side is not...
969172,55745,SEECLICKFIX_128611,City of Johns Creek,2018-09-13T17:36:45-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,The left turn signal going from state bridge r...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941952,28525,SEECLICKFIX_94162,City of SeaTac,2018-09-28T16:14:15-04:00,NaN,overgrown bush | tree,environment,environment_overgrowth,Overgrown Bush | Tree,The sidewalk is very overgrown and is hazardou...
943338,29911,SEECLICKFIX_95862,City of SeaTac,2018-09-28T09:27:53-04:00,NaN,other,governance,governance_general,Other,Landlord has not maintained their property. I...
951915,38488,SEECLICKFIX_106848,City of SeaTac,2018-09-25T05:37:19-04:00,NaN,other,governance,governance_general,Illegal parking causing a hazard,There are signs in military rd not to park as ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941959,28532,SEECLICKFIX_94169,Town of Summerville SC,2018-09-28T16:11:38-04:00,NaN,other,governance,governance_general,Feather Sign,NaN
947305,33878,SEECLICKFIX_100882,Town of Summerville SC,2018-09-26T16:01:52-04:00,NaN,other,governance,governance_general,Tow truck flat tire,A tow truck has been parked on the road in Sco...
950045,36618,SEECLICKFIX_104405,Town of Summerville SC,2018-09-25T16:35:12-04:00,NaN,garbage/recycling,environment,environment_garbage_collection,Garbage/Recycling,bulk waste removal never showed up schedule fo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941970,28543,SEECLICKFIX_94184,Dalton GA Public Works,2018-09-28T16:04:48-04:00,NaN,street sign down / bent,street,street_urgent_repair,Street Sign Down / Bent,Truck driver has knocked down 2 NO DUMPING Sig...
942042,28615,SEECLICKFIX_94272,Dalton GA Public Works,2018-09-28T15:47:10-04:00,NaN,brush/rubbish - pickup request,environment,environment_overgrowth,Brush/Rubbish - Pickup Request,Leaves and grass to be picked up. SOUTH
943199,29772,SEECLICKFIX_95691,Dalton GA Public Works,2018-09-28T10:10:13-04:00,NaN,brush/rubbish - pickup request,environment,environment_overgrowth,Brush/Rubbish - Pickup Request,A couple of garbage bags have washed down in f...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
941994,28567,SEECLICKFIX_94214,City of Oshkosh,2018-09-28T15:59:46-04:00,NaN,tree pruning,environment,environment_overgrowth,Tree Pruning,Tall bushes (over 48\ high) at the corner of M...
945098,31671,SEECLICKFIX_98039,City of Oshkosh,2018-09-27T13:15:27-04:00,NaN,"tall weeds/grass (8\ or taller)""",environment,environment_overgrowth,"Tall Weeds/Grass (8\ or taller)""",this report was closed without cutting weeds ...
947931,34504,SEECLICKFIX_101659,City of Oshkosh,2018-09-26T13:56:13-04:00,NaN,property maintenance,housing,housing_general,Property Maintenance,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942049,28622,SEECLICKFIX_94281,Maui County,2018-09-28T15:44:58-04:00,NaN,abandoned vehicles,environment,environment_abandoned_vehicle,Abandoned Vehicles,blue Ford Escape Hawaii license plate MMP 822 ...
951924,38497,SEECLICKFIX_106857,Maui County,2018-09-25T03:52:42-04:00,NaN,street light,street,street_lighting,Street Light,I called Maui Electric trouble line a few week...
956294,42867,SEECLICKFIX_112336,Maui County,2018-09-23T06:59:23-04:00,NaN,abandoned vehicles,environment,environment_abandoned_vehicle,Abandoned Vehicles,Location: Kahului. Abandoned vehicle located i...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942106,28679,SEECLICKFIX_94348,South Milwaukee WI,2018-09-28T15:32:21-04:00,NaN,tall weeds or grass,environment,environment_overgrowth,Tall Weeds or Grass,There is an extremely large city tree located ...
945972,32545,SEECLICKFIX_99164,South Milwaukee WI,2018-09-27T09:20:47-04:00,NaN,tall weeds or grass,environment,environment_overgrowth,Tall Weeds or Grass,Various potential violations on the property a...
949565,36138,SEECLICKFIX_103781,South Milwaukee WI,2018-09-25T20:04:52-04:00,NaN,tall weeds or grass,environment,environment_overgrowth,Tall Weeds or Grass,Property overrun by tall weeds. Raccoons skun...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942207,28780,SEECLICKFIX_94474,Town of Herndon,2018-09-28T15:09:20-04:00,NaN,streets,street,street_general,Drainage Issue on West Side of Spruce Strreet,The bottom of drainage ditch to the Elden St s...
943741,30314,SEECLICKFIX_96384,Town of Herndon,2018-09-27T23:11:43-04:00,NaN,streetlight is out,street,street_lighting,Streetlight is Out,The street light in front of my house is out f...
945464,32037,SEECLICKFIX_98513,Town of Herndon,2018-09-27T11:29:35-04:00,NaN,streetlight is out,street,street_lighting,Streetlight is Out,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942311,28884,SEECLICKFIX_94596,Town of Scarborough,2018-09-28T14:39:18-04:00,NaN,street lights,street,street_lighting,STREET LIGHTS,Light is out flickers on once in a while. We w...
943945,30518,SEECLICKFIX_96617,Town of Scarborough,2018-09-27T20:50:52-04:00,NaN,street lights,street,street_lighting,STREET LIGHTS,Street light is out at 4 Ridgeway Road AND 8 R...
955721,42294,SEECLICKFIX_111623,Town of Scarborough,2018-09-23T16:26:59-04:00,NaN,road issue/ defect (potholes),street,street_repair,ROAD ISSUE/ DEFECT (POTHOLES),Where Federal comes on to Eastern there are tw...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942313,28886,SEECLICKFIX_94598,St. Charles,2018-09-28T14:38:37-04:00,NaN,tall grass/overgrown weeds,environment,environment_overgrowth,Tall Grass/Overgrown Weeds,NaN
947209,33782,SEECLICKFIX_100751,St. Charles,2018-09-26T16:44:35-04:00,NaN,pothole,street,street_repair,Pothole,This pot hole is getting deeper and deeper as ...
955813,42386,SEECLICKFIX_111731,St. Charles,2018-09-23T15:22:30-04:00,NaN,dangerous sidewalks,street,street_sidewalk,Dangerous Sidewalks,Sidewalk is a trip hazard to all the walkers i...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942374,28947,SEECLICKFIX_94677,Ames IA,2018-09-28T14:15:07-04:00,NaN,other,governance,governance_general,Other,ADA I have no way to leave my home and go abou...
945579,32152,SEECLICKFIX_98658,Ames IA,2018-09-27T11:01:46-04:00,NaN,other,governance,governance_general,Other,Low hanging tree limbs over sidewalk
946503,33076,SEECLICKFIX_99869,Ames IA,2018-09-26T22:18:17-04:00,NaN,other,governance,governance_general,Other,The street lamp on 3914 West Lawn Drive does n...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942403,28976,SEECLICKFIX_94708,City of Foster City,2018-09-28T14:08:26-04:00,NaN,other,governance,governance_general,Stray cat,There has been a cat walking around our house ...
945007,31580,SEECLICKFIX_97931,City of Foster City,2018-09-27T13:42:27-04:00,NaN,parks,governance,governance_parks_and_rec,Water (Leak),Broken sprinkler head in park behind our house...
946352,32925,SEECLICKFIX_99692,City of Foster City,2018-09-27T02:45:12-04:00,NaN,parks,governance,governance_parks_and_rec,Water (Leak),Shad Park sprinkler head is broken. Water spew...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942426,28999,SEECLICKFIX_94734,Code Enforcement Area 3,2018-09-28T13:59:03-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,even side of San Pedro welsh to pedernales nee...
945872,32445,SEECLICKFIX_99045,Code Enforcement Area 3,2018-09-27T09:44:29-04:00,NaN,accumulation of trash,environment,environment_dumping,Accumulation of Trash,Caller reported that beer cans have been all o...
950241,36814,SEECLICKFIX_104654,Code Enforcement Area 3,2018-09-25T15:35:48-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,Caller reported high grass here.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942456,29029,SEECLICKFIX_94771,City of Covington,2018-09-28T13:51:56-04:00,NaN,pothole,street,street_repair,Pothole,Gravel falling away. It started closer to the ...
944451,31024,SEECLICKFIX_97246,City of Covington,2018-09-27T16:44:09-04:00,NaN,pothole,street,street_repair,Pothole,Street edge disintegrating
947968,34541,SEECLICKFIX_101704,City of Covington,2018-09-26T13:44:19-04:00,NaN,other,governance,governance_general,test report,Testing

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942631,29204,SEECLICKFIX_94984,Town of Grafton,2018-09-28T12:54:47-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,Light out
967424,53997,SEECLICKFIX_126494,Town of Grafton,2018-09-15T11:34:35-04:00,NaN,other,governance,governance_general,Other,Broken fence at river view near boat launch
973926,60499,SEECLICKFIX_134423,Town of Grafton,2018-09-10T08:35:28-04:00,NaN,pothole,street,street_repair,Pothole,DRAINAGE CATCH BASIN COVER AND MAN HOLE COVER ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942693,29266,SEECLICKFIX_95063,Grand Bahama Port Authority,2018-09-28T12:34:00-04:00,NaN,litter,environment,environment_litter,Litter,NaN
942701,29274,SEECLICKFIX_95072,Grand Bahama Port Authority,2018-09-28T12:32:06-04:00,NaN,litter,environment,environment_litter,Litter,NaN
942709,29282,SEECLICKFIX_95081,Grand Bahama Port Authority,2018-09-28T12:30:23-04:00,NaN,litter,environment,environment_litter,Litter,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942834,29407,SEECLICKFIX_95235,City of Wisconsin Rapids,2018-09-28T11:51:23-04:00,NaN,garbage / recycling,environment,environment_garbage_collection,Recycle,Non recycles inside recycle bin. Clothes shoe ...
942839,29412,SEECLICKFIX_95243,City of Wisconsin Rapids,2018-09-28T11:49:44-04:00,NaN,garbage / recycling,environment,environment_garbage_collection,Recycle,Recycle bin too full lid not closed and non re...
942846,29419,SEECLICKFIX_95250,City of Wisconsin Rapids,2018-09-28T11:47:49-04:00,NaN,garbage / recycling,environment,environment_garbage_collection,Recycle,Recycle bin too full lid not closed

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942969,29542,SEECLICKFIX_95399,Hoover AL,2018-09-28T11:16:36-04:00,NaN,abandoned vehicles/ junk cars,environment,environment_abandoned_vehicle,Abandoned Vehicles/ Junk Cars,Pick up truck in yard not moved in 5 years.
943410,29983,SEECLICKFIX_95962,Hoover AL,2018-09-28T08:55:19-04:00,NaN,street sidewalk & curb issues,street,street_sidewalk,Street Sidewalk & Curb Issues,Pothole on Clearview Road (southbound).
946605,33178,SEECLICKFIX_99996,Hoover AL,2018-09-26T21:11:58-04:00,NaN,abandoned vehicles/ junk cars,environment,environment_abandoned_vehicle,Abandoned Vehicles/ Junk Cars,Nissan Sentra with expired tag at intersection...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942970,29543,SEECLICKFIX_95402,City of Gallup,2018-09-28T11:15:56-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti covering road signs in front of drain...
946462,33035,SEECLICKFIX_99823,City of Gallup,2018-09-26T22:48:17-04:00,NaN,street light problem,street,street_lighting,Street Light Problem,Street light is out. Please replace with newer...
946482,33055,SEECLICKFIX_99845,City of Gallup,2018-09-26T22:36:59-04:00,NaN,street light problem,street,street_lighting,Street Light Problem,Street LIGHT is out.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
942986,29559,SEECLICKFIX_95421,Town of Watertown,2018-09-28T11:12:48-04:00,NaN,street signs,governance,governance_signage,Traffic Light Issue,The light at Galen/Pearl St. is timed poorly a...
948848,35421,SEECLICKFIX_102868,Town of Watertown,2018-09-26T09:38:22-04:00,NaN,street signs,governance,governance_signage,Traffic Light Issue,The traffic light on Galen St. at the Jefferso...
956146,42719,SEECLICKFIX_112150,Town of Watertown,2018-09-23T11:05:41-04:00,NaN,street signs,governance,governance_signage,New Traffic Pattern Warning,Would be nice to have a giant neon sign furthe...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943008,29581,SEECLICKFIX_95450,City of Fort Pierce,2018-09-28T11:06:15-04:00,NaN,tall grass / overgrown landscaping,environment,environment_overgrowth,Tall Grass / Overgrown Landscaping,Complaint from neighbor. Says landscaping is ...
943235,29808,SEECLICKFIX_95733,City of Fort Pierce,2018-09-28T09:58:04-04:00,NaN,trees,environment,environment_overgrowth,Dead Palm Tree,There is a dead palm tree along S. Ocean Dr. j...
945092,31665,SEECLICKFIX_98033,City of Fort Pierce,2018-09-27T13:16:37-04:00,NaN,animal control,public_health,publichealth_animal,Animal Control,Unattended chained dog heat index 103+ degrees

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943097,29670,SEECLICKFIX_95554,Code Enforcement Area 1,2018-09-28T10:42:48-04:00,NaN,other,governance,governance_general,Other,Crazy amount of fire ants!
943267,29840,SEECLICKFIX_95775,Code Enforcement Area 1,2018-09-28T09:45:06-04:00,NaN,other,governance,governance_general,Other,Is it a violation to have a porttapotty on pri...
944253,30826,SEECLICKFIX_97008,Code Enforcement Area 1,2018-09-27T17:50:49-04:00,NaN,accumulation of trash,environment,environment_dumping,Accumulation of Trash,Trash in plain view next to the house. I rep...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943339,29912,SEECLICKFIX_95864,Town of Wakefield,2018-09-28T09:27:26-04:00,NaN,pothole,street,street_repair,Pothole,Asphalt has broken up on side of the road in f...
952852,39425,SEECLICKFIX_108053,Town of Wakefield,2018-09-24T16:49:25-04:00,NaN,pothole,street,street_repair,Broken road,The Summer rain has washed away the stones on ...
963354,49927,SEECLICKFIX_121225,Town of Wakefield,2018-09-18T20:11:36-04:00,NaN,pothole,street,street_repair,Pothole,There are several potholes at the intersection...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943536,30109,SEECLICKFIX_96126,Richland County,2018-09-28T07:53:01-04:00,NaN,pothole,street,street_repair,Pothole,Third report. Still not fixed.
946217,32790,SEECLICKFIX_99501,Richland County,2018-09-27T07:46:11-04:00,NaN,pothole,street,street_repair,Pothole,I reported this yesterday and other potholes w...
949110,35683,SEECLICKFIX_103226,Richland County,2018-09-26T07:46:25-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943566,30139,SEECLICKFIX_96166,Water / Sewer,2018-09-28T07:24:04-04:00,NaN,flooding,street,street_drainage,Flooding,this is our second attempt for your assistance...
1002769,89342,SEECLICKFIX_170556,Water / Sewer,2018-08-01T15:02:12-04:00,NaN,sewer backup,infrastructure,infrastructure_water,Sewer Backup,backing into home since 7/28
1010639,97212,SEECLICKFIX_180702,Water / Sewer,2018-07-18T17:33:17-04:00,NaN,flooding,street,street_drainage,Flooding,Single sewer grate constantly blocked and floo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943656,30229,SEECLICKFIX_96289,Mason City,2018-09-28T01:00:40-04:00,NaN,overgrown grass/weed,environment,environment_overgrowth,City Property NOT 319 5th St SW ( Great Clips ),city property NOT 319 5th St SW ( Great Clips ...
943664,30237,SEECLICKFIX_96299,Mason City,2018-09-28T00:46:28-04:00,NaN,overgrown grass/weed,environment,environment_overgrowth,Overgrown Grass/Weed,NaN
951502,38075,SEECLICKFIX_106268,Mason City,2018-09-25T09:46:54-04:00,NaN,non-dwelling rvs (boats trailers snowmobiles o...,street,street_slippery,Trailer and vehicles over parked in the street,White car truck and race car trailer are parke...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943680,30253,SEECLICKFIX_96315,Mosinee WI,2018-09-28T00:25:38-04:00,NaN,other,governance,governance_general,Other,Large oil stain from unfinished road resurfaci...
951574,38147,SEECLICKFIX_106374,Mosinee WI,2018-09-25T09:24:55-04:00,NaN,other,governance,governance_general,Other,pick up truck parked behind garage on jack sta...
955894,42467,SEECLICKFIX_111845,Mosinee WI,2018-09-23T14:15:29-04:00,NaN,high grass/weeds,environment,environment_overgrowth,High Grass/Weeds,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
943976,30549,SEECLICKFIX_96658,Allegan MI,2018-09-27T20:27:16-04:00,NaN,other,governance,governance_general,Incomplete fence required by zoning board,We have been patiently waiting for our fence t...
961983,48556,SEECLICKFIX_119495,Allegan MI,2018-09-19T16:53:15-04:00,NaN,other,governance,governance_general,Other,It is at 311 Delano St. a large No Trespassing...
962540,49113,SEECLICKFIX_120180,Allegan MI,2018-09-19T12:26:57-04:00,NaN,leaf and brush pickup,environment,environment_overgrowth,Leaf and Brush Pickup,they are dumping their leaves and brush in the...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944001,30574,SEECLICKFIX_96685,El Reno OK,2018-09-27T20:11:21-04:00,NaN,tall weeds & grass,environment,environment_overgrowth,Tall Weeds & Grass,NaN
944025,30598,SEECLICKFIX_96715,El Reno OK,2018-09-27T19:57:19-04:00,NaN,tall weeds & grass,environment,environment_overgrowth,Tall Weeds & Grass,NaN
944031,30604,SEECLICKFIX_96722,El Reno OK,2018-09-27T19:52:58-04:00,NaN,tall weeds & grass,environment,environment_overgrowth,Tall Weeds & Grass,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944039,30612,SEECLICKFIX_96732,Grand Terrace CA,2018-09-27T19:49:44-04:00,NaN,ce-overgrown weeds,environment,environment_overgrowth,CE-Overgrown Weeds,Overgrown Weeds still there. If you put a noti...
961308,47881,SEECLICKFIX_118639,Grand Terrace CA,2018-09-20T08:47:53-04:00,NaN,ce-overgrown weeds,environment,environment_overgrowth,CE-Overgrown Weeds,Overgrown trees and weeds on Mirado between Ta...
961315,47888,SEECLICKFIX_118647,Grand Terrace CA,2018-09-20T08:43:10-04:00,NaN,ce-overgrown weeds,environment,environment_overgrowth,CE-Overgrown Weeds,Overgrown trees on Ladera Street. You cannot ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944140,30713,SEECLICKFIX_96864,Chatham NJ,2018-09-27T18:48:07-04:00,NaN,fields parks & public spaces,governance,governance_parks_and_rec,Fields Parks & Public Spaces,Signs that were reported yesterday and were re...
948746,35319,SEECLICKFIX_102733,Chatham NJ,2018-09-26T10:12:56-04:00,NaN,fields parks & public spaces,governance,governance_parks_and_rec,Other,Signs in ROW near LUM.
950737,37310,SEECLICKFIX_105286,Chatham NJ,2018-09-25T13:27:11-04:00,NaN,overhead & traffic lights signals,street,street_urgent_repair,Overhead & Traffic Lights Signals,The speed limit sign @ 291 Hillside Ave is obs...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944243,30816,SEECLICKFIX_96993,City of Swartz Creek,2018-09-27T17:59:07-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,An individual dropped approximately 12 to 15 u...
951030,37603,SEECLICKFIX_105652,City of Swartz Creek,2018-09-25T12:15:02-04:00,NaN,street light out,street,street_lighting,Street Light Out,This street light has had an overheating balla...
967301,53874,SEECLICKFIX_126320,City of Swartz Creek,2018-09-15T14:41:25-04:00,NaN,blight,environment,environment_general,Blight,Once again there is a vehicle parked in the mi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944348,30921,SEECLICKFIX_97134,Town of Concord,2018-09-27T17:15:06-04:00,NaN,pothole,street,street_repair,Pothole,Street needs to be swept and multiple pot hole...
970165,56738,SEECLICKFIX_129845,Town of Concord,2018-09-12T22:35:37-04:00,NaN,other,governance,governance_general,Other,Overgrowth of weeds makes exiting Channing Rd ...
978789,65362,SEECLICKFIX_140376,Town of Concord,2018-09-05T08:42:51-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944380,30953,SEECLICKFIX_97169,Code Enforcement Area 2,2018-09-27T17:03:01-04:00,NaN,graffiti / vandalism,vandalism,vandalism_graffiti,Graffiti / Vandalism,Multiple watermelons smashed on sidewalk. In...
949340,35913,SEECLICKFIX_103507,Code Enforcement Area 2,2018-09-25T22:41:57-04:00,NaN,street lights,street,street_lighting,Street Lights,Street light and marquee sign by Hwy 6 feeder ...
949506,36079,SEECLICKFIX_103712,Code Enforcement Area 2,2018-09-25T20:34:58-04:00,NaN,weeds and grass,environment,environment_overgrowth,Weeds and Grass,Large overgrown yard.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944423,30996,SEECLICKFIX_97217,WCRC Yard 1,2018-09-27T16:49:15-04:00,NaN,pothole,street,street_repair,Pothole,On either side of Huron Court on Huron River D...
946156,32729,SEECLICKFIX_99415,WCRC Yard 1,2018-09-27T08:17:10-04:00,NaN,pothole,street,street_repair,Pothole,Their have been multiple chunks of asphalt tha...
948618,35191,SEECLICKFIX_102556,WCRC Yard 1,2018-09-26T10:49:49-04:00,NaN,roadside tree removal/maintenance,environment,environment_overgrowth,Roadside Tree Removal/Maintenance,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944435,31008,SEECLICKFIX_97229,WCRC Yard 3,2018-09-27T16:46:49-04:00,NaN,pothole,street,street_repair,Pothole,The road needs to be graded on Fleming Road be...
945148,31721,SEECLICKFIX_98101,WCRC Yard 3,2018-09-27T12:59:06-04:00,NaN,flooding,street,street_drainage,Flooding,When Kalmbach Road was repaved this summer the...
953901,40474,SEECLICKFIX_109365,WCRC Yard 3,2018-09-24T12:36:48-04:00,NaN,roadside tree removal/maintenance,environment,environment_overgrowth,Roadside Tree Removal/Maintenance,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944556,31129,SEECLICKFIX_97371,Bisbee AZ,2018-09-27T16:05:50-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,This car is parked about 3’ from the curb and ...
948739,35312,SEECLICKFIX_102726,Bisbee AZ,2018-09-26T10:14:07-04:00,NaN,other,governance,governance_general,Right of way overgrown,A big bush is overgrowing S end 16th Terrace R...
956145,42718,SEECLICKFIX_112149,Bisbee AZ,2018-09-23T11:08:25-04:00,NaN,other,governance,governance_general,SeeClick???,Our city spent $5k on this SeeClickFix softwar...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944561,31134,SEECLICKFIX_97378,Downtown Santa Cruz,2018-09-27T16:04:40-04:00,NaN,litter on sidewalks,environment,environment_litter,Litter on Sidewalks,Lots of trash piling up behind empty Tampico spot
946511,33084,SEECLICKFIX_99880,Downtown Santa Cruz,2018-09-26T22:11:16-04:00,NaN,spill on sidewalk,street,street_sidewalk,Spill on Sidewalk,NaN
946551,33124,SEECLICKFIX_99929,Downtown Santa Cruz,2018-09-26T21:43:36-04:00,NaN,spill on sidewalk,street,street_sidewalk,Spill on Sidewalk,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944707,31280,SEECLICKFIX_97553,Kewanee IL,2018-09-27T15:10:27-04:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,NEED a stop sign on Central at Cottage for kid...
944709,31282,SEECLICKFIX_97555,Kewanee IL,2018-09-27T15:09:53-04:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,NEED A stop sign on Central Blvd for Kids and ...
950427,37000,SEECLICKFIX_104891,Kewanee IL,2018-09-25T14:48:17-04:00,NaN,other,governance,governance_general,Parking Often No Parking Zone,Vehicles parking at night usually but also at ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944936,31509,SEECLICKFIX_97839,Danville Utility Area,2018-09-27T14:02:14-04:00,NaN,street light out,street,street_lighting,Street light out/very dim,Please put bright light in street light on Col...
944968,31541,SEECLICKFIX_97881,Danville Utility Area,2018-09-27T13:51:43-04:00,NaN,street light out,street,street_lighting,Street light out/very dim,We have seen an increase of crime on Arnett Bl...
948474,35047,SEECLICKFIX_102359,Danville Utility Area,2018-09-26T11:30:16-04:00,NaN,tree limb on or near power line,infrastructure,infrastructure_power,Large tree leaning on power lines,An old oak tree is leaning on power lines and ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
944942,31515,SEECLICKFIX_97848,County Service Area,2018-09-27T14:00:02-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,The light at 441 and 235A is timed inproperly ...
949172,35745,SEECLICKFIX_103306,County Service Area,2018-09-26T07:02:03-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,Left turn did not go green. I could be wrong b...
949673,36246,SEECLICKFIX_103931,County Service Area,2018-09-25T18:56:17-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,Left turn green going north on 34th goes on wh...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
945407,31980,SEECLICKFIX_98435,Hartford Streets - Community Organization,2018-09-27T11:44:46-04:00,NaN,pedestrian facility (sidewalk condition curb r...,street,street_sidewalk,Pedestrian Facility (Sidewalk condition curb r...,2 Street lights are out between Broad Street a...
946471,33044,SEECLICKFIX_99832,Hartford Streets - Community Organization,2018-09-26T22:43:31-04:00,NaN,pedestrian facility (sidewalk condition curb r...,street,street_sidewalk,Pedestrian Facility (Sidewalk condition curb r...,Flat screen TV area rug and other furniture wa...
963773,50346,SEECLICKFIX_121796,Hartford Streets - Community Organization,2018-09-18T14:38:21-04:00,NaN,pedestrian facility (sidewalk condition curb r...,street,street_sidewalk,Street lights out,Street lights out for weeks now??? It is on C...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
945450,32023,SEECLICKFIX_98496,City of Seaford DE,2018-09-27T11:33:12-04:00,NaN,road conditions,street,street_general,Road Conditions,NaN
957234,43807,SEECLICKFIX_113495,City of Seaford DE,2018-09-22T11:32:56-04:00,NaN,trail/sidewalk issue,street,street_sidewalk,Trail/Sidewalk Issue,The sidewalk along Herring Run road described ...
966721,53294,SEECLICKFIX_125590,City of Seaford DE,2018-09-16T14:02:07-04:00,NaN,trail/sidewalk issue,street,street_sidewalk,Trail/Sidewalk Issue,The sidewalk is once again almost impassable d...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
945692,32265,SEECLICKFIX_98809,City of Allen Park,2018-09-27T10:29:51-04:00,NaN,sidewalk issues,street,street_sidewalk,Sidewalk Issues,Our new sidewalk was cracked as a result of ci...
949858,36431,SEECLICKFIX_104181,City of Allen Park,2018-09-25T17:44:06-04:00,NaN,grass height violation,environment,environment_overgrowth,Grass Height on Outer Drive,Grass Length is pathetic
956898,43471,SEECLICKFIX_113063,City of Allen Park,2018-09-22T15:35:11-04:00,NaN,tree removal,environment,environment_overgrowth,Tree Removal,Branch from wind storm on 9/21 caused huge bra...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
946477,33050,SEECLICKFIX_99840,Town of Sudbury,2018-09-26T22:40:33-04:00,NaN,trees - cleanup (trees & cemetery),environment,environment_overgrowth,Trees - Cleanup (Trees & Cemetery),Hi. These tree branches overhang Shadow Oak dr...
950275,36848,SEECLICKFIX_104700,Town of Sudbury,2018-09-25T15:27:30-04:00,NaN,drainage / storm drain (drainage),street,street_drainage,Drainage / Storm Drain (Drainage),Area in front of driveway and along sidewalk h...
952487,39060,SEECLICKFIX_107576,Town of Sudbury,2018-09-24T19:02:53-04:00,NaN,pothole (highway),street,street_repair,Pothole (Highway),Deep pothole on Morse ROad in the vicinity of ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
946602,33175,SEECLICKFIX_99992,Upper Dublin PA,2018-09-26T21:14:19-04:00,NaN,missing/damaged street light,street,street_lighting,Missing/Damaged Street Light,Street light out on street light pole in front...
947238,33811,SEECLICKFIX_100792,Upper Dublin PA,2018-09-26T16:35:05-04:00,NaN,sidewalk damage/issue,street,street_sidewalk,Sidewalk Damage/Issue,Tree branch hanging low along N side of Castle...
954534,41107,SEECLICKFIX_110138,Upper Dublin PA,2018-09-24T10:25:04-04:00,NaN,missing/damaged street light,street,street_lighting,Missing/Damaged Street Light,Street light out on light pole in front of 181...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
946723,33296,SEECLICKFIX_100136,Miami-Dade County - Unincorporated,2018-09-26T19:59:11-04:00,NaN,road hazard,street,street_general,Road Hazard,Street light not working correctly
971352,57925,SEECLICKFIX_131299,Miami-Dade County - Unincorporated,2018-09-12T07:50:14-04:00,NaN,road hazard,street,street_general,School zone signal broken,The yellow flashing school zone light that's t...
1018188,104761,SEECLICKFIX_190130,Miami-Dade County - Unincorporated,2018-07-05T11:15:35-04:00,NaN,potholes,street,street_repair,Potholes,"Large 24\ by 10\"" deep pothole at SW corner of..."

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
946751,33324,SEECLICKFIX_100168,Superior CO,2018-09-26T19:42:02-04:00,NaN,other,governance,governance_general,Standing water in intersection,There is constantly standing water at the inte...
948778,35351,SEECLICKFIX_102770,Superior CO,2018-09-26T10:05:32-04:00,NaN,street or sidewalk damage,street,street_sidewalk,Half-painted crosswalks,A while back they came through and painted jus...
952492,39065,SEECLICKFIX_107586,Superior CO,2018-09-24T18:59:58-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,I believe this house is in violation of the 3 ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
946785,33358,SEECLICKFIX_100212,Stoneham MA,2018-09-26T19:21:22-04:00,NaN,other,governance,governance_general,Rats,NaN
949099,35672,SEECLICKFIX_103212,Stoneham MA,2018-09-26T07:52:18-04:00,NaN,other,governance,governance_general,Hanging teee branches.,Hi. Branches need trimming at 25 Endicott Rd. ...
949951,36524,SEECLICKFIX_104286,Stoneham MA,2018-09-25T17:15:48-04:00,NaN,dpw - street lights/traffic signals,street,street_urgent_repair,DPW - Street Lights/Traffic Signals,Not a traffic light but just came home to a co...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
947003,33576,SEECLICKFIX_100500,Grand Haven MI,2018-09-26T17:47:11-04:00,NaN,street repair,street,street_repair,Street Repair,Catch basin on north side of Columbus street m...
949213,35786,SEECLICKFIX_103362,Grand Haven MI,2018-09-26T05:31:37-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,Huge limb in road
957008,43581,SEECLICKFIX_113215,Grand Haven MI,2018-09-22T14:13:00-04:00,NaN,tree issue,environment,environment_overgrowth,limb down by dairy cream,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
947235,33808,SEECLICKFIX_100787,Darlington SC,2018-09-26T16:36:21-04:00,NaN,pothole or street issue,street,street_repair,Pothole or Street Issue,Flood waters have washed some of the gravel of...
951902,38475,SEECLICKFIX_106828,Darlington SC,2018-09-25T06:36:20-04:00,NaN,other,governance,governance_general,Other,Mosquitos
952378,38951,SEECLICKFIX_107420,Darlington SC,2018-09-24T20:03:38-04:00,NaN,other,governance,governance_general,Other,Mosquitos

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
947293,33866,SEECLICKFIX_100868,City of Peculiar,2018-09-26T16:08:46-04:00,NaN,water (general concern),infrastructure,infrastructure_water,Water (General Concern),Water pressure is very low and would like some...
947613,34186,SEECLICKFIX_101238,City of Peculiar,2018-09-26T15:05:55-04:00,NaN,other,governance,governance_general,Other,NaN
951293,37866,SEECLICKFIX_106004,City of Peculiar,2018-09-25T10:48:22-04:00,NaN,trash pick up problem,environment,environment_garbage_collection,Trash Pick Up Problem,For the past two weeks WCA has been leaving re...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
947659,34232,SEECLICKFIX_101286,Greenfield WI,2018-09-26T15:00:05-04:00,NaN,private property issue,housing,housing_general,Private Property Issue,Per ordinance there's no dumpster enclosure ar...
947764,34337,SEECLICKFIX_101412,Greenfield WI,2018-09-26T14:45:28-04:00,NaN,private property issue,housing,housing_general,Private Property Issue,blocking exit door
948703,35276,SEECLICKFIX_102675,Greenfield WI,2018-09-26T10:24:34-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,No one lives here and there has been a broken ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
947945,34518,SEECLICKFIX_101678,Chapel Hill NC,2018-09-26T13:51:09-04:00,NaN,sidewalk repair,street,street_sidewalk,Sidewalk Repair,We would like to request more Chapel Hill grav...
949499,36072,SEECLICKFIX_103703,Chapel Hill NC,2018-09-25T20:39:06-04:00,NaN,pothole,street,street_repair,Pothole,The issue is really along the entire side of t...
954517,41090,SEECLICKFIX_110113,Chapel Hill NC,2018-09-24T10:29:00-04:00,NaN,dead animal,environment,environment_dead_animal,Dead Animal,Resident called about dead deer in Avalon crt....

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
948132,34705,SEECLICKFIX_101913,City of Adrian,2018-09-26T13:04:52-04:00,NaN,grass or vegetation too long,environment,environment_overgrowth,Grass or Vegetation Too Long,Please mow this lot
951113,37686,SEECLICKFIX_105757,City of Adrian,2018-09-25T11:51:12-04:00,NaN,grass or vegetation too long,environment,environment_overgrowth,Grass or Vegetation Too Long,City owned property that never gets mowed unle...
952790,39363,SEECLICKFIX_107974,City of Adrian,2018-09-24T17:09:28-04:00,NaN,other,governance,governance_general,Other,The traffic on Riverside is terrible 30 mile p...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
948737,35310,SEECLICKFIX_102724,Police Sector 3,2018-09-26T10:14:48-04:00,NaN,general police enforcement issue,public_order,publicorder_general,General Police Enforcement Issue,Homeless sleeping behind building. https://ir...
948751,35324,SEECLICKFIX_102738,Police Sector 3,2018-09-26T10:12:26-04:00,NaN,general police enforcement issue,public_order,publicorder_general,General Police Enforcement Issue,Homeless including those evading the law are c...
950960,37533,SEECLICKFIX_105567,Police Sector 3,2018-09-25T12:34:22-04:00,NaN,general police enforcement issue,public_order,publicorder_general,General Police Enforcement Issue,People asking for money distracting drivers ha...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
948860,35433,SEECLICKFIX_102883,City of Fountain Inn SC,2018-09-26T09:34:57-04:00,NaN,other,governance,governance_general,Other,It’s like a speed bump and there’s another nea...
953342,39915,SEECLICKFIX_108667,City of Fountain Inn SC,2018-09-24T14:57:56-04:00,NaN,other,governance,governance_general,Request for items at road for pick up/damaged ...,Request for items at road for pick up/damaged ...
959867,46440,SEECLICKFIX_116846,City of Fountain Inn SC,2018-09-20T18:35:32-04:00,NaN,other,governance,governance_general,trash at road,debris has been at the road over 2 weeks. whe...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
948962,35535,SEECLICKFIX_103033,Road Conditions,2018-09-26T08:54:14-04:00,NaN,pothole,street,street_repair,Pothole,Construction below the Bayonne bridge on Richm...
951715,38288,SEECLICKFIX_106562,Road Conditions,2018-09-25T08:45:39-04:00,NaN,pothole,street,street_repair,Pothole,Large pothole on Wilder ave near double yello...
966301,52874,SEECLICKFIX_125022,Road Conditions,2018-09-16T23:26:54-04:00,NaN,pothole,street,street_repair,Pothole,Street undermined causing a large hole to form...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949138,35711,SEECLICKFIX_103266,Uxbridge MA,2018-09-26T07:26:17-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,NaN
949142,35715,SEECLICKFIX_103270,Uxbridge MA,2018-09-26T07:25:16-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,NaN
962123,48696,SEECLICKFIX_119660,Uxbridge MA,2018-09-19T15:40:00-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,Large soil trucks are still trying to get down...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949274,35847,SEECLICKFIX_103431,Utility Service Area,2018-09-26T00:47:03-04:00,NaN,streetlight,street,street_lighting,Streetlight,Just south of 8th ave. Light has been out for ...
952114,38687,SEECLICKFIX_107081,Utility Service Area,2018-09-24T22:30:11-04:00,NaN,streetlight,street,street_lighting,Streetlight,There is an ExTREMELY bright light on this str...
957370,43943,SEECLICKFIX_113685,Utility Service Area,2018-09-22T09:49:09-04:00,NaN,streetlight,street,street_lighting,Streetlight,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949308,35881,SEECLICKFIX_103471,City of Burlingame,2018-09-25T23:30:37-04:00,NaN,street light,street,street_lighting,Street Light,Streetlight out across st. from 1131 Eastmoor ...
955883,42456,SEECLICKFIX_111829,City of Burlingame,2018-09-23T14:25:05-04:00,NaN,parks & playgrounds,governance,governance_parks_and_rec,Parks & Playgrounds,Trees cut down. Why?
957536,44109,SEECLICKFIX_113930,City of Burlingame,2018-09-22T00:57:21-04:00,NaN,street light,street,street_lighting,Right turn green light,one of the two right turn lights from Old Bay...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949371,35944,SEECLICKFIX_103545,Coachella CA,2018-09-25T22:17:06-04:00,NaN,street light maintenance,street,street_lighting,Street Light Maintenance,Some pathway lights at Bagdouma park need repl...
949889,36462,SEECLICKFIX_104217,Coachella CA,2018-09-25T17:36:10-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,There has been an abandoned vehicle (Red Astro...
949952,36525,SEECLICKFIX_104289,Coachella CA,2018-09-25T17:14:50-04:00,NaN,street light maintenance,street,street_lighting,Street Light Maintenance,The street light has not been functioning for ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949658,36231,SEECLICKFIX_103911,East Chicago IN,2018-09-25T19:05:16-04:00,NaN,mosquito infestation,public_health,publichealth_pests,Mosquito Infestation,need a mosquito truck in the markdown area
974598,61171,SEECLICKFIX_135261,East Chicago IN,2018-09-09T10:28:33-04:00,NaN,graffiti removal,vandalism,vandalism_graffiti,Graffiti Removal,NaN
974599,61172,SEECLICKFIX_135262,East Chicago IN,2018-09-09T10:27:32-04:00,NaN,graffiti removal,vandalism,vandalism_graffiti,Graffiti Removal,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
949681,36254,SEECLICKFIX_103939,Tornado 2018,2018-09-25T18:53:56-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,sidewalk is buckled cracked and crumbling
981302,67875,SEECLICKFIX_143463,Tornado 2018,2018-09-01T18:33:30-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,I'm not sure if this went through before. To...
1005773,92346,SEECLICKFIX_174465,Tornado 2018,2018-07-27T09:05:15-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,Resident reported to the Engineering Departmen...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
950021,36594,SEECLICKFIX_104371,Borough of Merchantville,2018-09-25T16:46:50-04:00,NaN,road or sidewalk repair problem,street,street_sidewalk,Crosswalk needs repainting,The crosswalk paint stripes are barely visible...
1007246,93819,SEECLICKFIX_176361,Borough of Merchantville,2018-07-24T18:45:16-04:00,NaN,road or sidewalk repair problem,street,street_sidewalk,Road or sidewalk repair problem,There is a bee hive under the risen sidewalk i...
1022091,108664,SEECLICKFIX_195032,Borough of Merchantville,2018-06-27T19:13:53-04:00,NaN,tree issue (downed tree or limb trimming needed),environment,environment_overgrowth,tree blocking stop sign,tree branches blocking view of stop sign on ch...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
950069,36642,SEECLICKFIX_104434,City of Roseville MI,2018-09-25T16:27:26-04:00,NaN,other,governance,governance_general,Street Light,The street light at the corner of Chestnut and...
950954,37527,SEECLICKFIX_105561,City of Roseville MI,2018-09-25T12:35:25-04:00,NaN,pothole,street,street_repair,Pothole,from the cement to the asphalt there are potho...
957082,43655,SEECLICKFIX_113313,City of Roseville MI,2018-09-22T13:09:54-04:00,NaN,pothole,street,street_repair,Pothole,There are 2 homes that exit onto Academy Lane....

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
950081,36654,SEECLICKFIX_104451,Bayside Village,2018-09-25T16:21:40-04:00,NaN,pothole,street,street_repair,Pothole,East side of Iroquois Road south of Fairy Chas...
953602,40175,SEECLICKFIX_108996,Bayside Village,2018-09-24T13:51:25-04:00,NaN,pothole,street,street_repair,Pothole,A stormwater issue resulting from the driveway...
953841,40414,SEECLICKFIX_109292,Bayside Village,2018-09-24T12:49:52-04:00,NaN,tree issues (hazard dead maintenance etc.),environment,environment_overgrowth,Tree Issues (Hazard Dead Maintenance Etc.),Willow tree that went down on near Fox Point/B...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
951765,38338,SEECLICKFIX_106625,Town of Wenham,2018-09-25T08:31:26-04:00,NaN,pothole,street,street_repair,Pothole,The potholes have gotten bad again on Woodside...
955611,42184,SEECLICKFIX_111483,Town of Wenham,2018-09-23T17:46:27-04:00,NaN,signs,governance,governance_signage,Signs,The first sign appears around 9/4 another arou...
956781,43354,SEECLICKFIX_112925,Town of Wenham,2018-09-22T17:04:29-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,We are very concerned about the huge pine tree...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
951813,38386,SEECLICKFIX_106687,Village of Perry,2018-09-25T08:15:56-04:00,NaN,street maintenance,street,street_general,Pot Hole around storm Drain,Large pot hole
951818,38391,SEECLICKFIX_106696,Village of Perry,2018-09-25T08:11:56-04:00,NaN,street maintenance,street,street_general,No traffic sign,Three way intersection no traffic sign.
957213,43786,SEECLICKFIX_113472,Village of Perry,2018-09-22T11:43:15-04:00,NaN,blight,environment,environment_general,Blight,Is the Village responsible for keeping weeds o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
951884,38457,SEECLICKFIX_106791,City of Loganville,2018-09-25T07:26:59-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,Street light infront if 371 Baymist Dr isn't w...
982499,69072,SEECLICKFIX_144935,City of Loganville,2018-08-30T20:51:24-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,The lights in Phase2 of Laurelmist Subdivision...
982603,69176,SEECLICKFIX_145064,City of Loganville,2018-08-30T18:26:43-04:00,NaN,water or sewer issue,infrastructure,infrastructure_water,Water or Sewer Issue,I am trying to confirm that the utility accoun...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
951991,38564,SEECLICKFIX_106933,Richmond,2018-09-25T00:37:43-04:00,NaN,street light,street,street_lighting,Street Light,Lamp is so dark and flickering
955175,41748,SEECLICKFIX_110968,Richmond,2018-09-23T23:28:16-04:00,NaN,street light,street,street_lighting,Street Light,Almost half the street lights on Turnill Stree...
974847,61420,SEECLICKFIX_135561,Richmond,2018-09-08T19:17:24-04:00,NaN,street light,street,street_lighting,Street Light,This is not for a street light but for stair l...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
952169,38742,SEECLICKFIX_107153,Shorewood MN,2018-09-24T22:00:53-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,I contacted Xcel and she indicated light was c...
953853,40426,SEECLICKFIX_109305,Shorewood MN,2018-09-24T12:47:24-04:00,NaN,tree issue,environment,environment_overgrowth,Tree That Has Been Left Along the Curb,Please advise if the city of Shorewood could p...
957120,43693,SEECLICKFIX_113359,Shorewood MN,2018-09-22T12:40:07-04:00,NaN,other,governance,governance_general,Other,I’m not sure if this is the appropriate place ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
952334,38907,SEECLICKFIX_107366,Town of Westwood MA,2018-09-24T20:24:44-04:00,NaN,pothole,street,street_repair,Pothole,Surrounding small sewer. Needs to be filled.
964855,51428,SEECLICKFIX_123185,Town of Westwood MA,2018-09-17T20:54:15-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,Curb Completely gone at this point at Willow a...
964858,51431,SEECLICKFIX_123188,Town of Westwood MA,2018-09-17T20:52:24-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,Curb gone.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
952383,38956,SEECLICKFIX_107431,Seat Pleasant MD,2018-09-24T20:00:04-04:00,NaN,other,governance,governance_general,Other,Over grown Bushes and shrubbery blocking the s...
956298,42871,SEECLICKFIX_112340,Seat Pleasant MD,2018-09-23T06:50:21-04:00,NaN,pothole,street,street_repair,Pothole,NaN
961502,48075,SEECLICKFIX_118886,Seat Pleasant MD,2018-09-19T23:59:21-04:00,NaN,other,governance,governance_general,NOISE COMPLAINT-OVERDUE,WE HAVING BEEN COMPLAINING FOR OVER 2 WEEKS AB...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
952432,39005,SEECLICKFIX_107500,HumboldtSK Canada,2018-09-24T19:29:07-04:00,NaN,potholes,street,street_repair,Potholes,There is a very deep pothole at the intersecti...
952436,39009,SEECLICKFIX_107508,HumboldtSK Canada,2018-09-24T19:26:04-04:00,NaN,potholes,street,street_repair,Potholes,There is a group of large potholes of at the i...
959504,46077,SEECLICKFIX_116394,HumboldtSK Canada,2018-09-20T23:43:29-04:00,NaN,potholes,street,street_repair,Potholes,Several potholes developing on 6th avenuenear ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
952818,39391,SEECLICKFIX_108008,WCRC Yard 4,2018-09-24T17:00:01-04:00,NaN,roadside tree removal/maintenance,environment,environment_overgrowth,Roadside Tree Removal/Maintenance,NaN
997265,83838,SEECLICKFIX_163665,WCRC Yard 4,2018-08-10T09:39:41-04:00,NaN,flooding,street,street_drainage,Flooding,Wald Strasse edge as built up from rain draina...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
953184,39757,SEECLICKFIX_108463,City of Sandpoint,2018-09-24T15:32:13-04:00,NaN,parked vehicle concerns,street,street_parking,Parked Vehicle Concerns,I stopped by on Friday to address a recent rec...
955090,41663,SEECLICKFIX_110867,City of Sandpoint,2018-09-24T05:08:36-04:00,NaN,animal control,public_health,publichealth_animal,Animal Control,There are two cats that have been killing bird...
956406,42979,SEECLICKFIX_112458,City of Sandpoint,2018-09-22T23:44:54-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,A-frame blocking sidewalk. Not enough space b...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
953407,39980,SEECLICKFIX_108749,Springerville AZ,2018-09-24T14:39:40-04:00,NaN,other,governance,governance_general,Other,Need to pull & weed eat all weeds @ all North ...
953422,39995,SEECLICKFIX_108765,Springerville AZ,2018-09-24T14:36:41-04:00,NaN,street repair,street,street_repair,Street Repair,Potholes on Slash 4 need to be filled in.
978188,64761,SEECLICKFIX_139663,Springerville AZ,2018-09-05T14:55:47-04:00,NaN,street light repair,street,street_lighting,Street Light Repair,Street Light is out across from 333 South Coco...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
953559,40132,SEECLICKFIX_108941,City of Suffolk,2018-09-24T14:00:51-04:00,NaN,pothole,street,street_repair,Pothole,2' pot hole surface 2\ deep in middle of Harbo...
991317,77890,SEECLICKFIX_155941,City of Suffolk,2018-08-19T18:13:58-04:00,NaN,pothole,street,street_repair,Pothole,This is a sinkhole

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
953628,40201,SEECLICKFIX_109027,Code Enforcement Area 4,2018-09-24T13:46:08-04:00,NaN,pothole,street,street_repair,Pothole,multiple pot holes have reappeared after the r...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
954031,40604,SEECLICKFIX_109515,Pinson AL,2018-09-24T12:09:19-04:00,NaN,potholes,street,street_repair,Potholes,Big pothole in middle of road about 2 foot wid...
987513,74086,SEECLICKFIX_151156,Pinson AL,2018-08-24T12:46:22-04:00,NaN,other,governance,governance_general,Other,between 3141 and 3145 cobblestone Dr there is ...
995350,81923,SEECLICKFIX_161243,Pinson AL,2018-08-13T14:45:19-04:00,NaN,other,governance,governance_general,Smoking in Business,The PBS Family Hair Care owner is smoking insi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
954065,40638,SEECLICKFIX_109556,Street Light / Sign / Meter,2018-09-24T12:02:20-04:00,NaN,street light,street,street_lighting,Street Light,very dark intersecting at night. utility poll...
964569,51142,SEECLICKFIX_122833,Street Light / Sign / Meter,2018-09-18T08:34:32-04:00,NaN,street light,street,street_lighting,Street Light,Street lights not working. Entire block is out
997382,83955,SEECLICKFIX_163818,Street Light / Sign / Meter,2018-08-09T23:31:03-04:00,NaN,street light,street,street_lighting,Street Light,Lights off on Silverbeech rd and both Twin Oak...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
954338,40911,SEECLICKFIX_109892,Pinellas County - proper,2018-09-24T11:04:52-04:00,NaN,county parks,governance,governance_parks_and_rec,County Parks - Handicap Ramp,Local fitness business blocks the only handica...
964889,51462,SEECLICKFIX_123229,Pinellas County - proper,2018-09-17T20:22:43-04:00,NaN,dead fish,environment,environment_dead_animal,Red Tide,There are hundreds of dead fish washing up int...
971403,57976,SEECLICKFIX_131365,Pinellas County - proper,2018-09-12T01:54:30-04:00,NaN,county parks,governance,governance_parks_and_rec,BACKED UP DRAINAGE SYSTEM AND MOSQUITOS !!!!!,It seems like the whole park is backed up with...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
954368,40941,SEECLICKFIX_109928,Milton,2018-09-24T10:59:19-04:00,NaN,other,governance,governance_general,Other,I am a manger at the Chick-fil-A off of Windwa...
966270,52843,SEECLICKFIX_124985,Milton,2018-09-17T00:53:51-04:00,NaN,other,governance,governance_general,New Roundabouts Break Ground June/July,In viewing the traffic circle lane width in-pe...
969878,56451,SEECLICKFIX_129486,Milton,2018-09-13T10:33:15-04:00,NaN,street lights,street,street_lighting,Street Lights,There is a pedestrian crossing traffic light n...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
956014,42587,SEECLICKFIX_111990,Los Altos Hills CA,2018-09-23T12:44:48-04:00,NaN,other,governance,governance_general,Other,Leaking fire hydrant
975505,62078,SEECLICKFIX_136342,Los Altos Hills CA,2018-09-07T19:36:52-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,Concerned that tree branches on Page Mill Road...
976917,63490,SEECLICKFIX_138066,Los Altos Hills CA,2018-09-06T17:17:17-04:00,NaN,pothole/street pavement,street,street_repair,Street Slurry / Damage to Driveway,Hello we drove over the freshly repaved/slurri...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
956115,42688,SEECLICKFIX_112112,Midtown Management District,2018-09-23T11:36:08-04:00,NaN,other,governance,governance_general,Other,Two food handlers are wearing open to foot wea...
962276,48849,SEECLICKFIX_119859,Midtown Management District,2018-09-19T14:34:40-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Lots of large tags on the construction fencing
962280,48853,SEECLICKFIX_119865,Midtown Management District,2018-09-19T14:32:51-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
956305,42878,SEECLICKFIX_112347,Treasure Island FL,2018-09-23T06:16:04-04:00,NaN,other,governance,governance_general,Other,The swimming pool pump has been broken down fo...
956908,43481,SEECLICKFIX_113074,Treasure Island FL,2018-09-22T15:29:45-04:00,NaN,codes compliance,planning,planning_general,Lack of code compliance with hedge height,Pictures will be sent to City Commissioner and...
958277,44850,SEECLICKFIX_114840,Treasure Island FL,2018-09-21T15:51:43-04:00,NaN,other,governance,governance_general,Other,Bushes blocking and obscuring other signage on...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
958073,44646,SEECLICKFIX_114584,Recycling & Solid Waste,2018-09-21T17:22:45-04:00,NaN,trash & recycling - bin replacement,environment,environment_garbage_collection,Trash & Recycling - Bin Replacement,Broken wheel. Wheel needs to be replaced.
971833,58406,SEECLICKFIX_131872,Recycling & Solid Waste,2018-09-11T17:13:53-04:00,NaN,trash & recycling - general issues,environment,environment_garbage_collection,Trash & Recycling - General Issues,Still no garbage pickup on Mulberry Hill. The...
973096,59669,SEECLICKFIX_133373,Recycling & Solid Waste,2018-09-10T18:46:41-04:00,NaN,trash & recycling - general issues,environment,environment_garbage_collection,Trash & Recycling - General Issues,Regular trash was not picked up today on our s...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
958139,44712,SEECLICKFIX_114666,City of Big Rapids,2018-09-21T16:53:16-04:00,NaN,property maintenance,housing,housing_general,Property Maintenance,Corner of Magnolia Court & Cedar Street.
973015,59588,SEECLICKFIX_133280,City of Big Rapids,2018-09-10T20:04:18-04:00,NaN,blight,environment,environment_general,Blight,Lawn has gone to seed. Needs care.
982011,68584,SEECLICKFIX_144338,City of Big Rapids,2018-08-31T14:13:17-04:00,NaN,other,governance,governance_general,Possible Pot Usage,Strong scent coming from the house concern for...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
959230,45803,SEECLICKFIX_116049,City of Melrose,2018-09-21T09:11:57-04:00,NaN,pothole,street,street_repair,Deep depression in sidewalk,I was removing some soil that had flowed from ...
966131,52704,SEECLICKFIX_124807,City of Melrose,2018-09-17T09:03:55-04:00,NaN,pothole,street,street_repair,Pothole,Manhole cover is sunk in .Very deep car swerve...
966493,53066,SEECLICKFIX_125256,City of Melrose,2018-09-16T18:58:42-04:00,NaN,pothole,street,street_repair,Pothole,Large potholes present on Vista St requiring y...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
959307,45880,SEECLICKFIX_116145,Leominster MA,2018-09-21T08:32:29-04:00,NaN,other,governance,governance_general,alcohol,to much alcohol and pot at field.drunks and ki...
964663,51236,SEECLICKFIX_122952,Leominster MA,2018-09-18T06:46:54-04:00,NaN,trees,environment,environment_overgrowth,Trees,I believe the tree is a Norway Maple. Ants are...
977088,63661,SEECLICKFIX_138278,Leominster MA,2018-09-06T15:03:43-04:00,NaN,trees,environment,environment_overgrowth,Broken limb in large oak,There is a large oak that is in front of my ho...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
959435,46008,SEECLICKFIX_116310,Town of Cumberland,2018-09-21T06:20:31-04:00,NaN,street lights,street,street_lighting,Street Lights,The street light at the corner of Sherman Ave ...
975025,61598,SEECLICKFIX_135776,Town of Cumberland,2018-09-08T15:22:18-04:00,NaN,street lights,street,street_lighting,Street Light out,37 Millers Brook street light is out
986081,72654,SEECLICKFIX_149405,Town of Cumberland,2018-08-27T08:40:38-04:00,NaN,signs,governance,governance_signage,Signs,Is someone going to remove all the Cumberland ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
960212,46785,SEECLICKFIX_117260,Sharon MA,2018-09-20T15:49:16-04:00,NaN,potholes,street,street_repair,Potholes,The pothole is very noticeable when trying to ...
962701,49274,SEECLICKFIX_120382,Sharon MA,2018-09-19T11:27:08-04:00,NaN,tree issues,environment,environment_overgrowth,Tree Issues,A broken lime is hanging on other branches it ...
968106,54679,SEECLICKFIX_127335,Sharon MA,2018-09-14T15:07:08-04:00,NaN,signs,governance,governance_signage,Signs,People continuously fail to stop at posted sto...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
960367,46940,SEECLICKFIX_117451,Alachua County FL,2018-09-20T14:35:53-04:00,NaN,illegal hazardous dumping/discharge,environment,environment_dumping,Illegal Hazardous Dumping/Discharge,More illegal dumping tires
960388,46961,SEECLICKFIX_117476,Alachua County FL,2018-09-20T14:29:34-04:00,NaN,illegal hazardous dumping/discharge,environment,environment_dumping,Illegal Hazardous Dumping/Discharge,Illegal dumping of furniture paintmedical wast...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
961945,48518,SEECLICKFIX_119444,Transportation,2018-09-19T17:13:54-04:00,NaN,drainage,street,street_drainage,Drainage,Ratepayer called in requesting to get a larger...
962396,48969,SEECLICKFIX_119999,Transportation,2018-09-19T13:29:46-04:00,NaN,drainage,street,street_drainage,Drainage,Center line culvert on rr163 east side of road...
970493,57066,SEECLICKFIX_130245,Transportation,2018-09-12T17:01:25-04:00,NaN,drainage,street,street_drainage,Drainage,Rate payer called in about steep slopes around...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
962306,48879,SEECLICKFIX_119898,Killingly CT,2018-09-19T14:12:31-04:00,NaN,blight,environment,environment_general,Blight,Yard all full of crap overgrown grass and some...
990028,76601,SEECLICKFIX_154360,Killingly CT,2018-08-21T10:38:03-04:00,NaN,other,governance,governance_general,Avian excrement,"Suggestion - Remove the wire \net\"" above the ..."
990041,76614,SEECLICKFIX_154376,Killingly CT,2018-08-21T10:29:25-04:00,NaN,other,governance,governance_general,Avian excrement,"Suggestion - Remove the wire \net\"" above the..."

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
962430,49003,SEECLICKFIX_120042,Police,2018-09-19T13:12:43-04:00,NaN,abandoned vehicle *emergencies: call 911*,environment,environment_abandoned_vehicle,Abandoned Vehicle *EMERGENCIES: CALL 911*,A Jeep Wrangler (KSA-0294) has been sitting on...
978129,64702,SEECLICKFIX_139580,Police,2018-09-05T15:35:28-04:00,NaN,abandoned vehicle *emergencies: call 911*,environment,environment_abandoned_vehicle,Abandoned Vehicle *EMERGENCIES: CALL 911*,Blue Acura (tag GSX 3774) with expired inspect...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
962969,49542,SEECLICKFIX_120710,Town of Cranford,2018-09-19T09:10:28-04:00,NaN,other,governance,governance_general,Other,Mohawk Park is in serious need of some mowing....
991871,78444,SEECLICKFIX_156641,Town of Cranford,2018-08-18T14:06:59-04:00,NaN,other,governance,governance_general,Other,Overgrown uninhabited lot.
1061915,148488,SEECLICKFIX_247817,Town of Cranford,2018-03-15T14:59:14-04:00,NaN,pothole/street maintenance,street,street_repair,Pothole/Street Maintenance,Potholes have reopened and new ones have forme...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
963581,50154,SEECLICKFIX_121521,Dunwoody Other,2018-09-18T17:03:14-04:00,NaN,other,governance,governance_general,Traffic,With construction on Mt Vernon many people try...
970859,57432,SEECLICKFIX_130680,Dunwoody Other,2018-09-12T13:14:55-04:00,NaN,other,governance,governance_general,Other,Someone dumped a large truck load of river roc...
972150,58723,SEECLICKFIX_132241,Dunwoody Other,2018-09-11T14:17:54-04:00,NaN,other,governance,governance_general,Dead Cat on side of road,Hello by the intersection of Brandywine Court ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
963722,50295,SEECLICKFIX_121723,Dublin GA (DEMO),2018-09-18T15:19:50-04:00,NaN,pothole,street,street_repair,Potholes,couple of big potholes need fixed please T...
1005263,91836,SEECLICKFIX_173824,Dublin GA (DEMO),2018-07-27T22:20:23-04:00,NaN,other,governance,governance_general,Other,Just before you get to Pinehurst Baptist Churc...
1077558,164131,SEECLICKFIX_270506,Dublin GA (DEMO),2017-12-20T21:07:53-05:00,NaN,street lights,street,street_lighting,Street Lights,A recent storm has blown out the street light ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
964418,50991,SEECLICKFIX_122637,City of Worcester,2018-09-18T10:01:00-04:00,NaN,sidewalk defective,street,street_sidewalk,Sidewalk Defective,The sidewalk isn't defective per se but every ...
989045,75618,SEECLICKFIX_153098,City of Worcester,2018-08-22T13:59:51-04:00,NaN,graffiti on public property,vandalism,vandalism_graffiti,Disgusting graffiti,Graffiti tagged on one side of build across fr...
989644,76217,SEECLICKFIX_153860,City of Worcester,2018-08-21T18:03:34-04:00,NaN,parks - complaint,governance,governance_parks_and_rec,Disgusting graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
965337,51910,SEECLICKFIX_123818,Hurricane Florence CH Response Team,2018-09-17T15:14:17-04:00,NaN,hurricane florence tree down - power line,infrastructure,infrastructure_power,Tree leaning on power line,Neighbor reports tree leaning toward road. No...
965482,52055,SEECLICKFIX_124015,Hurricane Florence CH Response Team,2018-09-17T14:01:46-04:00,NaN,hurricane florence tree down - power line,infrastructure,infrastructure_power,Hurricane Florence Tree Down - Power Line,There is a tree down on power lines at the int...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
966285,52858,SEECLICKFIX_125006,330 McGill Place,2018-09-16T23:46:36-04:00,NaN,maintenance - outdoor lighting 5605,environment,environment_general,Other,Light is fading on and off
970127,56700,SEECLICKFIX_129805,330 McGill Place,2018-09-12T23:29:36-04:00,NaN,maintenance - outdoor lighting 5605,environment,environment_general,Maintenance - Outdoor Lighting 5605,Floodlight above 608 still not working reporte...
993549,80122,SEECLICKFIX_158858,330 McGill Place,2018-08-15T20:56:02-04:00,NaN,maintenance - outdoor lighting 5605,environment,environment_general,Maintenance - Outdoor Lighting 5605,Flood light above 608 not working

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
966633,53206,SEECLICKFIX_125467,City of Whiting,2018-09-16T16:11:21-04:00,NaN,traffic sign or signal issue,street,street_urgent_repair,Traffic Sign or Signal Issue,Cars early in mornings and evenings driving ve...
971286,57859,SEECLICKFIX_131209,City of Whiting,2018-09-12T08:58:47-04:00,NaN,weeds litter debris problem,environment,environment_overgrowth,Weeds overgrowth eyesore,whiting residents every year. take pride in th...
976650,63223,SEECLICKFIX_137747,City of Whiting,2018-09-06T21:28:00-04:00,NaN,weeds litter debris problem,environment,environment_overgrowth,Weeds Litter Debris Problem,Front yard garden overgrown on to public sidew...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
966925,53498,SEECLICKFIX_125846,Patton Township,2018-09-16T08:20:12-04:00,NaN,sidewalk,street,street_sidewalk,Dead bird on the sidewalk,The dead bird has been lying by the lampost fo...
988358,74931,SEECLICKFIX_152223,Patton Township,2018-08-23T12:45:57-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,Sidewalk at Deans Way and Toftrees Ave has bee...
1000835,87408,SEECLICKFIX_168136,Patton Township,2018-08-04T19:56:43-04:00,NaN,hazardous tree,environment,environment_overgrowth,Hazardous Tree,A tree fell on Scotia Road near Meeks Lane. Th...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
967951,54524,SEECLICKFIX_127133,Bylaw,2018-09-14T17:15:42-04:00,NaN,other,governance,governance_general,Other,Resident was issued a municipal ticket for sti...
1064966,151539,SEECLICKFIX_252107,Bylaw,2018-03-03T21:37:30-05:00,NaN,other,governance,governance_general,Other: improper sewage drainage,the owners have created their own bathroom in ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
968147,54720,SEECLICKFIX_127382,Miami-Dade County,2018-09-14T14:44:08-04:00,NaN,road hazard,street,street_general,Road Hazard,This car has been parked on the curb Swail for...
973334,59907,SEECLICKFIX_133671,Miami-Dade County,2018-09-10T15:05:29-04:00,NaN,road hazard,street,street_general,Street black pole outrage,There is a electric black pole outrage theref...
974207,60780,SEECLICKFIX_134769,Miami-Dade County,2018-09-09T18:52:09-04:00,NaN,road hazard,street,street_general,Road Hazard,The Street Lights on S. Bayshore in Coconut Gr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
968642,55215,SEECLICKFIX_127977,Fairfield Bay AR,2018-09-14T09:54:29-04:00,NaN,drainage or ditches,street,street_drainage,Drainage or Ditches,NaN
979219,65792,SEECLICKFIX_140906,Fairfield Bay AR,2018-09-04T17:47:48-04:00,NaN,road conditions,street,street_general,Road Conditions,dead tree fallen
986787,73360,SEECLICKFIX_150294,Fairfield Bay AR,2018-08-25T14:33:53-04:00,NaN,drainage or ditches,street,street_drainage,Drainage or Ditches,The county is going to be clip & sealing that ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
969477,56050,SEECLICKFIX_129001,City of Mercer Island,2018-09-13T13:47:58-04:00,NaN,tree assessment,environment,environment_overgrowth,Tree Removal,A large tree fell on 85th Ave SE the access ro...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
970436,57009,SEECLICKFIX_130173,City of Thorp,2018-09-12T17:41:52-04:00,NaN,other,governance,governance_general,Other,why in the last two months is the odor so bad ...
1002541,89114,SEECLICKFIX_170268,City of Thorp,2018-08-01T20:49:19-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,Pieces of rotted wood are falling on the sidew...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
970448,57021,SEECLICKFIX_130193,City of Jonesboro,2018-09-12T17:29:48-04:00,NaN,private property issue,housing,housing_general,Private Property Issue,Yard full of junk vehicles garbage and trash.
1034848,121421,SEECLICKFIX_211727,City of Jonesboro,2018-05-31T23:01:46-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,Time to buy some Sakrete and make the repair. ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
971003,57576,SEECLICKFIX_130856,Tisbury MA,2018-09-12T12:02:02-04:00,NaN,illegal dumping,environment,environment_dumping,Large Item Trash Pick up,Several couches and chairs are starting to lit...
975712,62285,SEECLICKFIX_136587,Tisbury MA,2018-09-07T16:31:12-04:00,NaN,tree limbs,environment,environment_overgrowth,Tree Limbs,Large dead tree over road (next to locust).
999940,86513,SEECLICKFIX_167037,Tisbury MA,2018-08-06T14:13:07-04:00,NaN,street lights,street,street_lighting,Street Lights,across from Crane's on State Road Eversource c...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
971139,57712,SEECLICKFIX_131023,City of Petal,2018-09-12T10:38:02-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,NaN
978330,64903,SEECLICKFIX_139836,City of Petal,2018-09-05T13:32:37-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Abandoned property. Nobody is taking care of i...
1012782,99355,SEECLICKFIX_183440,City of Petal,2018-07-15T10:28:05-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Badly overgrown apparent inoperable vehicle.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
972139,58712,SEECLICKFIX_132227,Urbana Public Works,2018-09-11T14:22:29-04:00,NaN,other,governance,governance_general,Large wasp nest at Meadowbrook overlook shelter,there's a large wasp or hornet nest in the roo...
981759,68332,SEECLICKFIX_144042,Urbana Public Works,2018-08-31T18:24:10-04:00,NaN,street maintenance,street,street_general,@#%$%#$%!,Who designed that sidewalk with an internal cu...
981760,68333,SEECLICKFIX_144043,Urbana Public Works,2018-08-31T18:21:20-04:00,NaN,street maintenance,street,street_general,Street Maintenance,Rough Road

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
973386,59959,SEECLICKFIX_133744,City of Northfield,2018-09-10T14:18:46-04:00,NaN,potholes,street,street_repair,Potholes,The intersection of Shepherd circle west and R...
974322,60895,SEECLICKFIX_134913,City of Northfield,2018-09-09T16:25:03-04:00,NaN,potholes,street,street_repair,Potholes,Sinkhole that has stopped enlarging but has no...
1003424,89997,SEECLICKFIX_171426,City of Northfield,2018-07-31T15:00:19-04:00,NaN,potholes,street,street_repair,Potholes,I have a pothole in front of my driveway. It ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
974068,60641,SEECLICKFIX_134605,Yarmouth Town Nova Scotia,2018-09-09T22:16:15-04:00,NaN,sign and traffic lights issues,street,street_urgent_repair,Sign and Traffic Lights Issues,pedestrian crosswalk signals not functioning c...
985141,71714,SEECLICKFIX_148216,Yarmouth Town Nova Scotia,2018-08-28T10:04:52-04:00,NaN,street and sidewalk issues,street,street_sidewalk,Street and Sidewalk Issues,The work carried out over the last couple of y...
988991,75564,SEECLICKFIX_153033,Yarmouth Town Nova Scotia,2018-08-22T14:34:53-04:00,NaN,street and sidewalk issues,street,street_sidewalk,Street and Sidewalk Issues,On 20 August I observed a gentleman cutting th...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
975264,61837,SEECLICKFIX_136052,Greenfield DPW,2018-09-08T10:28:07-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,This post serves no apparent purpose except to...
981480,68053,SEECLICKFIX_143689,Greenfield DPW,2018-09-01T12:19:15-04:00,NaN,other,governance,governance_general,please make crosswalk visible so cars will sto...,NaN
985719,72292,SEECLICKFIX_148940,Greenfield DPW,2018-08-27T14:38:44-04:00,NaN,sidewalk,street,street_sidewalk,Sidewalk,Sidewalk is disintegrating in front of 113 Bea...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
975336,61909,SEECLICKFIX_136137,City of Ventnor,2018-09-08T07:03:35-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,sidewalk is collapsing right where people walk...
978814,65387,SEECLICKFIX_140409,City of Ventnor,2018-09-05T08:22:34-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,Grass needs cutting and weeds cut from fence.
995678,82251,SEECLICKFIX_161686,City of Ventnor,2018-08-13T10:19:10-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,Excessive noise from rooftop HVAC mechanical e...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
975388,61961,SEECLICKFIX_136201,City of Lauderhill,2018-09-07T23:20:40-04:00,NaN,pothole,street,street_repair,Two Gigantic potholes near stoplight in right ...,Accident almost caused because of two giant po...
1046184,132757,SEECLICKFIX_226459,City of Lauderhill,2018-05-07T16:41:55-04:00,NaN,street lights,street,street_lighting,Street Light,Street is out at that location.
1078239,164812,SEECLICKFIX_271484,City of Lauderhill,2017-12-14T19:31:19-05:00,NaN,street lights,street,street_lighting,Street Lights,The street light at the aforementioned address...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
975407,61980,SEECLICKFIX_136226,Lauderdale Lakes,2018-09-07T22:33:30-04:00,NaN,pothole,street,street_repair,Damaging pot hole,Pot hole in road almost looks like a hole in t...
1138334,224907,SEECLICKFIX_354610,Lauderdale Lakes,2016-10-31T16:09:57-04:00,NaN,road hazard,street,street_general,Road Hazard,Powerline wire on sidewalk visible not sure if...
1138341,224914,SEECLICKFIX_354621,Lauderdale Lakes,2016-10-31T15:22:59-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,One of many bus stops and sidewalks in communi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
976184,62757,SEECLICKFIX_137179,Carolina Shores NC,2018-09-07T11:03:05-04:00,NaN,other,governance,governance_general,Other,There is a tree directly behind my backyard th...
984834,71407,SEECLICKFIX_147826,Carolina Shores NC,2018-08-28T14:05:27-04:00,NaN,streets - pavement,street,street_general,Streets - Pavement,Mr. Ross stated that there were trucks on Sunf...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
976419,62992,SEECLICKFIX_137459,Safe Routes Florida - BMSD,2018-09-07T08:42:18-04:00,NaN,pothole,street,street_repair,Pothole,its a road hazard also right in front of the c...
993542,80115,SEECLICKFIX_158849,Safe Routes Florida - BMSD,2018-08-15T21:09:54-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Sidewalk torn up. No barricades nothing to le...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
976866,63439,SEECLICKFIX_138004,Buildings,2018-09-06T18:01:31-04:00,NaN,abandoned structure,environment,environment_abandoned_site,Abandoned Structure,The condemned Midland Hotel. The door facing P...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
976967,63540,SEECLICKFIX_138131,City of Hughson,2018-09-06T16:31:34-04:00,NaN,streetlight,street,street_lighting,Streetlight,Light repeatedly going on an off. May be due f...
983485,70058,SEECLICKFIX_146143,City of Hughson,2018-08-29T19:02:34-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Abandoned vehicle on private property
983486,70059,SEECLICKFIX_146145,City of Hughson,2018-08-29T19:00:39-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Abandoned vehicle on private property with spi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
977105,63678,SEECLICKFIX_138300,Water/Sewer,2018-09-06T14:50:43-04:00,NaN,water/sewer billing question,infrastructure,infrastructure_water,Water/Sewer Billing Question,trying to get the amount owed on my bill acct#...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
977294,63867,SEECLICKFIX_138530,Town of Cohasset,2018-09-06T12:26:54-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,The sidewalk across 24 Forest Ave. has been ri...
1007491,94064,SEECLICKFIX_176677,Town of Cohasset,2018-07-24T13:59:08-04:00,NaN,other,governance,governance_general,Other,We have a bunch of trees that need to be trimm...
1042664,129237,SEECLICKFIX_221898,Town of Cohasset,2018-05-15T21:48:09-04:00,NaN,sidewalk issue,street,street_sidewalk,Poison ivy,There is a significant amount of poison ivy on...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
978885,65458,SEECLICKFIX_140501,City of Hialeah,2018-09-05T05:58:44-04:00,NaN,road hazard,street,street_general,Speeding,This street never gets monitored for speeders ...
980085,66658,SEECLICKFIX_141971,City of Hialeah,2018-09-04T06:03:17-04:00,NaN,road hazard,street,street_general,Street light out 2 of them,Two street lights out next to each other 6680 ...
1031145,117718,SEECLICKFIX_206838,City of Hialeah,2018-06-08T17:28:17-04:00,NaN,pothole,street,street_repair,Pothole,There is a large pothole on the southbound Le ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
980460,67033,SEECLICKFIX_142415,O'Fallon,2018-09-03T14:35:30-04:00,NaN,street lights,street,street_lighting,Street light is out,Absolutely no lighting on this street. The one...
989750,76323,SEECLICKFIX_153989,O'Fallon,2018-08-21T16:05:33-04:00,NaN,street lights,street,street_lighting,Street Lights,NaN
1005410,91983,SEECLICKFIX_174005,O'Fallon,2018-07-27T16:26:27-04:00,NaN,street lights,street,street_lighting,Street Light Out,The street light is out. Please fix it.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
981170,67743,SEECLICKFIX_143310,ECC/HANH Residents,2018-09-01T23:19:56-04:00,NaN,other,governance,governance_general,Other,People are driving through here on motorcycles...
981176,67749,SEECLICKFIX_143318,ECC/HANH Residents,2018-09-01T23:01:42-04:00,NaN,other,governance,governance_general,Other,A guy is outside disturbing the peace
981177,67750,SEECLICKFIX_143320,ECC/HANH Residents,2018-09-01T22:52:36-04:00,NaN,other,governance,governance_general,Other,Breach of peace. People are loitering

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
982440,69013,SEECLICKFIX_144864,Surrey Community,2018-08-30T22:19:15-04:00,NaN,other,governance,governance_general,Dead animal,There is a black dead kitten on the road
1001203,87776,SEECLICKFIX_168608,Surrey Community,2018-08-03T19:43:29-04:00,NaN,other,governance,governance_general,Other,there is a dead racoon on the grass in front o...
1005984,92557,SEECLICKFIX_174764,Surrey Community,2018-07-26T17:42:25-04:00,NaN,other,governance,governance_general,Other,An underground wasp nest has been built at the...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
983686,70259,SEECLICKFIX_146381,City of Rochester,2018-08-29T15:37:37-04:00,NaN,other,governance,governance_general,Post to Neighbors,side walk
990485,77058,SEECLICKFIX_154923,City of Rochester,2018-08-20T18:03:52-04:00,NaN,other,governance,governance_general,Other,The tree owned by the city on the curb side of...
992292,78865,SEECLICKFIX_157158,City of Rochester,2018-08-17T14:55:51-04:00,NaN,blight (incl. tall grass and weeds),environment,environment_overgrowth,Blight (incl. tall grass and weeds),House was demolished in September 2017. Lawn a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
986816,73389,SEECLICKFIX_150326,Town of Hillsborough,2018-08-25T13:52:42-04:00,NaN,other,governance,governance_general,Dead trees,On south side of Robinwood Lane between Denise...
1017293,103866,SEECLICKFIX_189026,Town of Hillsborough,2018-07-06T18:52:09-04:00,NaN,litter / dumping,environment,environment_litter,Litter / Dumping,Across the street from 748 El Cerrito Hillsbor...
1017763,104336,SEECLICKFIX_189607,Town of Hillsborough,2018-07-06T03:53:30-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,The garbage recycling and compost bins outside...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
988130,74703,SEECLICKFIX_151941,Georgetown MA,2018-08-23T16:08:57-04:00,NaN,traffic or street sign issue,street,street_urgent_repair,Town Bylaws and Speed Signs,It appears that the signage on MA-97 and 133 a...
1018433,105006,SEECLICKFIX_190430,Georgetown MA,2018-07-04T20:38:54-04:00,NaN,pothole,street,street_repair,Pothole,Is there a plan to repave Thurlow St through G...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
989968,76541,SEECLICKFIX_154282,Dalton GA Code Enforcement,2018-08-21T12:00:42-04:00,NaN,littering / illegal dumping,environment,environment_dumping,Littering / Illegal Dumping,Citizen informed me that neighbors had placed ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
994524,81097,SEECLICKFIX_160122,City of Mesquite,2018-08-14T15:23:03-04:00,NaN,other,governance,governance_general,Junkyard Mess,There are dozens of wrecked cars lined up on t...
998224,84797,SEECLICKFIX_164846,City of Mesquite,2018-08-08T18:03:35-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,The owner caren page who moved in #33 about 3 ...
1006694,93267,SEECLICKFIX_175666,City of Mesquite,2018-07-25T15:31:56-04:00,NaN,other,governance,governance_general,Other,This property has become a real eyesore in/aro...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
996984,83557,SEECLICKFIX_163336,Forsyth GA,2018-08-10T13:55:15-04:00,NaN,other,governance,governance_general,Other,Branches hanging over road
996992,83565,SEECLICKFIX_163346,Forsyth GA,2018-08-10T13:47:13-04:00,NaN,pothole,street,street_repair,Pothole,Mud/Pothole
1009071,95644,SEECLICKFIX_178739,Forsyth GA,2018-07-21T13:02:08-04:00,NaN,sewer system issue,infrastructure,infrastructure_water,Sewer System Issue,Beaver has built a dam that causes the water n...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
999924,86497,SEECLICKFIX_167016,Miami-Dade County - Roads,2018-08-06T14:23:24-04:00,NaN,potholes,street,street_repair,Potholes,Pothole on NE 10th Ave and 89 Street on West s...
1005368,91941,SEECLICKFIX_173952,Miami-Dade County - Roads,2018-07-27T18:05:28-04:00,NaN,potholes,street,street_repair,Potholes,NaN
1005504,92077,SEECLICKFIX_174123,Miami-Dade County - Roads,2018-07-27T14:23:58-04:00,NaN,potholes,street,street_repair,Potholes,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1002611,89184,SEECLICKFIX_170358,New Haven: Internal,2018-08-01T18:26:19-04:00,NaN,housing violation,housing,housing_general,Cars are parked everyday on front lawns even o...,This issue was reported before. Cars ate parke...
1020196,106769,SEECLICKFIX_192650,New Haven: Internal,2018-07-01T10:25:12-04:00,NaN,tall grass or weeds,environment,environment_overgrowth,Public Space Streets and Drains,Grass bordering the beach in City Point needs ...
1024372,110945,SEECLICKFIX_198068,New Haven: Internal,2018-06-23T01:57:40-04:00,NaN,housing violation,housing,housing_general,Roach infestation in residence which includes ...,169 Weybosset Street is infested with roaches....

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1002624,89197,SEECLICKFIX_170375,City of Webster,2018-08-01T18:11:39-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,NaN
1030843,117416,SEECLICKFIX_206451,City of Webster,2018-06-09T16:41:27-04:00,NaN,street signs,governance,governance_signage,Street sign broken- laying on sidewalk,Street sign broken off at base laying on sidew...
1078864,165437,SEECLICKFIX_272403,City of Webster,2017-12-09T13:49:01-05:00,NaN,other,governance,governance_general,Traffic Signal - timing issue,Between 5:00am-5:30am there are several motori...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1004659,91232,SEECLICKFIX_173082,Anchorage,2018-07-29T17:47:10-04:00,NaN,other,governance,governance_general,Garmin Customer Support,A Garmin GPS unit can take you pretty much any...
1042350,128923,SEECLICKFIX_221503,Anchorage,2018-05-16T13:00:56-04:00,NaN,street maintenance,street,street_general,Street Maintenance,Piper St. pavement is heaved and buckling wher...
1046092,132665,SEECLICKFIX_226340,Anchorage,2018-05-07T20:04:50-04:00,NaN,street maintenance,street,street_general,Street Maintenance,Here's the photos...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1007648,94221,SEECLICKFIX_176879,Parks & Recreation,2018-07-24T11:43:29-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,Dead tree at the end of Rapp Run Road

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1007838,94411,SEECLICKFIX_177120,ECC/HANH Voucher Residents,2018-07-24T04:01:42-04:00,NaN,other,governance,governance_general,Other,There are mischief-maker throughout the commun...
1045428,132001,SEECLICKFIX_225456,ECC/HANH Voucher Residents,2018-05-09T10:56:59-04:00,NaN,other,governance,governance_general,Other,A guy keep coming over riding a motorcycle. sh...
1049627,136200,SEECLICKFIX_230995,ECC/HANH Voucher Residents,2018-04-29T02:09:46-04:00,NaN,other,governance,governance_general,Other,There walking to close to apartments with ther...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1012895,99468,SEECLICKFIX_183579,HMS: Common Issues,2018-07-14T21:12:28-04:00,NaN,other community lighting,environment,environment_general,Other Community Lighting,pool lights always on
1019402,105975,SEECLICKFIX_191655,HMS: Common Issues,2018-07-02T20:59:26-04:00,NaN,other,governance,governance_general,Other,The lawn service has not edged the side walk o...
1039285,125858,SEECLICKFIX_217725,HMS: Common Issues,2018-05-22T09:07:06-04:00,NaN,other,governance,governance_general,Weeds in yard,The 2nd house on left as you enter the cul de ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1018744,105317,SEECLICKFIX_190835,Health Concerns / Pest Control,2018-07-03T20:17:59-04:00,NaN,mosquito complaints,public_health,publichealth_pests,Mosquito Complaints,overgrown abandoned property. infested with mo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1022782,109355,SEECLICKFIX_195954,City of Bedford,2018-06-26T16:08:43-04:00,NaN,pothole,street,street_repair,Pothole,There are 2 huge potholes when you are turning...
1025749,112322,SEECLICKFIX_199800,City of Bedford,2018-06-20T15:30:50-04:00,NaN,other,governance,governance_general,Other,Shrubs and bushes---too tall to see when you'r...
1027974,114547,SEECLICKFIX_202696,City of Bedford,2018-06-15T13:18:20-04:00,NaN,pothole,street,street_repair,Pothole at corner of Meetinghouse and S. River...,Pothole on West side of S. River Rd at Meeting...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1035122,121695,SEECLICKFIX_212094,Lowell Community,2018-05-31T14:13:35-04:00,NaN,pothole,street,street_repair,Pothole,Coming out of the parking lot on the Walker St...
1039428,126001,SEECLICKFIX_217915,Lowell Community,2018-05-21T20:10:18-04:00,NaN,other,governance,governance_general,All LRTA buses should serve downtown Lowell,All LRTA buses which end at the train station ...
1051230,137803,SEECLICKFIX_233120,Lowell Community,2018-04-24T15:30:34-04:00,NaN,other,governance,governance_general,motor vehicle on bikepath during lunchtime,and the truck didn't look official. after wha...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1036277,122850,SEECLICKFIX_213715,Wadesboro NC,2018-05-29T15:13:15-04:00,NaN,other,governance,governance_general,53 n,Damaged 400 pr
1054732,141305,SEECLICKFIX_237693,Wadesboro NC,2018-04-14T16:16:27-04:00,NaN,other,governance,governance_general,Damaged 25pair cable,2 cables need attached to new pole. New pole h...
1096795,183368,SEECLICKFIX_297710,Wadesboro NC,2017-08-15T00:06:18-04:00,NaN,other,governance,governance_general,Tore down cable from wreck on Highway 74 had t...,Mazda was fleeing from the police hit broke po...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1042699,129272,SEECLICKFIX_221940,Water and Sewer,2018-05-15T20:24:46-04:00,NaN,water theft concern,infrastructure,infrastructure_water,Water Theft Concern,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1042873,129446,SEECLICKFIX_222165,Jacksonville,2018-05-15T14:57:26-04:00,NaN,high weeds and grass,environment,environment_overgrowth,High weeds and grass,This lot is an eyesore and needs to be mowed
1043709,130282,SEECLICKFIX_223211,Jacksonville,2018-05-14T09:16:44-04:00,NaN,high weeds and grass,environment,environment_overgrowth,High weeds and grass,High weeds n grass on Idle Creek don't have ad...
1043894,130467,SEECLICKFIX_223472,Jacksonville,2018-05-13T13:29:59-04:00,NaN,high weeds and grass,environment,environment_overgrowth,High weeds and grass,High weeds and grass at 515 John St. Frequent ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1048860,135433,SEECLICKFIX_229963,City of Miami Gardens,2018-04-30T20:05:18-04:00,NaN,sidewalks or crosswalks,street,street_sidewalk,Sidewalks or Crosswalks,Test
1165128,251701,SEECLICKFIX_386357,City of Miami Gardens,2016-08-03T00:08:13-04:00,NaN,road hazard,street,street_general,Street Light not working,Street Light is blown in front of 17645 nw 19t...
1178188,264761,SEECLICKFIX_402105,City of Miami Gardens,2016-06-16T22:21:00-04:00,NaN,road hazard,street,street_general,Road Hazard / Lights are OUT,New World 42 Townhomes - Lights are OUT - Par...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1056288,142861,SEECLICKFIX_239856,City of Canton,2018-04-09T09:46:02-04:00,NaN,brush pick up request,environment,environment_overgrowth,Brush Pick Up Request,Branch and brush pick-up request for 126 Laure...
1058082,144655,SEECLICKFIX_242399,City of Canton,2018-04-01T16:49:22-04:00,NaN,brush pick up request,environment,environment_overgrowth,Brush Pick Up Request,NaN
1059173,145746,SEECLICKFIX_243904,City of Canton,2018-03-27T15:55:53-04:00,NaN,street light,street,street_lighting,Street Light,Street light down the left side of house and a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1057751,144324,SEECLICKFIX_241954,City of Shoreline - Public Works / Customer Re...,2018-04-02T18:38:17-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,NaN
1058147,144720,SEECLICKFIX_242491,City of Shoreline - Public Works / Customer Re...,2018-03-31T23:45:03-04:00,NaN,other,governance,governance_general,Pedestrian Crosswalk Button Seems to be Non-Fu...,This afternoon I was trying to cross Aurora we...
1058564,145137,SEECLICKFIX_243075,City of Shoreline - Public Works / Customer Re...,2018-03-29T16:47:47-04:00,NaN,graffiti / vandalism,vandalism,vandalism_graffiti,Graffiti / Vandalism,Yummy defacing telephone wiring box

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1058154,144727,SEECLICKFIX_242500,City of Shoreline - Parks,2018-03-31T22:30:28-04:00,NaN,trees / vegetation issues,environment,environment_overgrowth,Trees / Vegetation Issues,Heavy invasive ivy hanging on to 4-5 trees alo...
1058277,144850,SEECLICKFIX_242666,City of Shoreline - Parks,2018-03-31T09:57:11-04:00,NaN,trees / vegetation issues,environment,environment_overgrowth,Trees / Vegetation Issues,Laurel bushes overhang and obstruct much of si...
1070067,156640,SEECLICKFIX_259527,City of Shoreline - Parks,2018-02-11T13:00:07-05:00,NaN,trees / vegetation issues,environment,environment_overgrowth,Trees / Vegetation Issues,Trees are leaning over road some are falling p...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1058260,144833,SEECLICKFIX_242644,City of Sartell,2018-03-31T11:26:38-04:00,NaN,snow plow issue,street,street_slippery,Snow Plow Issue,Yard damage
1061716,148289,SEECLICKFIX_247559,City of Sartell,2018-03-16T11:20:57-04:00,NaN,street light out,street,street_lighting,Street Light Out,NaN
1082519,169092,SEECLICKFIX_277670,City of Sartell,2017-11-09T20:19:43-05:00,NaN,street light out,street,street_lighting,Street Light Out,We had new street lights installed two weeks a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1058561,145134,SEECLICKFIX_243071,Fayette AL,2018-03-29T16:59:39-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,A contractor problem sewer rehab created stand...
1077616,164189,SEECLICKFIX_270585,Fayette AL,2017-12-20T14:16:16-05:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,NaN
1099073,185646,SEECLICKFIX_300761,Fayette AL,2017-08-02T12:11:17-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1060511,147084,SEECLICKFIX_245790,Big Lake MN,2018-03-21T16:38:06-04:00,NaN,illegal carport,housing,housing_general,Illegal Carport,commercial gooseneck trailer is parked in the ...
1062195,148768,SEECLICKFIX_248166,Big Lake MN,2018-03-14T17:18:00-04:00,NaN,junk/blight,environment,environment_dumping,Junk/Blight,There is a treadmill dishwasher refrigerator c...
1066022,152595,SEECLICKFIX_253599,Big Lake MN,2018-02-27T16:05:25-05:00,NaN,other,governance,governance_general,Danger,This house was finally torn down a couple of w...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1060635,147208,SEECLICKFIX_245977,Snowcrew,2018-03-21T09:48:40-04:00,NaN,snow shoveling assistance - volunteer request,street,street_slippery,Snow Shoveling Assistance - Volunteer Request,We need help shoveling a small portion of our ...
1076075,162648,SEECLICKFIX_268385,Snowcrew,2018-01-04T16:22:34-05:00,NaN,snow shoveling assistance - volunteer request,street,street_slippery,Snow Shoveling Assistance - Volunteer Request,Assistance shoveling walkway and front stairs
1076083,162656,SEECLICKFIX_268394,Snowcrew,2018-01-04T15:36:44-05:00,NaN,snow shoveling assistance - volunteer request,street,street_slippery,Snow Shoveling Assistance - Volunteer Request,Older women in need of help shoveling

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1062552,149125,SEECLICKFIX_248669,Atlantic County Utilities Authority - Ventnor ...,2018-03-13T14:27:21-04:00,NaN,litter issue,environment,environment_litter,Litter Issue,People (I think from out-of-town) have repeate...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1063121,149694,SEECLICKFIX_249450,Town of Monson,2018-03-11T00:32:30-05:00,NaN,other,governance,governance_general,Other,NaN
1081275,167848,SEECLICKFIX_275872,Town of Monson,2017-11-20T10:29:31-05:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,Child's road street sign is missing.
1081277,167850,SEECLICKFIX_275874,Town of Monson,2017-11-20T10:27:48-05:00,NaN,traffic or street sign issue,street,street_urgent_repair,Traffic or Street Sign Issue,Blanchard extension and wales road street sign...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1063482,150055,SEECLICKFIX_249985,Narberth Borough,2018-03-09T08:31:54-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Sidewalk not cleared
1076576,163149,SEECLICKFIX_269093,Narberth Borough,2017-12-31T12:37:15-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Snow not cleared at all. No salt put down eit...
1079380,165953,SEECLICKFIX_273173,Narberth Borough,2017-12-05T10:15:43-05:00,NaN,streets,street,street_general,Noisy Manhole Cover,Manhole Cover that was fixed last year is agai...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1063837,150410,SEECLICKFIX_250499,HMS: Tennis Court,2018-03-07T22:06:42-05:00,NaN,tennis court lighting / timer,governance,governance_parks_and_rec,Tennis Court Lighting / Timer,Three lights are no longer working
1117665,204238,SEECLICKFIX_325731,HMS: Tennis Court,2017-04-20T21:14:55-04:00,NaN,tennis court lighting / timer,governance,governance_parks_and_rec,Tennis Court Lighting / Timer,Court 5/6 light is not working.
1126066,212639,SEECLICKFIX_337237,HMS: Tennis Court,2017-02-28T09:18:39-05:00,NaN,tennis court lighting / timer,governance,governance_parks_and_rec,Tennis Court Lighting / Timer,several light bulbs are out on the tennis floo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1072490,159063,SEECLICKFIX_263237,Farmington,2018-01-26T10:16:47-05:00,NaN,snow and ice removal,street,street_slippery,Snow and Ice Removal,This street has been plowed a couple times thi...
1072629,159202,SEECLICKFIX_263441,Farmington,2018-01-25T13:33:53-05:00,NaN,snow and ice removal,street,street_slippery,Snow and Ice Removal,Road needs plowed
1072630,159203,SEECLICKFIX_263443,Farmington,2018-01-25T13:33:53-05:00,NaN,snow and ice removal,street,street_slippery,Snow and Ice Removal,Road needs plowed

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1072620,159193,SEECLICKFIX_263430,Loveland,2018-01-25T13:52:14-05:00,NaN,pothole,street,street_repair,Metal Plate,There is a metal plate on the North Side of th...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1072962,159535,SEECLICKFIX_263970,Chatham MA,2018-01-23T17:52:40-05:00,NaN,water or sewer issues,infrastructure,infrastructure_water,Water or Sewer Issues,Warning light and siren going off outside the ...
1086579,173152,SEECLICKFIX_283416,Chatham MA,2017-10-16T13:59:52-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,Street light on all day.
1095056,181629,SEECLICKFIX_295350,Chatham MA,2017-08-24T01:06:40-04:00,NaN,tree issue,environment,environment_overgrowth,Tree Issue,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1072965,159538,SEECLICKFIX_263976,Montpelier VT,2018-01-23T17:23:46-05:00,NaN,pothole,street,street_repair,Pothole,2 massive potholes that have been here for abo...
1093673,180246,SEECLICKFIX_293402,Montpelier VT,2017-09-01T10:08:44-04:00,NaN,other,governance,governance_general,done! my coworker said it has been done,I wondered if you could have someone go to the...
1128718,215291,SEECLICKFIX_341115,Montpelier VT,2017-02-07T13:36:14-05:00,NaN,other,governance,governance_general,long dip pothole,On rt 12 just north of Putnamville there is a ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1073527,160100,SEECLICKFIX_264794,Clark County,2018-01-20T10:16:16-05:00,NaN,other,governance,governance_general,Street Light Out,Street light goes on and off
1073883,160456,SEECLICKFIX_265344,Clark County,2018-01-17T17:04:42-05:00,NaN,other,governance,governance_general,Other,This is a very dangerous intersection. There n...
1073886,160459,SEECLICKFIX_265355,Clark County,2018-01-17T16:14:40-05:00,NaN,other,governance,governance_general,Other,At present this East West signal on Warm Sprin...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1073911,160484,SEECLICKFIX_265391,Town of Middletown,2018-01-17T14:04:38-05:00,NaN,pothole,street,street_repair,Pothole,I''m not sure whether this is a city problem o...
1200250,286823,SEECLICKFIX_430267,Town of Middletown,2016-02-25T14:49:22-05:00,NaN,street signs,governance,governance_signage,Street Signs,Hi I recently requested new street signs to be...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1073975,160548,SEECLICKFIX_265489,Tres de Febrero,2018-01-16T22:18:05-05:00,NaN,other,governance,governance_general,RUIDOS MOLESTOS,EN EL EDIFICIO DE LA PILETA CLIMATIZADA \LA AG...
1073980,160553,SEECLICKFIX_265495,Tres de Febrero,2018-01-16T21:50:35-05:00,NaN,other,governance,governance_general,Colectivo 53 en camino hacia Palomar paro c to...,Sin informar a los pasajeros q viajabamos el c...
1090999,177572,SEECLICKFIX_289736,Tres de Febrero,2017-09-17T15:26:42-04:00,NaN,other,governance,governance_general,#HermanoEnLaCalle,Ayuda urgente!!

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1074347,160920,SEECLICKFIX_266022,Chelsea MI,2018-01-14T18:37:01-05:00,NaN,other,governance,governance_general,Pot hole,Pot hole south bound lane north of pierce
1107204,193777,SEECLICKFIX_311739,Chelsea MI,2017-06-16T16:37:10-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,The push button on the west side of the crossw...
1110097,196670,SEECLICKFIX_315646,Chelsea MI,2017-05-31T12:53:53-04:00,NaN,street lights,street,street_lighting,Street light is out,Noticed about a week ago that street light doe...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1074426,160999,SEECLICKFIX_266151,Los Angeles,2018-01-13T21:30:14-05:00,NaN,street repair,street,street_repair,Pothole,Giant pothole on Vesper Avenue.
1074896,161469,SEECLICKFIX_266832,Los Angeles,2018-01-10T18:24:38-05:00,NaN,other,governance,governance_general,Graffitti,Graffiti on apt complex
1074897,161470,SEECLICKFIX_266833,Los Angeles,2018-01-10T18:23:59-05:00,NaN,other,governance,governance_general,Graffiti on Rec Center,Graffiti on Rec Center

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1076592,163165,SEECLICKFIX_269122,Doraville,2017-12-30T21:32:55-05:00,NaN,pothole,street,street_repair,Pothole,Huge pothole and very degraded pavement on Lon...
1110990,197563,SEECLICKFIX_316825,Doraville,2017-05-26T01:30:00-04:00,NaN,pothole,street,street_repair,Deep destructive pothole,This pothole in on us 23 south Buford hwy in t...
1112656,199229,SEECLICKFIX_319068,Doraville,2017-05-16T22:20:48-04:00,NaN,pothole,street,street_repair,Potholes on northbound PIB before Tilly Mill R...,There are a series of potholes on the northbou...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1076856,163429,SEECLICKFIX_269483,Greater Rincon Hill CBD,2017-12-28T14:41:04-05:00,NaN,graffiti/sticker removal,vandalism,vandalism_graffiti,Graffiti/Sticker Removal,NaN
1076857,163430,SEECLICKFIX_269484,Greater Rincon Hill CBD,2017-12-28T14:38:45-05:00,NaN,steam cleaning request (private),street,street_cleaning,Steam Cleaning Request (Private),NaN
1076858,163431,SEECLICKFIX_269486,Greater Rincon Hill CBD,2017-12-28T14:37:08-05:00,NaN,graffiti/sticker removal,vandalism,vandalism_graffiti,Graffiti/Sticker Removal,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1076980,163553,SEECLICKFIX_269671,CCCBD,2017-12-27T14:19:55-05:00,NaN,illegal drug use,public_order,publicorder_drug_activity,Illegal Drug Use,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1077368,163941,SEECLICKFIX_270230,Mt. Laurel Township,2017-12-22T13:54:35-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,the sidewalks in front of this vacant home on ...
1080111,166684,SEECLICKFIX_274240,Mt. Laurel Township,2017-11-29T13:35:36-05:00,NaN,pothole,street,street_repair,Pothole,looks like sharp shrapnel stuck in the road fr...
1080113,166686,SEECLICKFIX_274242,Mt. Laurel Township,2017-11-29T13:35:36-05:00,NaN,pothole,street,street_repair,Pothole,looks like sharp shrapnel stuck in the road fr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1078955,165528,SEECLICKFIX_272547,HART,2017-12-08T10:09:53-05:00,NaN,ztrash at bus stop,environment,environment_litter,Trash at bus stop N 30th St and E Annie Tampa,Forwarded from City of Tampa Customer Service...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1079651,166224,SEECLICKFIX_273563,City of Linwood,2017-12-03T10:48:43-05:00,NaN,code enforcement,planning,planning_general,Code Enforcement,NaN
1085813,172386,SEECLICKFIX_282297,City of Linwood,2017-10-20T20:06:59-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,NaN
1085902,172475,SEECLICKFIX_282437,City of Linwood,2017-10-20T10:11:10-04:00,NaN,code enforcement,planning,planning_general,Code Enforcement,BASKETBALL STAND HAS BEEN LYING IN THE FRONT ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1079933,166506,SEECLICKFIX_273972,NYC District 5,2017-11-30T15:47:20-05:00,NaN,street repair,street,street_repair,Street Repair,Water is leaking from the road.
1084504,171077,SEECLICKFIX_280411,NYC District 5,2017-10-30T09:50:57-04:00,NaN,other,governance,governance_general,Other,Every Saturday and Sunday morning from 8am to ...
1087182,173755,SEECLICKFIX_284276,NYC District 5,2017-10-12T09:46:21-04:00,NaN,other,governance,governance_general,Traffic light,Fix traffic light at this intersection - it is...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1080788,167361,SEECLICKFIX_275189,City of Greensboro,2017-11-23T17:20:22-05:00,NaN,abandoned motor vehicle,environment,environment_abandoned_vehicle,Abandoned Motor Vehicle,Wrecked car has been there for over two weeks.
1081059,167632,SEECLICKFIX_275571,City of Greensboro,2017-11-21T12:45:09-05:00,NaN,dead animal pickup,environment,environment_dead_animal,Dead Animal Pickup,NaN
1081349,167922,SEECLICKFIX_275980,City of Greensboro,2017-11-19T16:44:05-05:00,NaN,other,governance,governance_general,Osprey Trail maintenance,There are several mile marker signs off the tr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1080811,167384,SEECLICKFIX_275225,Holden MA,2017-11-23T09:41:33-05:00,NaN,pothole,street,street_repair,Pothole,NaN
1083452,170025,SEECLICKFIX_278967,Holden MA,2017-11-04T21:50:01-04:00,NaN,traffic signal issue,street,street_urgent_repair,Traffic Signal Issue,Would anyone replace the flashing signals and ...
1085730,172303,SEECLICKFIX_282180,Holden MA,2017-10-21T20:45:46-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,Pole #1 on Pilgrim. Light is out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1082256,168829,SEECLICKFIX_277292,Charleston IL,2017-11-12T21:06:43-05:00,NaN,other,governance,governance_general,Other,I noticed a couple of soldiers signs that were...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1082813,169386,SEECLICKFIX_278091,Middletown CT,2017-11-08T08:37:17-05:00,NaN,other,governance,governance_general,Other,Since there is no category for 'potholes' I am...
1095406,181979,SEECLICKFIX_295822,Middletown CT,2017-08-22T12:22:55-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,mattress on train tracks
1096383,182956,SEECLICKFIX_297150,Middletown CT,2017-08-16T18:14:40-04:00,NaN,other,governance,governance_general,Other,The street light on Washington at the intersec...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1083933,170506,SEECLICKFIX_279627,City of Schertz,2017-11-02T09:18:27-04:00,NaN,street lights,street,street_lighting,Street Lights,The street light on the corner of Meadow Creek...
1151108,237681,SEECLICKFIX_369623,City of Schertz,2016-09-14T23:42:43-04:00,NaN,street lights,street,street_lighting,street light,Street light in front of home goes out and the...
1157440,244013,SEECLICKFIX_377167,City of Schertz,2016-08-26T18:30:36-04:00,NaN,street lights,street,street_lighting,NaN,Street Light is out.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1084152,170725,SEECLICKFIX_279919,City of Natchez,2017-11-01T09:53:33-04:00,NaN,pothole,street,street_repair,Pothole,Pothole in front of my house cause a Trick or ...
1209356,295929,SEECLICKFIX_444177,City of Natchez,2015-11-11T14:24:01-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Broken sidewalk
1209357,295930,SEECLICKFIX_444178,City of Natchez,2015-11-11T14:14:01-05:00,NaN,flooding,street,street_drainage,Flooding,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1084341,170914,SEECLICKFIX_280198,Research Triangle High School,2017-10-31T07:40:35-04:00,NaN,other,governance,governance_general,Other,The carpet tiles are starting to peel up in tw...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1084882,171455,SEECLICKFIX_280953,City of Forest Hills,2017-10-27T09:32:33-04:00,NaN,fallen tree or falling tree,environment,environment_overgrowth,Fallen Tree or Falling Tree,We live at 1431 Tyne Blvd. There is a tree ac...
1087566,174139,SEECLICKFIX_284796,City of Forest Hills,2017-10-10T11:08:10-04:00,NaN,other,governance,governance_general,Missing keys,NaN
1088984,175557,SEECLICKFIX_286822,City of Forest Hills,2017-09-30T14:35:41-04:00,NaN,overgrown vegetation,environment,environment_overgrowth,Overgrown Vegetation,Stop line on Dresden is too far back from Saxo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1085588,172161,SEECLICKFIX_281972,Birmingham MI,2017-10-23T11:17:34-04:00,NaN,other,governance,governance_general,Post to Neighbors,thank you for quick response and service
1098184,184757,SEECLICKFIX_299497,Birmingham MI,2017-08-07T18:51:04-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Tripped on row
1098185,184758,SEECLICKFIX_299498,Birmingham MI,2017-08-07T18:51:04-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Tripped on row

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1086969,173542,SEECLICKFIX_283968,Bryan TX,2017-10-13T14:21:30-04:00,NaN,pothole,street,street_repair,Pothole,Pothole on Cambridge where it T's into Barak. ...
1091953,178526,SEECLICKFIX_291025,Bryan TX,2017-09-12T09:27:39-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Licences plate # JKN 6820 it is an older mode...
1097270,183843,SEECLICKFIX_298341,Bryan TX,2017-08-11T20:43:24-04:00,NaN,other,governance,governance_general,Park needs some work done,The yellow bucket on splash pad is broken conc...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1088515,175088,SEECLICKFIX_286104,City of Pharr,2017-10-04T09:00:41-04:00,NaN,other,governance,governance_general,Mosquitoes out of control. No app for pharr to...,Too many mosquitos in this area. The city of p...
1128465,215038,SEECLICKFIX_340731,City of Pharr,2017-02-09T15:03:48-05:00,NaN,other,governance,governance_general,WATER & SEWER,W/O#5445413 FROM THE INTERSECTIONS OF STATE HW...
1134060,220633,SEECLICKFIX_348601,City of Pharr,2016-12-16T17:44:25-05:00,NaN,other,governance,governance_general,Graffiti on concrete in underpass.,Please clean up the graffiti in the underpass ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1089074,175647,SEECLICKFIX_286945,VTrans District 5,2017-09-29T16:44:00-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,When traveling east or west on Route 2 there i...
1090338,176911,SEECLICKFIX_288738,VTrans District 5,2017-09-21T13:56:29-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,Please turn on the school warning flashing lights
1090420,176993,SEECLICKFIX_288854,VTrans District 5,2017-09-21T07:44:58-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal Issues Off-Ramp,This morning around 7:20am the light at the bo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1089854,176427,SEECLICKFIX_288028,Duluth GA,2017-09-25T13:20:19-04:00,NaN,other,governance,governance_general,Traffic Light,The traffic light at the intersection of Club...
1122626,209199,SEECLICKFIX_332523,Duluth GA,2017-03-24T10:09:21-04:00,NaN,other,governance,governance_general,Other,Sink Hole between house

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1090247,176820,SEECLICKFIX_288598,PalmettoPride,2017-09-22T09:13:17-04:00,NaN,report a litter hotspot,environment,environment_litter,Report a Litter Hotspot,Lots of roadside trash is along Saluda trail a...
1090395,176968,SEECLICKFIX_288819,PalmettoPride,2017-09-21T09:38:43-04:00,NaN,other litter/beautification concerns,environment,environment_litter,POTHOLE,HUGE POTHOLE RIGHT AT FORREST HILLS PLANT ENTR...
1090922,177495,SEECLICKFIX_289613,PalmettoPride,2017-09-18T09:43:18-04:00,NaN,other litter/beautification concerns,environment,environment_litter,Other Litter/Beautification Concerns,the streetlight in front of 218 viking lane is...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1090328,176901,SEECLICKFIX_288721,East Lansing MI,2017-09-21T14:53:16-04:00,NaN,pothole,street,street_repair,Pothole Minefield,As a commuter who drives back and forth on Sag...
1097430,184003,SEECLICKFIX_298536,East Lansing MI,2017-08-11T08:56:42-04:00,NaN,pothole,street,street_repair,Pothole,rought road EB between Abbott and Hagadorn con...
1102760,189333,SEECLICKFIX_305704,East Lansing MI,2017-07-13T07:01:27-04:00,NaN,other,governance,governance_general,Curb side damage,Damage/Deteriation to street-side curb [north ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1091781,178354,SEECLICKFIX_290801,Sunland Park,2017-09-12T17:01:52-04:00,NaN,pothole,street,street_repair,Pothole,There are 2 or 3 very large and very deep pot ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1094378,180951,SEECLICKFIX_294385,CMCBD,2017-08-28T13:50:03-04:00,NaN,311 called,governance,governance_general,311 Called,-wheelchair bicycle parts shopping cart and ...
1094584,181157,SEECLICKFIX_294693,CMCBD,2017-08-27T10:45:44-04:00,NaN,311 called,governance,governance_general,311 Called,NaN
1095770,182343,SEECLICKFIX_296310,CMCBD,2017-08-20T15:51:11-04:00,NaN,311 called,governance,governance_general,311 Called,Broken furniture Julia and minna

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1094603,181176,SEECLICKFIX_294718,VTrans District 7,2017-08-27T07:10:38-04:00,NaN,traffic signal,street,street_urgent_repair,Traffic Signal,Illogical display

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1096659,183232,SEECLICKFIX_297527,City of Palm Beach Gardens,2017-08-15T14:31:45-04:00,NaN,pothole,street,street_repair,Pothole,There is a cluster of potholes in the East bou...
1134334,220907,SEECLICKFIX_348969,City of Palm Beach Gardens,2016-12-14T10:31:07-05:00,NaN,other,governance,governance_general,I -95 and 45 Th intersection,Garbage left behind by homeless

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1098846,185419,SEECLICKFIX_300422,Brantford,2017-08-03T14:55:47-04:00,NaN,curbs & sidewalks,street,street_sidewalk,Curbs & Sidewalks,There's a pothole right in the middle of Uplan...
1224334,310907,SEECLICKFIX_466620,Brantford,2015-04-24T11:33:36-04:00,NaN,curbs & sidewalks,street,street_sidewalk,Curbs & Sidewalks,There is pothole on the road before driveway r...
1228130,314703,SEECLICKFIX_474556,Brantford,2015-02-16T08:51:08-05:00,NaN,traffic lights,street,street_urgent_repair,Traffic Lights,Why can we not get a roundabout in some areas ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1099546,186119,SEECLICKFIX_301418,St. Johns,2017-07-31T09:20:54-04:00,NaN,drainage/flooding issue,street,street_drainage,Drainage/Flooding Issue,culvert plugged which causes water to flood ya...
1114857,201430,SEECLICKFIX_322064,St. Johns,2017-05-03T23:49:01-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,multiple broken down vehicles stored in a vaca...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1099864,186437,SEECLICKFIX_301870,Russellville AR,2017-07-28T13:05:10-04:00,NaN,street lights,street,street_lighting,Street Lights,street light is out and missing globe
1190149,276722,SEECLICKFIX_416768,Russellville AR,2016-05-04T00:21:47-04:00,NaN,street lights,street,street_lighting,Syreet light out,Street light out
1198173,284746,SEECLICKFIX_427427,Russellville AR,2016-03-14T11:49:54-04:00,NaN,pothole,street,street_repair,Pothole,test issue please ignore.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1100268,186841,SEECLICKFIX_302396,West Warwick RI,2017-07-26T13:38:58-04:00,NaN,pothole,street,street_repair,Pothole,several potholes on the West Warwick end of Ne...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1101209,187782,SEECLICKFIX_303662,VTrans District 3,2017-07-21T10:25:16-04:00,NaN,vegetation,environment,environment_overgrowth,Dead Trees,All of the trees in this area are dead and wil...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1102084,188657,SEECLICKFIX_304818,City of Placentia,2017-07-17T10:06:38-04:00,NaN,pothole,street,street_repair,Pothole,Huge pot hole on Sherwood Ave in between Cambr...
1138522,225095,SEECLICKFIX_354867,City of Placentia,2016-10-29T14:31:34-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on block wall

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1105314,191887,SEECLICKFIX_309076,SeeClickFix service requests are no longer mon...,2017-06-28T19:22:00-04:00,NaN,other,governance,governance_general,Speed limit,Speed limit between 119 Washington st & 173 it...
1105856,192429,SEECLICKFIX_309823,SeeClickFix service requests are no longer mon...,2017-06-26T08:17:14-04:00,NaN,other,governance,governance_general,Water/sewer,Drain seems to be cover in dirt and debris
1105915,192488,SEECLICKFIX_309909,SeeClickFix service requests are no longer mon...,2017-06-25T16:27:11-04:00,NaN,other,governance,governance_general,Littering & Public Drunkenness,Constant littering and public drunkenness thro...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1105346,191919,SEECLICKFIX_309113,Poquoson,2017-06-28T15:54:25-04:00,NaN,other,governance,governance_general,Wood steps floating near red buoy next to duck...,NaN
1207903,294476,SEECLICKFIX_441962,Poquoson,2015-12-04T14:25:36-05:00,NaN,other,governance,governance_general,street is flooding,intersection is impassable.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1106979,193552,SEECLICKFIX_311410,VTrans District 8,2017-06-19T08:42:50-04:00,NaN,vegetation,environment,environment_overgrowth,Vegetation,At the intersection from 1116 Main St. (Rt 104...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1107182,193755,SEECLICKFIX_311710,Norwell MA,2017-06-16T19:55:25-04:00,NaN,pothole,street,street_repair,Pothole,Significant number of potholes in both east an...
1112932,199505,SEECLICKFIX_319438,Norwell MA,2017-05-15T16:01:43-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1114348,200921,SEECLICKFIX_321375,Norwell MA,2017-05-07T12:20:27-04:00,NaN,pothole,street,street_repair,Pothole,This pothole has been here for several years a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1107317,193890,SEECLICKFIX_311894,Congers,2017-06-16T08:05:26-04:00,NaN,pothole,street,street_repair,Pothole,2' feel sinkhole at storm drain on corner of N...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1107352,193925,SEECLICKFIX_311933,Power Inn Alliance PBID,2017-06-15T19:53:03-04:00,NaN,homeless encampment,public_order,publicorder_general,Homeless Encampment,Fernando. Makeshift camp behind Subway. Possi...
1107354,193927,SEECLICKFIX_311935,Power Inn Alliance PBID,2017-06-15T19:43:00-04:00,NaN,homeless encampment,public_order,publicorder_general,Homeless Encampment,Fernando. Makeshift tent shelter at the end ...
1107357,193930,SEECLICKFIX_311938,Power Inn Alliance PBID,2017-06-15T19:34:37-04:00,NaN,homeless encampment,public_order,publicorder_general,Homeless Encampment,Homeless at Thunderdome. Reported by Fernando.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1108775,195348,SEECLICKFIX_313934,Clawson MI,2017-06-07T07:19:03-04:00,NaN,parks,governance,governance_parks_and_rec,Parks,Why so many sharp weeds at park in the area wh...
1108916,195489,SEECLICKFIX_314119,Clawson MI,2017-06-06T13:01:44-04:00,NaN,other,governance,governance_general,NAPA auto parts,The employees from NAPA auto parts are using e...
1111718,198291,SEECLICKFIX_317833,Clawson MI,2017-05-22T11:31:20-04:00,NaN,street light issue,street,street_lighting,Street Light Issue,There needs to be a street light put on Redrut...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1110039,196612,SEECLICKFIX_315576,City of Yellowknife,2017-05-31T15:50:59-04:00,NaN,road maintenance,street,street_general,Road Maintenance,It baffle's my mind how the City of Yellowknif...
1110951,197524,SEECLICKFIX_316770,City of Yellowknife,2017-05-26T10:08:08-04:00,NaN,park maintenance,governance,governance_parks_and_rec,Park Maintenance,Someone dumped bags of garbage- please see pho...
1110952,197525,SEECLICKFIX_316771,City of Yellowknife,2017-05-26T10:07:48-04:00,NaN,park maintenance,governance,governance_parks_and_rec,Park Maintenance,Someone dumped bags of garbage- please see pho...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1113073,199646,SEECLICKFIX_319614,Wauwatosa WI (DEMO),2017-05-15T07:18:13-04:00,NaN,streets,street,street_general,Streets,Potholes and rough st
1113617,200190,SEECLICKFIX_320348,Wauwatosa WI (DEMO),2017-05-11T07:19:37-04:00,NaN,streets,street,street_general,Streets,Rough and uneven st
1114248,200821,SEECLICKFIX_321234,Wauwatosa WI (DEMO),2017-05-08T07:20:29-04:00,NaN,streets,street,street_general,Streets,Terribly bumpy and potholes

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1113432,200005,SEECLICKFIX_320093,Brandon City of Manitoba,2017-05-12T06:00:40-04:00,NaN,pothole,street,street_repair,Pothole,The street in the back of Cornell Bay once aga...
1185063,271636,SEECLICKFIX_410577,Brandon City of Manitoba,2016-05-23T08:00:44-04:00,NaN,pothole,street,street_repair,Pothole,At the est end of cornell bay the road has det...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1113732,200305,SEECLICKFIX_320506,League City TX (DEMO),2017-05-10T13:25:28-04:00,NaN,other,governance,governance_general,Other,Large garbage pickup on 416 harbor dr
1123678,210251,SEECLICKFIX_333968,League City TX (DEMO),2017-03-17T09:20:39-04:00,NaN,pothole,street,street_repair,Pothole,There is a pothole at the end of our driveway....
1157461,244034,SEECLICKFIX_377189,League City TX (DEMO),2016-08-26T17:15:20-04:00,NaN,street signs,governance,governance_signage,Street Signs,The on ramp from Dixie Farm Road to I-45 is ex...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1113898,200471,SEECLICKFIX_320741,Rochester,2017-05-09T16:20:58-04:00,NaN,pothole,street,street_repair,Pothole,DEEP hole
1113899,200472,SEECLICKFIX_320742,Rochester,2017-05-09T16:18:22-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1117024,203597,SEECLICKFIX_324889,Rochester,2017-04-24T12:21:20-04:00,NaN,pothole,street,street_repair,Pothole,The potholes on East Ave in Brighton are causi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1114300,200873,SEECLICKFIX_321314,Precinct 3,2017-05-07T18:12:02-04:00,NaN,other,governance,governance_general,Other,Boat house is falling into the lake and I have...
1114301,200874,SEECLICKFIX_321315,Precinct 3,2017-05-07T18:10:12-04:00,NaN,other,governance,governance_general,Other,This boat needs to be taken out of the water t...
1124720,211293,SEECLICKFIX_335379,Precinct 3,2017-03-09T10:06:07-05:00,NaN,other,governance,governance_general,Other,More photos of the issue of trash that I just ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1114431,201004,SEECLICKFIX_321492,King County Parks,2017-05-06T14:32:19-04:00,NaN,tree down,environment,environment_overgrowth,Tree with white flowers is down,The tree with white flowers in the garden next...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1114551,201124,SEECLICKFIX_321652,Utica NY (Demo),2017-05-05T14:25:54-04:00,NaN,streets,street,street_general,Pothole,There is a large pothole in the street right a...
1126549,213122,SEECLICKFIX_337904,Utica NY (Demo),2017-02-24T14:04:18-05:00,NaN,streets,street,street_general,Pothole Weaver St.,Deep potholes as depicted in pictures includin...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1116023,202596,SEECLICKFIX_323628,Calhoun County,2017-04-27T16:50:58-04:00,NaN,potholes,street,street_repair,Potholes,NaN
1116024,202597,SEECLICKFIX_323629,Calhoun County,2017-04-27T16:50:42-04:00,NaN,potholes,street,street_repair,Potholes,NaN
1116025,202598,SEECLICKFIX_323630,Calhoun County,2017-04-27T16:50:08-04:00,NaN,potholes,street,street_repair,Potholes,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1116065,202638,SEECLICKFIX_323681,Town of Ware,2017-04-27T13:42:43-04:00,NaN,other,governance,governance_general,Other,Street curbs that the snow plows destroyed and...
1119760,206333,SEECLICKFIX_328508,Town of Ware,2017-04-10T12:39:44-04:00,NaN,street light,street,street_lighting,Street Light,NaN
1127058,213631,SEECLICKFIX_338667,Town of Ware,2017-02-21T10:45:04-05:00,NaN,street light,street,street_lighting,Street Light,Half the street is pitch black

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1116139,202712,SEECLICKFIX_323775,Nantucket MA,2017-04-27T10:46:26-04:00,NaN,pothole,street,street_repair,Pothole,Mt Vernon. Big!
1117687,204260,SEECLICKFIX_325763,Nantucket MA,2017-04-20T19:45:27-04:00,NaN,pothole,street,street_repair,Pothole,Pothole has been guarded by a barricade for mo...
1137108,223681,SEECLICKFIX_352867,Nantucket MA,2016-11-13T15:53:49-05:00,NaN,pothole,street,street_repair,Need repair,Pavement breaking up

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1116733,203306,SEECLICKFIX_324498,City of Corpus Christi,2017-04-25T13:54:39-04:00,NaN,pothole,street,street_repair,Pothole,There are numerous potholes running from Archd...
1119293,205866,SEECLICKFIX_327868,City of Corpus Christi,2017-04-12T13:55:49-04:00,NaN,street lights,street,street_lighting,Street Lights,Light on the Cul de Sac has been out and is ca...
1154041,240614,SEECLICKFIX_373066,City of Corpus Christi,2016-09-06T17:15:32-04:00,NaN,pothole,street,street_repair,Broken Pavement/Protruded Concrete/Pot Holes,The cul-de-sac of 1122 Green Leaf has been in ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1118309,204882,SEECLICKFIX_326561,Lea County,2017-04-18T11:07:43-04:00,NaN,other,governance,governance_general,Other,NaN
1119000,205573,SEECLICKFIX_327490,Lea County,2017-04-13T18:28:09-04:00,NaN,other,governance,governance_general,Other,Broken pole across the new Jal Elementary scho...
1146635,233208,SEECLICKFIX_364410,Lea County,2016-09-28T12:04:11-04:00,NaN,other,governance,governance_general,Post to neighbors,Pole broke at base result of being hit by vehi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1118818,205391,SEECLICKFIX_327232,Bahamas Water & Sewerage Corporation,2017-04-15T05:50:08-04:00,NaN,other,governance,governance_general,Potter's Cay Bathroom,It's dilapidated.
1122376,208949,SEECLICKFIX_332151,Bahamas Water & Sewerage Corporation,2017-03-26T12:56:06-04:00,NaN,other,governance,governance_general,Illegal Dumping,Lots of bulk waste dumped at Stoke's Beach.
1122464,209037,SEECLICKFIX_332270,Bahamas Water & Sewerage Corporation,2017-03-25T13:54:24-04:00,NaN,other,governance,governance_general,Illegal Dumping,This has been an issue on Leeward Road for yea...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1118945,205518,SEECLICKFIX_327413,Côte Saint Luc,2017-04-14T09:48:03-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti
1197420,283993,SEECLICKFIX_426382,Côte Saint Luc,2016-03-20T19:29:57-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffitis sur les bancs et les poubelles du parc.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1122226,208799,SEECLICKFIX_331945,City of Avon,2017-03-27T11:23:27-04:00,NaN,pothole,street,street_repair,POTHOLE,There is a HUGE pothole at the stopsign on MIL...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1124956,211529,SEECLICKFIX_335707,Suisun City,2017-03-07T17:18:25-05:00,NaN,other,governance,governance_general,Graffiti,The dumpsters on Kellogg Street have been vand...
1125007,211580,SEECLICKFIX_335768,Suisun City,2017-03-07T12:52:38-05:00,NaN,other,governance,governance_general,Other,The dumpster on Kellogg Street has been tagged...
1148078,234651,SEECLICKFIX_366046,Suisun City,2016-09-24T11:40:49-04:00,NaN,street lights,street,street_lighting,Street light Glitch,Traffic light on highway12 and Marina drive in...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1125965,212538,SEECLICKFIX_337091,Cobb County,2017-02-28T17:59:55-05:00,NaN,street lights,street,street_lighting,Street Lights,The left turn lane light from Sandy Plains ont...
1126536,213109,SEECLICKFIX_337882,Cobb County,2017-02-24T15:08:05-05:00,NaN,pothole,street,street_repair,Pothole,HUGE 3 foot by 3 foot by 6 inch deep pothole o...
1126553,213126,SEECLICKFIX_337910,Cobb County,2017-02-24T13:27:56-05:00,NaN,pothole,street,street_repair,Pothole,There is a pothole in the middle of the road (...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1127108,213681,SEECLICKFIX_338739,Sunnyside WA,2017-02-20T23:03:10-05:00,NaN,street lights,street,street_lighting,Light out on Light Post,There is a light on the Street light post righ...
1208045,294618,SEECLICKFIX_442188,Sunnyside WA,2015-12-02T13:27:00-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Street Lights,Light is out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1128173,214746,SEECLICKFIX_340322,Monroe GA,2017-02-12T09:44:01-05:00,NaN,other,governance,governance_general,Other,Hole next to sidewalk at City hall
1130372,216945,SEECLICKFIX_343434,Monroe GA,2017-01-24T14:05:12-05:00,NaN,abandoned vehicles,environment,environment_abandoned_vehicle,Abandoned Vehicles,These two vehicles are on blocks undrivable pr...
1133692,220265,SEECLICKFIX_348051,Monroe GA,2016-12-21T15:05:40-05:00,NaN,other,governance,governance_general,Other,Universal Rundal gates and exterior door have ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1128590,215163,SEECLICKFIX_340928,City of Blaine,2017-02-08T10:35:55-05:00,NaN,street light,street,street_lighting,Street Light,"The Light at the end of the \new\"" part of 129..."
1151886,238459,SEECLICKFIX_370525,City of Blaine,2016-09-12T20:16:34-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti destruction of property,Someone cut the swings in half in the park

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1129594,216167,SEECLICKFIX_342304,City of Gulfport,2017-01-31T12:27:30-05:00,NaN,other,governance,governance_general,Bees in house,Noticed large colony of honey bees in the open...
1135144,221717,SEECLICKFIX_350123,City of Gulfport,2016-12-06T10:39:05-05:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned vehicle,5510 13th Ave S is filled with junk and inoper...
1138998,225571,SEECLICKFIX_355547,City of Gulfport,2016-10-24T19:11:10-04:00,NaN,other,governance,governance_general,Other,There are numerous inoperable vehicles on the ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1130514,217087,SEECLICKFIX_343635,City of Turlock,2017-01-23T13:55:35-05:00,NaN,other,governance,governance_general,Large pothole located on Taylor Rd,Just nearly avoided a large pothole heading on...
1227548,314121,SEECLICKFIX_473585,City of Turlock,2015-03-03T12:36:12-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1130672,217245,SEECLICKFIX_343864,Everett MA,2017-01-21T20:57:51-05:00,NaN,potholes/road hazards,street,street_repair,Potholes/Road Hazards,large deep pothole
1130817,217390,SEECLICKFIX_344074,Everett MA,2017-01-20T07:00:10-05:00,NaN,other,governance,governance_general,Loud daily honking,The school bus that comes to this house lays o...
1130937,217510,SEECLICKFIX_344239,Everett MA,2017-01-19T07:53:46-05:00,NaN,other,governance,governance_general,Hole in street rocks are everywhere,Hole on street rocks are everywhere they are b...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1131037,217610,SEECLICKFIX_344378,New Haven LCI,2017-01-18T12:19:52-05:00,NaN,blight,environment,environment_general,Ripped Up Playground - Piles of Turfing Left B...,The playground at the former daycare center wa...
1139270,225843,SEECLICKFIX_355900,New Haven LCI,2016-10-21T15:32:15-04:00,NaN,blight,environment,environment_general,Public Space Streets and Drains,Large Rodents on grace street around the catch...
1192074,278647,SEECLICKFIX_419180,New Haven LCI,2016-04-25T11:48:49-04:00,NaN,blight,environment,environment_general,Empty Lot Filled With Garbage,There is an empty lot next to a resident's pro...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1131536,218109,SEECLICKFIX_345048,Mauritius Public Utilities,2017-01-13T16:04:34-05:00,NaN,electricity streetlight out,street,street_lighting,Electricity Streetlight Out,no light at night

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1132323,218896,SEECLICKFIX_346129,City of Taylor,2017-01-06T23:51:08-05:00,NaN,missed recycling pick up,environment,environment_recycling,Missed Recycling Pick Up,NaN
1132617,219190,SEECLICKFIX_346542,City of Taylor,2017-01-04T15:17:30-05:00,NaN,dead animal on road,street,street_roadkill,Dead Animal on Road,NaN
1132852,219425,SEECLICKFIX_346879,City of Taylor,2017-01-02T16:46:27-05:00,NaN,missed recycling pick up,environment,environment_recycling,Missed Recycling Pick Up,Missed recycling and trash pick up.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1132554,219127,SEECLICKFIX_346457,City of Murfreesboro,2017-01-04T23:17:21-05:00,NaN,other,governance,governance_general,Dangerous Curve on Rucker,There continue to be multiple accidents in thi...
1134815,221388,SEECLICKFIX_349672,City of Murfreesboro,2016-12-08T23:34:02-05:00,NaN,street lights,street,street_lighting,Street Lights,street lite at end of my driveway is out - I l...
1141414,227987,SEECLICKFIX_358385,City of Murfreesboro,2016-10-13T21:45:33-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Fixed,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1132572,219145,SEECLICKFIX_346481,City of Kyle,2017-01-04T19:45:27-05:00,NaN,street light,street,street_lighting,Street Light,NaN
1134601,221174,SEECLICKFIX_349375,City of Kyle,2016-12-11T19:41:49-05:00,NaN,street light,street,street_lighting,Street Light,NaN
1134930,221503,SEECLICKFIX_349834,City of Kyle,2016-12-07T20:45:58-05:00,NaN,street light,street,street_lighting,Street Light,Decorative lights are dual head and each light...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1132821,219394,SEECLICKFIX_346830,Macon Bibb County,2017-01-03T08:43:16-05:00,NaN,s-waste: garbage - cart replacement,environment,environment_garbage_collection,S-WASTE: Garbage - Cart Replacement,Customer is requesting a replacement cart

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1133800,220373,SEECLICKFIX_348221,City of Charlottesville,2016-12-20T13:37:04-05:00,NaN,other,governance,governance_general,Utility Billing Waste,The city is wasting a lot of money and resourc...
1154047,240620,SEECLICKFIX_373073,City of Charlottesville,2016-09-06T17:08:24-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Sidewalk cracked
1175854,262427,SEECLICKFIX_399253,City of Charlottesville,2016-06-26T11:45:34-04:00,NaN,other,governance,governance_general,tagging on bus stop,please remove the tagging from this bus stop

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1134305,220878,SEECLICKFIX_348934,Delray Beach,2016-12-14T13:29:39-05:00,NaN,street lights,street,street_lighting,Street Lights,The city (not FPL) poles are out on both stree...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1134804,221377,SEECLICKFIX_349642,City of Winona,2016-12-09T10:27:20-05:00,NaN,street maintenance,street,street_general,Street Maintenance,The street light on the corner of Carimona and...
1138574,225147,SEECLICKFIX_354937,City of Winona,2016-10-28T16:03:09-04:00,NaN,other,governance,governance_general,Tree service,City tree is dying. Barks and limbs are in bad...
1139040,225613,SEECLICKFIX_355605,City of Winona,2016-10-24T12:48:53-04:00,NaN,other,governance,governance_general,Other,On Sarnia street heading from East Lake Apartm...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1135123,221696,SEECLICKFIX_350095,City of Zephyrhills,2016-12-06T12:32:21-05:00,NaN,other,governance,governance_general,Salon sign blocking view of the one way street...,Salon sign blocking view of the one way street...
1135124,221697,SEECLICKFIX_350097,City of Zephyrhills,2016-12-06T12:27:19-05:00,NaN,other,governance,governance_general,Post to Neighbors,Blocking of view on a one way street intersect...
1192796,279369,SEECLICKFIX_420167,City of Zephyrhills,2016-04-20T11:05:40-04:00,NaN,streets,street,street_general,Street Signs,test issue. stop sign bent.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1135522,222095,SEECLICKFIX_350682,Snellville,2016-12-01T16:36:58-05:00,NaN,other,governance,governance_general,We need a traffic light as the visibility is ...,When exiting Madison Farm subdivision onto Cet...
1138455,225028,SEECLICKFIX_354770,Snellville,2016-10-30T19:02:00-04:00,NaN,sidewalks,street,street_sidewalk,Overgrown bushes on side of rd north and south...,The grass and bush going North and South of Ce...
1192085,278658,SEECLICKFIX_419192,Snellville,2016-04-25T10:54:31-04:00,NaN,street signs,governance,governance_signage,Street Signs,test issue. stop sign is bent.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1135856,222429,SEECLICKFIX_351119,Redford Township,2016-11-29T02:36:50-05:00,NaN,street lights,street,street_lighting,Street Lights,Traffic lights completely out in all direction...
1141986,228559,SEECLICKFIX_359038,Redford Township,2016-10-12T14:54:09-04:00,NaN,streets,street,street_general,Streets Potholes,Large pothole at the end of my driveway in the...
1142726,229299,SEECLICKFIX_359892,Redford Township,2016-10-10T18:18:05-04:00,NaN,other,governance,governance_general,Not maintaining the property,Over grown grass trees and weeds growing throu...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1137188,223761,SEECLICKFIX_352977,Poughkeepsie NY (DEMO),2016-11-12T13:30:21-05:00,NaN,other,governance,governance_general,Pothole - wicked tooth jarring hole,Pothole left behind from water main issues in ...
1186624,273197,SEECLICKFIX_412458,Poughkeepsie NY (DEMO),2016-05-17T14:46:15-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Test - Gray Toyota Car parked on the curb.
1194360,280933,SEECLICKFIX_422287,Poughkeepsie NY (DEMO),2016-04-11T11:27:40-04:00,NaN,other,governance,governance_general,Streets-test,Small crack in sidewalk. This is a test issue.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1137321,223894,SEECLICKFIX_353183,Public Works Service Area,2016-11-10T16:04:09-05:00,NaN,streetlight,street,street_lighting,Other,THANK YOU GRU - THE LIGHTS HAVE BEEN REPAIRED...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1140383,226956,SEECLICKFIX_357227,NYC311,2016-10-17T12:54:56-04:00,NaN,street light problem,street,street_lighting,Street Light Problem,Roadway lights out on the Major Deegan highway...
1146435,233008,SEECLICKFIX_364176,NYC311,2016-09-28T22:41:02-04:00,NaN,pothole,street,street_repair,Pothole,After conedison dig some digging but never fix...
1147521,234094,SEECLICKFIX_365410,NYC311,2016-09-26T13:44:57-04:00,NaN,cracked sidewalk,street,street_sidewalk,Large tree branch hanging loose.,Large tree branch right above the city bikes i...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1140952,227525,SEECLICKFIX_357874,City of Blue Ash,2016-10-14T23:32:58-04:00,NaN,other,governance,governance_general,Green Traffic Light out on left lane.,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1141034,227607,SEECLICKFIX_357964,City of Margate,2016-10-14T18:36:34-04:00,NaN,street lights,street,street_lighting,Light not working,Left turn lane light arrow not working causing...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1143082,229655,SEECLICKFIX_360303,City of Hobart,2016-10-09T18:02:42-04:00,NaN,other,governance,governance_general,Dead deer,Laying in side of road
1208740,295313,SEECLICKFIX_443227,City of Hobart,2015-11-20T11:58:58-05:00,NaN,pothole,street,street_repair,Pothole,On the shoulder. 3 ft wide. Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1143536,230109,SEECLICKFIX_360825,City of Toledo,2016-10-07T13:06:42-04:00,NaN,junkdebristall grass&weedsbroken vehicles,environment,environment_abandoned_site,Junkdebristall grass&weedsbroken vehicles,731 Saturn Ditch over growth
1143850,230423,SEECLICKFIX_361184,City of Toledo,2016-10-06T15:15:48-04:00,NaN,junkdebristall grass&weedsbroken vehicles,environment,environment_abandoned_site,Junkdebristall grass&weedsbroken vehicles,Old mattress and debris leaning against the si...
1143895,230468,SEECLICKFIX_361232,City of Toledo,2016-10-06T13:44:12-04:00,NaN,street potholes,street,street_repair,Street Potholes,In front of driveway at 924 waybridge. I li...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1146780,233353,SEECLICKFIX_364579,Santa Monica CA,2016-09-28T02:11:05-04:00,NaN,street lights,street,street_lighting,Street Lights,The entire 20th street south of San Vicente an...
1195950,282523,SEECLICKFIX_424397,Santa Monica CA,2016-03-31T10:36:45-04:00,NaN,streets,street,street_general,"Streets - \Keep Clear\"" marking needed""",This area gets packed in the mornings because ...
1208041,294614,SEECLICKFIX_442182,Santa Monica CA,2015-12-02T14:37:39-05:00,NaN,street lights,street,street_lighting,Street Lights,Light flickers on and then goes out for severa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1149123,235696,SEECLICKFIX_367264,North Fond du Lac,2016-09-21T09:07:06-04:00,NaN,grass mowing,environment,environment_overgrowth,Grass no being maintained,Grass is now approx 15\ tall. Has not been cut...
1206217,292790,SEECLICKFIX_439509,North Fond du Lac,2015-12-30T09:20:00-05:00,NaN,missed refuse / recycling,environment,environment_garbage_collection,Missed Refuse / Recycling,Recycling drove right by without picking up th...
1207067,293640,SEECLICKFIX_440792,North Fond du Lac,2015-12-15T12:38:40-05:00,NaN,terrace trees - landscaping,environment,environment_overgrowth,Terrace Trees - Landscaping,628 MINNESOTA THE TREES ON THE TERRACE NEED TO...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1149862,236435,SEECLICKFIX_368133,Glenville,2016-09-19T15:00:01-04:00,NaN,overgrown grass,environment,environment_overgrowth,Overgrown Grass,While I appreciate the town mowing the overgro...
1212715,299288,SEECLICKFIX_448980,Glenville,2015-09-30T21:20:09-04:00,NaN,pothole,street,street_repair,Pothole,Corner or Maplewood and Woodcrest. Created by ...
1214018,300591,SEECLICKFIX_450877,Glenville,2015-09-14T08:26:51-04:00,NaN,pothole,street,street_repair,Pothole,broken pavement and potholes on Ralmar where ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1150308,236881,SEECLICKFIX_368681,Erie PA,2016-09-17T15:33:54-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,NaN
1150357,236930,SEECLICKFIX_368742,Erie PA,2016-09-17T10:33:03-04:00,NaN,sidewalk damage,street,street_sidewalk,Sidewalk Damage,Cracked
1150358,236931,SEECLICKFIX_368743,Erie PA,2016-09-17T10:32:03-04:00,NaN,other,governance,governance_general,Power lines on ground,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1152908,239481,SEECLICKFIX_371712,City of Flowery Branch,2016-09-09T16:39:50-04:00,NaN,high grass/weeds,environment,environment_overgrowth,High Grass/Weeds,The grass in this yard is over a foot long or ...
1213859,300432,SEECLICKFIX_450638,City of Flowery Branch,2015-09-16T09:41:10-04:00,NaN,high grass/weeds,environment,environment_overgrowth,High Grass/Weeds,5915 Mitchell street

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1158459,245032,SEECLICKFIX_378382,eThekwini Municipality,2016-08-24T09:12:35-04:00,NaN,pothole,street,street_repair,Streetlight not working,1. Please attend to streetlight outside 9 Phyl...
1207088,293661,SEECLICKFIX_440824,eThekwini Municipality,2015-12-15T07:38:08-05:00,NaN,pothole,street,street_repair,STREET LIGHTS OUT,THE STREET LIGHTS ARE OUT AT THE TOP OF ENTABE...
1231870,318443,SEECLICKFIX_480457,eThekwini Municipality,2014-11-19T19:08:19-05:00,NaN,pothole,street,street_repair,Pothole,Huge pothole in Road

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1159090,245663,SEECLICKFIX_379100,Las Vegas,2016-08-22T22:22:25-04:00,NaN,street lights,street,street_lighting,Street light outage...,Hello and to whom it may concern There is a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1163797,250370,SEECLICKFIX_384771,Yuba City,2016-08-07T22:36:13-04:00,NaN,other,governance,governance_general,Graffiti,Graffiti on the fence and the sidewalk just in...
1170606,257179,SEECLICKFIX_392878,Yuba City,2016-07-14T19:31:11-04:00,NaN,street lights,street,street_lighting,Street Lights,BURNOUT
1205745,292318,SEECLICKFIX_438760,Yuba City,2016-01-06T21:11:32-05:00,NaN,pothole,street,street_repair,Pothole,There's a pothole that's getting bigger and no...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1168532,255105,SEECLICKFIX_390365,Lillehamer,2016-07-22T13:09:29-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Test
1168845,255418,SEECLICKFIX_390731,Lillehamer,2016-07-21T14:10:22-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Graffiti on a utiliy box : metal surface
1178303,264876,SEECLICKFIX_402244,Lillehamer,2016-06-16T13:57:42-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1173545,260118,SEECLICKFIX_396360,Chatham,2016-07-05T18:10:18-04:00,NaN,pothole,street,street_repair,Pothole,The roadway surface is very broken up for a sh...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1174526,261099,SEECLICKFIX_397622,Tyler,2016-06-30T22:31:22-04:00,NaN,street lights,street,street_lighting,Street Lights,Light is out
1188040,274613,SEECLICKFIX_414120,Tyler,2016-05-12T16:34:06-04:00,NaN,street signs,governance,governance_signage,No turn light,The left turn light going northbound on old ja...
1199985,286558,SEECLICKFIX_429922,Tyler,2016-02-27T15:28:32-05:00,NaN,flooding,street,street_drainage,Flooding,End of street has fallen off and taken curb ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1176455,263028,SEECLICKFIX_400000,Caldwell NJ,2016-06-23T14:08:18-04:00,NaN,other,governance,governance_general,Other,Resident at 44 Central reported that the tree ...
1179097,265670,SEECLICKFIX_403265,Caldwell NJ,2016-06-13T13:55:42-04:00,NaN,other,governance,governance_general,Other,Resident Aneta Dabek reported a dead tree on t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1176497,263070,SEECLICKFIX_400049,City of Amsterdam,2016-06-23T12:18:12-04:00,NaN,overgrown vegetation,environment,environment_overgrowth,Overgrown Vegetation,Sidewalk between Romeyn Ave and Tremont overgr...
1177093,263666,SEECLICKFIX_400771,City of Amsterdam,2016-06-21T14:07:15-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti on garage door and house,Keeps comeing back even after they covered up ...
1207374,293947,SEECLICKFIX_441241,City of Amsterdam,2015-12-10T15:20:40-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,Our children's parks are being vandalized with...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1177294,263867,SEECLICKFIX_401033,City of San Rafael,2016-06-20T19:28:29-04:00,NaN,street lights,street,street_lighting,Street Lights,The street light at this pole is on 24 hours a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1177689,264262,SEECLICKFIX_401530,Lagos,2016-06-19T05:46:21-04:00,NaN,street repair,street,street_repair,Street Repair,Bad portion on Abiodun Road off 5th Avenue Gow...
1195833,282406,SEECLICKFIX_424241,Lagos,2016-04-01T07:33:52-04:00,NaN,street repair,street,street_repair,Street Repair,Port hole. At major road.
1197905,284478,SEECLICKFIX_427047,Lagos,2016-03-16T12:15:45-04:00,NaN,illegal dumping,environment,environment_dumping,Illegal Dumping,Illegal Dumping of Refuse on Oslo Way

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1177915,264488,SEECLICKFIX_401791,Cookeville,2016-06-17T19:22:03-04:00,NaN,street lights,street,street_lighting,Street Lights,The street lights on each side of this house a...
1200241,286814,SEECLICKFIX_430255,Cookeville,2016-02-25T15:51:37-05:00,NaN,pothole,street,street_repair,Pothole,TEst Issue. Please ignore. Pothole
1207501,294074,SEECLICKFIX_441428,Cookeville,2015-12-09T10:46:14-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Trash,Trash can over flowing

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1180251,266824,SEECLICKFIX_404786,Loveland CO,2016-06-08T10:21:01-04:00,NaN,pothole,street,street_repair,Pot /Sink hole.,Sink hole south side of street at curb. Affect...
1205206,291779,SEECLICKFIX_437952,Loveland CO,2016-01-13T12:24:42-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Street Lights,Test issue
1205207,291780,SEECLICKFIX_437953,Loveland CO,2016-01-13T12:20:20-05:00,NaN,pothole,street,street_repair,Pothole,test issue not real. pothole

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1181818,268391,SEECLICKFIX_406682,Town of Seekonk,2016-06-02T23:10:09-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1181819,268392,SEECLICKFIX_406683,Town of Seekonk,2016-06-02T23:09:36-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1186070,272643,SEECLICKFIX_411793,Town of Seekonk,2016-05-18T21:47:17-04:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1183589,270162,SEECLICKFIX_408811,Arkansas City,2016-05-27T12:59:42-04:00,NaN,pothole,street,street_repair,Numerous potholes,Numerous potholes on 21 that need addressed gr...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1183753,270326,SEECLICKFIX_409010,Roswell GA,2016-05-26T19:24:39-04:00,NaN,other,governance,governance_general,Trail deteriorating,Across the street from 385 Azalea Dr there are...
1183755,270328,SEECLICKFIX_409013,Roswell GA,2016-05-26T19:19:57-04:00,NaN,other,governance,governance_general,Trail deteriorating,Across the street from st. Francis day school ...
1190620,277193,SEECLICKFIX_417364,Roswell GA,2016-05-02T10:29:33-04:00,NaN,pothole,street,street_repair,Pothole behind Atlanta Bread - Stonebridge Squ...,There is a HUGE pothole behind Atlanta Bread a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1184402,270975,SEECLICKFIX_409796,City of McDonough,2016-05-24T19:46:35-04:00,NaN,property maintenance,housing,housing_general,Grass,NaN
1185122,271695,SEECLICKFIX_410647,City of McDonough,2016-05-22T20:41:19-04:00,NaN,property maintenance,housing,housing_general,Abandoned house and yard is disarray,House appears abandoned and grass is out of co...
1185123,271696,SEECLICKFIX_410648,City of McDonough,2016-05-22T20:39:05-04:00,NaN,property maintenance,housing,housing_general,Yard maintenance,House appears abandoned and grass is out of co...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1185665,272238,SEECLICKFIX_411298,Town of Bedford,2016-05-20T07:48:04-04:00,NaN,pothole,street,street_repair,Pothole,Corner of street and sidewalk.
1198219,284792,SEECLICKFIX_427490,Town of Bedford,2016-03-14T08:50:28-04:00,NaN,pothole,street,street_repair,Pothole,Decent sized pothole at transition between Bed...
1198381,284954,SEECLICKFIX_427714,Town of Bedford,2016-03-12T10:14:51-05:00,NaN,pothole,street,street_repair,Pothole,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1187033,273606,SEECLICKFIX_412905,North Olmsted,2016-05-16T17:07:14-04:00,NaN,other,governance,governance_general,Other,there is a large pot hole at the driveway of o...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1187351,273924,SEECLICKFIX_413290,Town of Halifax,2016-05-15T18:53:44-04:00,NaN,pothole,street,street_repair,Pothole,2 foot wide possible 6 inchs deep
1199645,286218,SEECLICKFIX_429455,Town of Halifax,2016-03-01T16:16:24-05:00,NaN,other,governance,governance_general,Other,The drain hole was torn up during plowing and ...
1201743,288316,SEECLICKFIX_432284,Town of Halifax,2016-02-14T16:08:47-05:00,NaN,pothole,street,street_repair,Potholes,Many potholes on franklin street for a long ti...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1189509,276082,SEECLICKFIX_415920,Georgetown KY,2016-05-06T23:35:42-04:00,NaN,streets,street,street_general,Potholes,Potholes are taking up the entire width of the...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1189750,276323,SEECLICKFIX_416241,Gary IN,2016-05-06T00:25:35-04:00,NaN,other,governance,governance_general,Post to neighbors,NaN
1202097,288670,SEECLICKFIX_432785,Gary IN,2016-02-09T20:37:34-05:00,NaN,other,governance,governance_general,Other,Can the law of a Reprocity be applied to someo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1191567,278140,SEECLICKFIX_418552,Town of West Boylston,2016-04-27T13:10:44-04:00,NaN,tree problems,environment,environment_overgrowth,Tree problems,Hello I live at 56 Western Ave and my next do...
1193605,280178,SEECLICKFIX_421229,Town of West Boylston,2016-04-15T14:48:49-04:00,NaN,drainage or flooding issues,street,street_drainage,Drainage or flooding issues,We have been trying for 3 years to correct the...
1195266,281839,SEECLICKFIX_423492,Town of West Boylston,2016-04-05T09:09:35-04:00,NaN,pothole,street,street_repair,Pothole and drainage issue,Large pothole at bottom of driveway and water ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1192968,279541,SEECLICKFIX_420394,City of Park Ridge,2016-04-19T12:41:12-04:00,NaN,other,governance,governance_general,dead animals,there is a large cat on talcott in front of pa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1193156,279729,SEECLICKFIX_420650,Dallas,2016-04-18T14:21:50-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,test issu.
1193174,279747,SEECLICKFIX_420670,Dallas,2016-04-18T13:24:57-04:00,NaN,flooding,street,street_drainage,Flooding,test issue

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1193889,280462,SEECLICKFIX_421616,Town of Ashland,2016-04-13T23:13:01-04:00,NaN,pothole,street,street_repair,Sewer cover disintegrating,Asphalt is work away on sides of sewer cover c...
1195152,281725,SEECLICKFIX_423353,Town of Ashland,2016-04-05T15:08:09-04:00,NaN,road hazard,street,street_general,Road Hazard,Looks like a pipe cover was ripped out of the ...
1196018,282591,SEECLICKFIX_424504,Town of Ashland,2016-03-30T17:09:12-04:00,NaN,pothole,street,street_repair,Pothole,Why is Parcel Search not functioning on the As...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1194902,281475,SEECLICKFIX_423015,City of Angola,2016-04-06T22:34:10-04:00,NaN,other,governance,governance_general,Other,test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1195085,281658,SEECLICKFIX_423265,Doral,2016-04-05T20:53:45-04:00,NaN,pothole,street,street_repair,Pothole,Pothole located at the right side almost arriv...
1207022,293595,SEECLICKFIX_440728,Doral,2015-12-16T07:44:51-05:00,NaN,pothole,street,street_repair,Potholes & crooked line,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1195507,282080,SEECLICKFIX_423792,Town of Millis,2016-04-04T09:11:23-04:00,NaN,street light issue,street,street_lighting,Street Light,Street light at 55/57 Hilltop turns on then sh...
1212171,298744,SEECLICKFIX_448205,Town of Millis,2015-10-08T11:14:26-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1226304,312877,SEECLICKFIX_469913,Town of Millis,2015-03-25T12:34:22-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,Sidewalk needs plowing

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1195743,282316,SEECLICKFIX_424103,Village of Sussex,2016-04-01T18:31:48-04:00,NaN,pothole,street,street_repair,Pothole,The railroad tracks by The Boneyard and Quad G...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1196375,282948,SEECLICKFIX_425031,Jackson County MS,2016-03-28T11:04:42-04:00,NaN,street lights,street,street_lighting,street light is blown,The street light is at the kids bus stop and w...
1202258,288831,SEECLICKFIX_433017,Jackson County MS,2016-02-08T14:19:04-05:00,NaN,street lights,street,street_lighting,Street Lights,Test issue light out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1196392,282965,SEECLICKFIX_425051,Mill Creek,2016-03-28T10:05:39-04:00,NaN,street lights,street,street_lighting,Street light operating improperly.,Sodium vapor lamp cycles on and off.
1207370,293943,SEECLICKFIX_441235,Mill Creek,2015-12-10T16:20:55-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Pothole,Pothole is on side of road
1207380,293953,SEECLICKFIX_441254,Mill Creek,2015-12-10T13:11:18-05:00,NaN,street lights,street,street_lighting,[test] Street Light,street light is broken

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1196640,283213,SEECLICKFIX_425351,Palm Beach County,2016-03-25T21:02:58-04:00,NaN,street lights,street,street_lighting,Street Lights,All lights out in parking lot behind McKeen To...
1196935,283508,SEECLICKFIX_425762,Palm Beach County,2016-03-23T11:02:53-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,There is no sidewalk going to this bus stop on...
1197285,283858,SEECLICKFIX_426199,Palm Beach County,2016-03-21T16:06:20-04:00,NaN,other,governance,governance_general,Commercial vehicle,This commercial yard waste truck continues to ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1197092,283665,SEECLICKFIX_425970,Hartford 311,2016-03-22T13:47:40-04:00,NaN,pothole,street,street_repair,Pothole,Several big potholes. Car damages and noise un...
1197770,284343,SEECLICKFIX_426847,Hartford 311,2016-03-17T13:46:10-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN
1197771,284344,SEECLICKFIX_426849,Hartford 311,2016-03-17T13:45:35-04:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1197152,283725,SEECLICKFIX_426038,Fayette County,2016-03-22T09:39:49-04:00,NaN,street lights,street,street_lighting,Pothole,Test issue - pothole

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1197414,283987,SEECLICKFIX_426374,Town of Oakville,2016-03-20T20:24:24-04:00,NaN,pothole,street,street_repair,Pothole,Timings for traffic light is not good. Hyde pa...
1199892,286465,SEECLICKFIX_429796,Town of Oakville,2016-02-28T16:10:49-05:00,NaN,pothole,street,street_repair,Pothole,The soil erosion has caused root exposure and ...
1214017,300590,SEECLICKFIX_450875,Town of Oakville,2015-09-14T08:53:40-04:00,NaN,pothole,street,street_repair,Pothole,Not a pothole but you give me no other options...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1197960,284533,SEECLICKFIX_427131,McComb,2016-03-15T20:28:00-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,Test Issue abandoned vehicle
1197969,284542,SEECLICKFIX_427148,McComb,2016-03-15T18:08:54-04:00,NaN,street lights,street,street_lighting,Street Lights,Test issue please ignore streetlight
1197972,284545,SEECLICKFIX_427152,McComb,2016-03-15T18:05:45-04:00,NaN,pothole,street,street_repair,Pothole,Test Issue Please ignore Pothole

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1198116,284689,SEECLICKFIX_427347,Town of Mashpee,2016-03-14T17:24:43-04:00,NaN,sidewalk issue,street,street_sidewalk,Sidewalk Issue,On the Mashpee Walking Path at 278 Main St the...
1200862,287435,SEECLICKFIX_431046,Town of Mashpee,2016-02-22T09:28:57-05:00,NaN,other,governance,governance_general,Condition of road,I would like to have RiverRd considered for re...
1201858,288431,SEECLICKFIX_432449,Town of Mashpee,2016-02-12T14:37:38-05:00,NaN,pothole,street,street_repair,Pothole,2 large potholes at the end of Great Oak R jus...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1198515,285088,SEECLICKFIX_427882,Jefferson County,2016-03-11T10:55:32-05:00,NaN,street lights,street,street_lighting,Pothole,Test issue please ignore.
1200087,286660,SEECLICKFIX_430056,Jefferson County,2016-02-26T15:08:19-05:00,NaN,flooding,street,street_drainage,Flooding,test issue please ignore.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1199243,285816,SEECLICKFIX_428867,Westwood Neighborhood Council,2016-03-05T19:38:09-05:00,NaN,street light,street,street_lighting,Street Light,the street light between Landfair ave and Roeb...
1202413,288986,SEECLICKFIX_433242,Westwood Neighborhood Council,2016-02-06T17:02:37-05:00,NaN,pothole,street,street_repair,Pothole - causing damage,There is a damaging pothole coming on to Chari...
1228328,314901,SEECLICKFIX_474881,Westwood Neighborhood Council,2015-02-11T10:46:37-05:00,NaN,graffiti,vandalism,vandalism_graffiti,Graffiti,"The word \Aafen\"" has been spray-painted on th..."

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1199994,286567,SEECLICKFIX_429934,Katy,2016-02-27T13:59:14-05:00,NaN,street lights,street,street_lighting,Light sequence is too long on Saturdays,Fix it!
1204534,291107,SEECLICKFIX_436938,Katy,2016-01-20T19:29:59-05:00,NaN,pothole,street,street_repair,Dangerous potholes,Please repair the potholes on Greenbush Rd Kat...
1207403,293976,SEECLICKFIX_441285,Katy,2015-12-10T09:47:51-05:00,NaN,street lights,street,street_lighting,Street Lights,Light is broken

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1200775,287348,SEECLICKFIX_430937,West Park FL,2016-02-22T15:26:14-05:00,NaN,street lights,street,street_lighting,Street Lights,Test Issue please ignore. Light is damaged
1200779,287352,SEECLICKFIX_430942,West Park FL,2016-02-22T14:49:12-05:00,NaN,street signs,governance,governance_signage,Street Signs,Test Issue please ignore. Bent stop sign

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1200846,287419,SEECLICKFIX_431026,Ruston LA,2016-02-22T10:40:07-05:00,NaN,pothole,street,street_repair,Pothole,Test issue pothole

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1201388,287961,SEECLICKFIX_431766,Upper Providence PA (DEMO),2016-02-17T22:30:00-05:00,NaN,street lights,street,street_lighting,Street Lights,chapel hill road and providence road media pa ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1201616,288189,SEECLICKFIX_432110,Kluang Johor,2016-02-16T08:38:59-05:00,NaN,street lights not working / lampu jalan tidak ...,street,street_lighting,Street Lights not working / Lampu Jalan tidak ...,NaN
1204911,291484,SEECLICKFIX_437511,Kluang Johor,2016-01-17T03:06:10-05:00,NaN,pothole / lubang di jalan,street,street_repair,Pothole / Lubang di Jalan,Tanah runtuhmendapan tanah serta hakisan di ba...
1209663,296236,SEECLICKFIX_444617,Kluang Johor,2015-11-08T03:25:46-05:00,NaN,traffic lights not working / lampu isyarat tid...,street,street_urgent_repair,Traffic Lights not working / Lampu Isyarat tid...,空地没人处理，长了大树对旁边的屋子有威胁，该如何好？

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1202612,289185,SEECLICKFIX_433522,Auburn AL,2016-02-04T15:33:25-05:00,NaN,street lights,street,street_lighting,Street Signs,TEST ISSUE - street sign down

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1202644,289217,SEECLICKFIX_433563,Belleair Bluffs,2016-02-04T13:00:59-05:00,NaN,other,governance,governance_general,Other,In center island at cut de sac there is a slic...
1208590,295163,SEECLICKFIX_443005,Belleair Bluffs,2015-11-23T10:21:00-05:00,NaN,street lights,street,street_lighting,Street Lights,Light is out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1202660,289233,SEECLICKFIX_433582,Town of Schodack,2016-02-04T11:33:57-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Street Signs,Test issue street sign down

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1202734,289307,SEECLICKFIX_433681,Rocky Hill NJ,2016-02-03T16:33:36-05:00,NaN,pothole,street,street_repair,Pothole,This is a test issue.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1203496,290069,SEECLICKFIX_434723,Lawrenceville GA (DEMO),2016-01-28T09:52:49-05:00,NaN,pothole,street,street_repair,very big pothole need patch ASAP,When traveling on 29 going towards Pleasant Hi...
1206169,292742,SEECLICKFIX_439434,Lawrenceville GA (DEMO),2015-12-30T20:54:16-05:00,NaN,pothole,street,street_repair,Pothole,Huge Pothole in Walmart parking lot. It was re...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1203588,290161,SEECLICKFIX_434881,Tullahoma TN,2016-01-27T10:38:15-05:00,NaN,street signs,governance,governance_signage,Street Signs,Bent sign

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1203699,290272,SEECLICKFIX_435043,East Chicago Code Enforcement (Private Issues),2016-01-26T15:26:06-05:00,NaN,55.032 using containers of others declare unla...,public_order,publicorder_general,55.032 USING CONTAINERS OF OTHERS DECLARE UNLA...,Neighbors illegally using containers of others...
1203701,290274,SEECLICKFIX_435045,East Chicago Code Enforcement (Private Issues),2016-01-26T15:22:16-05:00,NaN,55.032 using containers of others declare unla...,public_order,publicorder_general,55.032 USING CONTAINERS OF OTHERS DECLARE UNLA...,Neighbors illegally using containers of others...
1203702,290275,SEECLICKFIX_435048,East Chicago Code Enforcement (Private Issues),2016-01-26T15:12:31-05:00,NaN,156.383c maintenance and repair of fence,environment,environment_general,156.383C MAINTENANCE AND REPAIR OF FENCE,Damaged perimeter security fencing in deterior...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1204006,290579,SEECLICKFIX_435600,St. Mary's County MD (DEMO),2016-01-25T10:35:20-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,I am too old to shovel the sidewalk in front o...
1204089,290662,SEECLICKFIX_435825,St. Mary's County MD (DEMO),2016-01-24T20:55:49-05:00,NaN,other,governance,governance_general,Snow Removal,Need help shoveling driveway. cheryl45529@gma...
1204184,290757,SEECLICKFIX_436186,St. Mary's County MD (DEMO),2016-01-23T18:12:32-05:00,NaN,other,governance,governance_general,Other,My drive way

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1204034,290607,SEECLICKFIX_435702,Frostproof,2016-01-25T09:34:01-05:00,NaN,flooding,street,street_drainage,Flooding,TEST ISSUE. NOT REAL. flooding

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1204179,290752,SEECLICKFIX_436163,Middlesex County Improvement Authority NJ (DEMO),2016-01-23T18:52:58-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks/driveway/front and back porches.,I'm just trying to get help with the snow shov...
1206951,293524,SEECLICKFIX_440630,Middlesex County Improvement Authority NJ (DEMO),2015-12-16T22:00:24-05:00,NaN,street lights,street,street_lighting,No streetlight and sidewalk on hiddenValley drive,Hello Sir I live in hidden valley at Edison...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1204269,290842,SEECLICKFIX_436467,Hyattsville MD,2016-01-22T19:40:32-05:00,NaN,other,governance,governance_general,Other,Snow removal
1204279,290852,SEECLICKFIX_436513,Hyattsville MD,2016-01-22T17:44:26-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Help shoveling
1204286,290859,SEECLICKFIX_436527,Hyattsville MD,2016-01-22T17:09:22-05:00,NaN,sidewalks,street,street_sidewalk,Shovel request please. 3606 hamilton street hy...,If someone would be kind enough to shovel our ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1204589,291162,SEECLICKFIX_437026,Ephraim City,2016-01-20T13:40:19-05:00,NaN,street signs,governance,governance_signage,Street Signs,TEST ISSUE NOT REAL. stop sign bent

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1205489,292062,SEECLICKFIX_438376,LaBelle FL (DEMO),2016-01-09T22:20:11-05:00,NaN,flooding,street,street_drainage,mosquitoes,The mosquitos are very thick around my propert...
1213527,300100,SEECLICKFIX_450132,LaBelle FL (DEMO),2015-09-21T12:26:41-04:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Parks and Playgrounds,TEST: This slide is cracked please fix when yo...
1213541,300114,SEECLICKFIX_450151,LaBelle FL (DEMO),2015-09-21T10:21:35-04:00,NaN,streets,street,street_general,Streets,TEST

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1205591,292164,SEECLICKFIX_438532,Derby,2016-01-08T14:37:01-05:00,NaN,pothole,street,street_repair,Pothole,large pothole
1205595,292168,SEECLICKFIX_438539,Derby,2016-01-08T13:50:18-05:00,NaN,street signs,governance,governance_signage,Street Signs,broken stop sign please fix.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1205777,292350,SEECLICKFIX_438815,Highland City UT (DEMO),2016-01-06T14:49:06-05:00,NaN,street lights,street,street_lighting,Lighting,A street light is not functioning at this loca...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1205929,292502,SEECLICKFIX_439078,Homewood City Hall,2016-01-04T10:24:43-05:00,NaN,other,governance,governance_general,Graffiti,Large spray paint graffiti on north side of Au...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1206086,292659,SEECLICKFIX_439329,City of Lehi,2015-12-31T20:22:37-05:00,NaN,other,governance,governance_general,Other,The streets in this neighborhood haven't seen ...
1206833,293406,SEECLICKFIX_440456,City of Lehi,2015-12-18T13:53:15-05:00,NaN,flooding,street,street_drainage,Sewer drain is clogged,There is a back up of water on the street. Test.
1206866,293439,SEECLICKFIX_440497,City of Lehi,2015-12-18T08:59:06-05:00,NaN,street lights,street,street_lighting,Street Lights,What is up with the lights at the on ramps? 5 ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1206242,292815,SEECLICKFIX_439564,Prince Albert CAN (DEMO),2015-12-29T16:48:05-05:00,NaN,other,governance,governance_general,Jake brakes in city limits,Why is there not a sign outside of the city to...
1208440,295013,SEECLICKFIX_442766,Prince Albert CAN (DEMO),2015-11-25T11:27:18-05:00,NaN,streets,street,street_general,Streets,with the increase of traffic through CYPA it i...
1209715,296288,SEECLICKFIX_444687,Prince Albert CAN (DEMO),2015-11-07T00:45:45-05:00,NaN,other,governance,governance_general,Christmas and dentists,There are absolutely no dentists in PA for abo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1206525,293098,SEECLICKFIX_440029,City of Sauk Rapids,2015-12-23T11:11:24-05:00,NaN,pothole,street,street_repair,Pothole,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1206838,293411,SEECLICKFIX_440461,Easton MA,2015-12-18T13:11:44-05:00,NaN,potholes,street,street_repair,Potholes,Resident reported large pothole at entrance to...
1206977,293550,SEECLICKFIX_440670,Easton MA,2015-12-16T14:47:42-05:00,NaN,potholes,street,street_repair,Potholes,Hi many potholes on the Center Street end of W...
1207077,293650,SEECLICKFIX_440808,Easton MA,2015-12-15T10:22:06-05:00,NaN,streetlights,street,street_lighting,Streetlights,There are three LED street lights that have be...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207163,293736,SEECLICKFIX_440930,South Jordan UT,2015-12-14T09:41:28-05:00,NaN,street lights,street,street_lighting,Street Lights,Left turn does not turn green
1207444,294017,SEECLICKFIX_441353,South Jordan UT,2015-12-09T16:30:01-05:00,NaN,sidewalks,street,street_sidewalk,Pothole,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207298,293871,SEECLICKFIX_441124,Town of Holliston,2015-12-11T15:08:54-05:00,NaN,street lights,street,street_lighting,Street Lights,Mostly off.
1220098,306671,SEECLICKFIX_459995,Town of Holliston,2015-06-24T14:40:58-04:00,NaN,street lights,street,street_lighting,Street Lights,In front of Holliston Sportsmen Assoc. driveway.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207470,294043,SEECLICKFIX_441384,Marion,2015-12-09T14:17:30-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,[test] issue pothole,pothole near SW of intersection

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207525,294098,SEECLICKFIX_441460,Santa Fe NM (DEMO),2015-12-09T07:42:06-05:00,NaN,street lights,street,street_lighting,Street Lights,2 lights out at Camino Consuelo & Siringo. 1 ...
1207673,294246,SEECLICKFIX_441659,Santa Fe NM (DEMO),2015-12-07T17:58:22-05:00,NaN,street lights,street,street_lighting,dark neighborhood.,The fifth street light on the left coming from...
1208086,294659,SEECLICKFIX_442256,Santa Fe NM (DEMO),2015-12-01T18:16:12-05:00,NaN,other,governance,governance_general,Other,Extremely high traffic Blatant criminal activi...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207603,294176,SEECLICKFIX_441565,Westerly RI (DEMO),2015-12-08T12:21:21-05:00,NaN,pothole,street,street_repair,Pothole,Two potholes in front of my house on either si...
1210723,297296,SEECLICKFIX_446150,Westerly RI (DEMO),2015-10-26T17:41:57-04:00,NaN,street lights,street,street_lighting,Street Lights,street light on route 1 and Andersen Court

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207676,294249,SEECLICKFIX_441663,City of Syracuse,2015-12-07T17:29:22-05:00,NaN,street lights,street,street_lighting,Street Lights,THE LIGHT ON THE 4- WAY STOP OF ULSTER / EMERS...
1207796,294369,SEECLICKFIX_441824,City of Syracuse,2015-12-05T19:15:35-05:00,NaN,pothole,street,street_repair,Dangerous pothole,Driving from the East Gennessee Street into th...
1207908,294481,SEECLICKFIX_441970,City of Syracuse,2015-12-04T12:41:52-05:00,NaN,pothole,street,street_repair,Pothole,Standing water splashes pedestrians and building.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207688,294261,SEECLICKFIX_441678,Sioux Falls SD (DEMO),2015-12-07T16:15:05-05:00,NaN,street lights,street,street_lighting,Pothole,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207740,294313,SEECLICKFIX_441746,Town of Nantucket,2015-12-07T06:49:18-05:00,NaN,other,governance,governance_general,Broken Utility Cover,NaN
1209062,295635,SEECLICKFIX_443719,Town of Nantucket,2015-11-16T12:05:55-05:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Granite curb is dislocated.
1211234,297807,SEECLICKFIX_446840,Town of Nantucket,2015-10-20T21:31:34-04:00,NaN,other,governance,governance_general,Tree stump and hazardous sidewalk at 14 North ...,A large town owned tree at this location split...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207912,294485,SEECLICKFIX_441979,Espanola NM (DEMO),2015-12-04T12:10:26-05:00,NaN,streets,street,street_general,Streets,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207965,294538,SEECLICKFIX_442065,Shenandoah,2015-12-03T15:00:15-05:00,NaN,pothole,street,street_repair,No sidewalk,TEST

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207974,294547,SEECLICKFIX_442079,Larimer County CO (DEMO),2015-12-03T13:06:33-05:00,NaN,streets,street,street_general,pothole,The pothole is off the pavement right at the c...
1211717,298290,SEECLICKFIX_447521,Larimer County CO (DEMO),2015-10-14T16:40:35-04:00,NaN,streets,street,street_general,Streets,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207976,294549,SEECLICKFIX_442082,Muscatine,2015-12-03T12:26:59-05:00,NaN,parks and playgrounds,governance,governance_parks_and_rec,Street Lights,Light is out

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1207985,294558,SEECLICKFIX_442096,Norco CA (DEMO),2015-12-03T11:27:28-05:00,NaN,other,governance,governance_general,Other,Flood drain blocked by weeds and dirt. Probab...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1208446,295019,SEECLICKFIX_442775,Centralia MO,2015-11-25T10:18:07-05:00,NaN,sidewalks,street,street_sidewalk,Streets,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1208558,295131,SEECLICKFIX_442960,City of Nashville,2015-11-23T14:29:37-05:00,NaN,pothole,street,street_repair,Pothole,3 ft wide. On the shoulder. Test.
1209888,296461,SEECLICKFIX_444954,City of Nashville,2015-11-05T08:43:48-05:00,NaN,pothole,street,street_repair,Pothole,Deep pot holes at the intersection of south 16...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1208905,295478,SEECLICKFIX_443459,Town of East Greenwich,2015-11-18T14:05:44-05:00,NaN,other,governance,governance_general,Street Light Out,The Street Light at the entrance to Foster Way...
1211510,298083,SEECLICKFIX_447225,Town of East Greenwich,2015-10-17T11:25:35-04:00,NaN,parks & playgrounds,governance,governance_parks_and_rec,Parks & Playgrounds,Moss

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1208980,295553,SEECLICKFIX_443589,City of Rapid City,2015-11-17T12:28:07-05:00,NaN,pothole,street,street_repair,Pothole,3 ft wide. On the shoulder. Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1209064,295637,SEECLICKFIX_443722,City of Fort Worth,2015-11-16T11:22:51-05:00,NaN,other,governance,governance_general,Street Light Out,The street light is our on the corner of Counc...
1209381,295954,SEECLICKFIX_444219,City of Fort Worth,2015-11-11T09:16:57-05:00,NaN,other,governance,governance_general,School zone,School zone lights not blinking at mm Walton e...
1209382,295955,SEECLICKFIX_444220,City of Fort Worth,2015-11-11T09:12:10-05:00,NaN,other,governance,governance_general,Pot Hole,Larger pot hole causing damage to cars flat t...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1209354,295927,SEECLICKFIX_444174,Avondale AZ,2015-11-11T14:38:01-05:00,NaN,streets,street,street_general,Streets,This is a test issue.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1209462,296035,SEECLICKFIX_444328,Port of San Diego,2015-11-10T13:12:01-05:00,NaN,pothole,street,street_repair,Pothole,2 Big Potholes! had to avoid it quickly while ...
1210430,297003,SEECLICKFIX_445739,Port of San Diego,2015-10-29T20:05:49-04:00,NaN,pothole,street,street_repair,Pothole,Deep-long rail-like impressions in the road. V...
1210710,297283,SEECLICKFIX_446133,Port of San Diego,2015-10-26T20:50:52-04:00,NaN,street lights,street,street_lighting,Street Lights,There is a dual left from harbor to scott st. ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1209482,296055,SEECLICKFIX_444358,City of Gustine,2015-11-10T11:16:15-05:00,NaN,other,governance,governance_general,Other,10 cars at house hold leaking oil into gutter ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1209496,296069,SEECLICKFIX_444380,City of Lee's Summit,2015-11-10T09:18:14-05:00,NaN,other,governance,governance_general,THe new Highway messages,MORE POWER TO YOU!! Anyone that complains abo...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1210183,296756,SEECLICKFIX_445384,City of Las Vegas,2015-11-02T12:19:10-05:00,NaN,signs signals and lighting,street,street_urgent_repair,Signs Signals and Lighting,STREET LIGHT OUT PLEASE REPAIR
1210370,296943,SEECLICKFIX_445654,City of Las Vegas,2015-10-30T12:51:01-04:00,NaN,signs signals and lighting,street,street_urgent_repair,Signs Signals and Lighting,NaN
1211228,297801,SEECLICKFIX_446832,City of Las Vegas,2015-10-20T23:06:07-04:00,NaN,signs signals and lighting,street,street_urgent_repair,Street lights,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1210193,296766,SEECLICKFIX_445401,Colquitt County GA (DEMO),2015-11-02T10:17:54-05:00,NaN,sidewalks,street,street_sidewalk,Pothole,Test
1210498,297071,SEECLICKFIX_445849,Colquitt County GA (DEMO),2015-10-29T09:42:04-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Test Issue.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1210838,297411,SEECLICKFIX_446309,City of Southgate,2015-10-24T21:22:51-04:00,NaN,sidewalks,street,street_sidewalk,pedestrian operated traffic light needed.,There are numerous pedestrians that cross Fort...
1213335,299908,SEECLICKFIX_449873,City of Southgate,2015-09-23T08:18:47-04:00,NaN,other,governance,governance_general,Dead Animal,Dead coyote/possibly dog in center lane.
1213721,300294,SEECLICKFIX_450411,City of Southgate,2015-09-18T11:13:09-04:00,NaN,street signs,governance,governance_signage,Street Signs,Wood post is broken

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211004,297577,SEECLICKFIX_446547,City of Marshfield,2015-10-22T14:09:58-04:00,NaN,pothole,street,street_repair,Pothole,Shoulder. 3 ft wide. Hidden by puddle. Test.
1213432,300005,SEECLICKFIX_450001,City of Marshfield,2015-09-22T10:10:41-04:00,NaN,pothole,street,street_repair,Pothole,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211033,297606,SEECLICKFIX_446582,City of Antigua,2015-10-22T11:15:45-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Jgjggjgj,Ljkhkhkh
1211203,297776,SEECLICKFIX_446797,City of Antigua,2015-10-21T10:25:16-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211050,297623,SEECLICKFIX_446602,Coventry CT (DEMO),2015-10-22T09:21:28-04:00,NaN,pothole,street,street_repair,Streets,TEST

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211279,297852,SEECLICKFIX_446896,Albany GA (DEMO),2015-10-20T14:14:50-04:00,NaN,street lights,street,street_lighting,Pothole,Test
1211287,297860,SEECLICKFIX_446905,Albany GA (DEMO),2015-10-20T13:52:20-04:00,NaN,pothole,street,street_repair,Pothole,Test issue

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211416,297989,SEECLICKFIX_447088,City of St. Albans,2015-10-19T11:17:36-04:00,NaN,street signs,governance,governance_signage,Street Signs,Sign knocked over

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211430,298003,SEECLICKFIX_447108,City of Lake Worth,2015-10-19T08:51:37-04:00,NaN,pothole,street,street_repair,Pothole,Residents are force to drive through several d...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1211803,298376,SEECLICKFIX_447642,City of Saratoga,2015-10-13T16:09:06-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212176,298749,SEECLICKFIX_448211,City of Cloquet,2015-10-08T10:22:58-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212192,298765,SEECLICKFIX_448235,City of North Las Vegas,2015-10-07T22:45:19-04:00,NaN,street light,street,street_lighting,Street lights out,NaN
1212274,298847,SEECLICKFIX_448354,City of North Las Vegas,2015-10-06T23:07:55-04:00,NaN,street light,street,street_lighting,Neighborhood street lights,All the street lights have been out in our nei...
1216527,303100,SEECLICKFIX_454733,City of North Las Vegas,2015-08-10T14:32:37-04:00,NaN,street light,street,street_lighting,Street Light,Light out beside the mailbox

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212196,298769,SEECLICKFIX_448240,Hendersonville Water,2015-10-07T21:23:44-04:00,NaN,water leak,infrastructure,infrastructure_water,Water Leak,Water is running from spot in street.
1212241,298814,SEECLICKFIX_448303,Hendersonville Water,2015-10-07T12:27:27-04:00,NaN,water leak,infrastructure,infrastructure_water,Water Leak,Water is oozing up through the gravel driveway...
1217515,304088,SEECLICKFIX_456205,Hendersonville Water,2015-07-28T14:06:13-04:00,NaN,water valve box problem,infrastructure,infrastructure_water,Water Valve Box Problem,Valve box at intersection of Tamarac Terrace a...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212221,298794,SEECLICKFIX_448274,Las Vegas NM (DEMO),2015-10-07T15:43:49-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,TEST

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212234,298807,SEECLICKFIX_448293,Salt Lake City County UT (DEMO),2015-10-07T13:20:29-04:00,NaN,wildflower park - garbage pickup,environment,environment_garbage_collection,Wildflower Park - Garbage Pickup,Test issue! :)

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212363,298936,SEECLICKFIX_448470,City of Groveland,2015-10-06T09:24:07-04:00,NaN,flooding,street,street_drainage,Flooding,City hall dead in water
1212413,298986,SEECLICKFIX_448546,City of Groveland,2015-10-05T14:44:50-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,This is a rusty brown ford truck with no wheels
1213325,299898,SEECLICKFIX_449858,City of Groveland,2015-09-23T09:52:07-04:00,NaN,pothole,street,street_repair,Pothole,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212364,298937,SEECLICKFIX_448471,Township of Verona,2015-10-06T09:19:53-04:00,NaN,park inspection (staff only),governance,governance_parks_and_rec,Park Inspection (Staff Only),NaN
1212365,298938,SEECLICKFIX_448472,Township of Verona,2015-10-06T09:16:36-04:00,NaN,street signs,governance,governance_signage,Street Signs,Post is broken
1214676,301249,SEECLICKFIX_451883,Township of Verona,2015-09-04T10:12:05-04:00,NaN,street signs,governance,governance_signage,Street Signs,On the side of the road

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212634,299207,SEECLICKFIX_448872,City of Henderson,2015-10-01T17:22:04-04:00,NaN,street light,street,street_lighting,Street Light,This light has been out for two weeks!! it is ...
1215441,302014,SEECLICKFIX_453078,City of Henderson,2015-08-25T00:45:11-04:00,NaN,street light,street,street_lighting,Light not working,Light has been out for a while now and is not ...
1215764,302337,SEECLICKFIX_453551,City of Henderson,2015-08-20T09:52:33-04:00,NaN,street light,street,street_lighting,Street Light,street light has been out for 3 weeks

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212691,299264,SEECLICKFIX_448944,City of Biloxi,2015-10-01T09:42:46-04:00,NaN,pothole,street,street_repair,Pothole,NaN
1213109,299682,SEECLICKFIX_449557,City of Biloxi,2015-09-25T13:53:02-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1212798,299371,SEECLICKFIX_449086,City of Tamarac,2015-09-30T10:18:24-04:00,NaN,street signs,governance,governance_signage,Street Signs,Post is broken

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213232,299805,SEECLICKFIX_449739,Town of Dover NJ,2015-09-24T09:15:07-04:00,NaN,pothole,street,street_repair,Pothole,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213320,299893,SEECLICKFIX_449852,City of Des Plaines,2015-09-23T10:48:29-04:00,NaN,abandoned vehicle,environment,environment_abandoned_vehicle,Abandoned Vehicle,test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213446,300019,SEECLICKFIX_450020,Deerfield Beach FL (DEMO),2015-09-22T08:28:49-04:00,NaN,flooding,street,street_drainage,Flooding,This is a test

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213509,300082,SEECLICKFIX_450106,City of Hendersonville,2015-09-21T14:30:29-04:00,NaN,accumulation of garbage on property,environment,environment_dumping,Accumulation of Garbage on Property,Hello I have reported this issue before and wa...
1213784,300357,SEECLICKFIX_450511,City of Hendersonville,2015-09-17T11:38:11-04:00,NaN,street light out,street,street_lighting,Street Light Out,NaN
1218233,304806,SEECLICKFIX_457220,City of Hendersonville,2015-07-20T09:20:38-04:00,NaN,abandoned/junked vehicle,environment,environment_abandoned_vehicle,Abandoned/Junked Vehicle,A parked car with no license plate has been pa...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213531,300104,SEECLICKFIX_450139,Tree Data Project,2015-09-21T11:37:27-04:00,NaN,tree health,environment,environment_overgrowth,Tree Health,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213720,300293,SEECLICKFIX_450410,City of Hurricane,2015-09-18T11:13:21-04:00,NaN,pothole,street,street_repair,Pothole,Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213778,300351,SEECLICKFIX_450501,Neptune Beach FL (DEMO),2015-09-17T14:14:45-04:00,NaN,flooding,street,street_drainage,Flooding,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1213853,300426,SEECLICKFIX_450628,City of DeLeon,2015-09-16T11:03:02-04:00,NaN,loud noise,public_order,publicorder_noise_complaint,Loud Noise,Every single day an old man who is tall has lo...
1227193,313766,SEECLICKFIX_472420,City of DeLeon,2015-03-10T16:29:51-04:00,NaN,road maintenance,street,street_general,Road Maintenance,Of the 4 stop signs at the intersection of Man...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1214363,300936,SEECLICKFIX_451382,West Melbourne FL (DEMO),2015-09-09T16:52:11-04:00,NaN,sidewalks,street,street_sidewalk,Sidewalks,This is a Test. Please clean this sidewalk wh...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1214465,301038,SEECLICKFIX_451536,City of San Clamente,2015-09-08T13:22:51-04:00,NaN,street signs,governance,governance_signage,Street Signs,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1214477,301050,SEECLICKFIX_451555,Lower Merion Demo,2015-09-08T11:56:08-04:00,NaN,streets,street,street_general,Streets,Pothole! Close this issue Jim! Test.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1214758,301331,SEECLICKFIX_452005,Village of Allouez,2015-09-03T11:13:09-04:00,NaN,street signs,governance,governance_signage,Street Signs,Jkggf

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1216252,302825,SEECLICKFIX_454302,West Malaysia (Peninsular Malaysia),2015-08-14T01:19:50-04:00,NaN,other,governance,governance_general,Other,Mohon menaiktaraf sepanjang Jalan Kg. Majid 9 ...
1216326,302899,SEECLICKFIX_454413,West Malaysia (Peninsular Malaysia),2015-08-12T23:50:21-04:00,NaN,potholes/road damage,street,street_repair,Potholes/road damage,Mohon membaiki jalan yang rosak di hadapan rum...
1221068,307641,SEECLICKFIX_461447,West Malaysia (Peninsular Malaysia),2015-06-10T23:28:59-04:00,NaN,potholes/road damage,street,street_repair,Potholes/road damage,luba\ gbbbb

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1218550,305123,SEECLICKFIX_457684,Coon Rapids,2015-07-15T23:52:10-04:00,NaN,street - miscellaneous street maintenance issues,street,street_general,Street - Miscellaneous street maintenance issues,Cross walk markings need to be repainted. Curr...
1223918,310491,SEECLICKFIX_466001,Coon Rapids,2015-04-29T11:05:52-04:00,NaN,street - potholes in the street pavement,street,street_repair,Street - Potholes in the street pavement,Many many holes. Hate to drive my brand new ca...
1225105,311678,SEECLICKFIX_467923,Coon Rapids,2015-04-13T11:21:08-04:00,NaN,street- street not draining,street,street_drainage,Street- Street not draining,The outlet for this catch basin is plugged wit...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1219062,305635,SEECLICKFIX_458476,Casino Reinvestment Dev. Authority,2015-07-09T07:58:41-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Billboard needs to be fixed
1220803,307376,SEECLICKFIX_461047,Casino Reinvestment Dev. Authority,2015-06-15T11:39:59-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Broken glass on liberty gifts ocean ave and Bo...
1220822,307395,SEECLICKFIX_461074,Casino Reinvestment Dev. Authority,2015-06-15T09:14:51-04:00,NaN,code enforcement issue,planning,planning_general,Code Enforcement Issue,Vacant lot overgrown

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1219584,306157,SEECLICKFIX_459227,Times of India,2015-07-02T00:26:45-04:00,NaN,fire and safety,fire,fire_general,Cleanliness - कचरा,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1219794,306367,SEECLICKFIX_459515,Town of Fort Kent,2015-06-29T17:06:42-04:00,NaN,pothole,street,street_repair,Pothole,Testing...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1221235,307808,SEECLICKFIX_461696,East Malaysia (Sabah Sarawak and Labuan),2015-06-09T03:32:56-04:00,NaN,natural disaster (flood fallen trees etc),environment,environment_overgrowth,Earthquake,Pray for Sabahan may God help them and stop th...
1229134,315707,SEECLICKFIX_476215,East Malaysia (Sabah Sarawak and Labuan),2015-01-25T09:58:33-05:00,NaN,broken/faulty streetlights,street,street_lighting,Broken/faulty streetlights,For one year already
1231827,318400,SEECLICKFIX_480387,East Malaysia (Sabah Sarawak and Labuan),2014-11-21T03:24:30-05:00,NaN,potholes/road damage,street,street_repair,Walkway Damage,The house owner ( House number H 1 Taman Rai...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1221455,308028,SEECLICKFIX_462043,MAHARASHTRA POLICE,2015-06-05T07:58:23-04:00,NaN,other,governance,governance_general,Post to neighbors,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1222811,309384,SEECLICKFIX_464207,City of Yacaipa,2015-05-15T01:34:13-04:00,NaN,pothole/street maintenance,street,street_repair,street light is not working,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1224924,311497,SEECLICKFIX_467625,Tes,2015-04-15T12:17:28-04:00,NaN,pothole,street,street_repair,Pothole,East bound side of Boylston St. (Rt 9) directl...
1226928,313501,SEECLICKFIX_471227,Tes,2015-03-13T15:05:18-04:00,NaN,pothole,street,street_repair,Potholes,There are several deep potholes on lower Walnu...
1227760,314333,SEECLICKFIX_473908,Tes,2015-02-26T09:19:19-05:00,NaN,pothole,street,street_repair,Pothole,The street is one sheet of ice and difficult f...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1225889,312462,SEECLICKFIX_469156,Town and Country,2015-04-01T17:03:44-04:00,NaN,other,governance,governance_general,Rotten Window Sills,Rotton window sill and frame no flashing aroun...
1226432,313005,SEECLICKFIX_470168,Town and Country,2015-03-23T11:43:36-04:00,NaN,other,governance,governance_general,Other,Leak coming from unit above Leaking into the c...
1226832,313405,SEECLICKFIX_470982,Town and Country,2015-03-15T22:40:40-04:00,NaN,outdoor light,environment,environment_general,Outdoor Light,Hello again Leo! This is my second test just ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1226823,313396,SEECLICKFIX_470961,Nagpur Municipal Corporation,2015-03-16T08:21:03-04:00,NaN,water supply,infrastructure,infrastructure_water,Water Supply,hamare complex me water supply nahi ho rha h.
1226825,313398,SEECLICKFIX_470963,Nagpur Municipal Corporation,2015-03-16T08:13:23-04:00,NaN,pothole/street maintenance,street,street_repair,Pothole/Street Maintenance,please fulfil the pothole .

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1228669,315242,SEECLICKFIX_475457,City of Dinuba,2015-02-03T16:12:34-05:00,NaN,street light,street,street_lighting,Street Light,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1231007,317580,SEECLICKFIX_479131,Toronto Star,2014-12-11T15:37:03-05:00,NaN,housing issue -beta test,housing,housing_general,Housing Issue -beta test,No heat. #more balcony has been under construc...
1231008,317581,SEECLICKFIX_479132,Toronto Star,2014-12-11T15:35:26-05:00,NaN,housing issue -beta test,housing,housing_general,Housing Issue -beta test,Unpainted hallways. #more all maintenance work...
1231009,317582,SEECLICKFIX_479133,Toronto Star,2014-12-11T15:34:21-05:00,NaN,housing issue -beta test,housing,housing_general,Housing Issue -beta test,Peeling paint on walls. #more cracks in walls.

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1231901,318474,SEECLICKFIX_480527,Mesa,2014-11-18T15:58:24-05:00,NaN,street light issue,street,street_lighting,Street Light Out - and Pigeon Issue,Hi There this street light only works intermit...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1231999,318572,SEECLICKFIX_480671,SF311 (inactive),2014-11-16T17:57:03-05:00,NaN,graffiti abatement - existing sr,vandalism,vandalism_graffiti,Graffiti Abatement - Existing SR,Feathered grey needs to be painted
1232345,318918,SEECLICKFIX_481163,SF311 (inactive),2014-11-09T14:46:52-05:00,NaN,graffiti abatement - existing sr,vandalism,vandalism_graffiti,Graffiti Abatement - Existing SR,White graffiti remove

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1235046,321619,SEECLICKFIX_485227,Bainbridge,2014-09-21T19:09:31-04:00,NaN,other,governance,governance_general,Other,Illegal burning. Burning yard trash every Week...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1261440,348013,SEECLICKFIX_516708,Brooklyn Community Board 14 (DOT),2014-05-10T02:00:11-04:00,NaN,other,governance,governance_general,extremely loud music coming from church,Extremely loud music constantly being play at ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1269091,355664,SEECLICKFIX_526478,Winter Storm Leon Neighbor to Neighbor Assistance,2014-03-24T17:48:51-04:00,NaN,other,governance,governance_general,Basketball Goal Facing The Street,My neighbor continues to keep their basketball...
1269108,355681,SEECLICKFIX_526499,Winter Storm Leon Neighbor to Neighbor Assistance,2014-03-24T16:53:59-04:00,NaN,other,governance,governance_general,Several Huge Potholes on Elizabeth Street near...,There are several huge potholes right in a row...
1269122,355695,SEECLICKFIX_526523,Winter Storm Leon Neighbor to Neighbor Assistance,2014-03-24T13:26:00-04:00,NaN,other,governance,governance_general,POTHOLES,CUSTOMER STATES THERE ARE POTHOLES THAT NEED T...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1271004,357577,SEECLICKFIX_529189,Hydrant Volunteer Program,2014-03-10T20:13:22-04:00,NaN,fire hydrant needs clearing,fire,fire_equipment_broken,Fire Hydrant Needs Clearing,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1271808,358381,SEECLICKFIX_530180,Elkton MD,2014-03-06T10:54:01-05:00,NaN,street improvement,street,street_general,Pothole at intersection of Main and Bow,NaN

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1272291,358864,SEECLICKFIX_530776,Loudoun County,2014-03-04T04:25:46-05:00,NaN,other,governance,governance_general,driveway,driveway needs to be shoveled #snowcrew
1272302,358875,SEECLICKFIX_530789,Loudoun County,2014-03-03T23:34:46-05:00,NaN,other,governance,governance_general,Need disabled parking space cleared,Snow plowed in parking space #snowcrew
1272306,358879,SEECLICKFIX_530794,Loudoun County,2014-03-03T23:17:46-05:00,NaN,other,governance,governance_general,Clearing parking space,I'm disabled and my car is plowed in my parkin...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2
1273212,359785,SEECLICKFIX_532102,Westport CT,2014-02-25T15:01:46-05:00,NaN,other,governance,governance_general,Multiple Potholes,Multiple potholes spanning entire width of roa...
1276333,362906,SEECLICKFIX_536779,Westport CT,2014-01-28T13:25:51-05:00,NaN,other,governance,governance_general,Panhandling,Panhandling bottom of Exit 17 I95 ramps

- NOTES:
    - US_CHICAGO: COMPLAINT_1
    - US_BATON_ROUGE: COMPLAINT_1
    - IRELAND: COMLAINT_2
    - US_CINCINNATI: Not sure, 1 but autofilled, 2 is all NaN
    - US_BLOOMINGTON: 1, bc 2 is all NaN
    - SEECLICKFIX: COMPLAINT_2

In [17]:
df[df['CITY']=='US_CINCINNATI'].groupby(['COMPLAINT_1']).count().sort_values('COMPLAINT_ID', ascending=False)

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_2
COMPLAINT_1,,,,,,,,,
"""Request entered through the Web. Refer to Intake Questions for further description.""",141283,141283,141283,141283,141283,141283,141283,141283,0
""" """,100387,100387,100387,100387,100387,100387,100387,100387,0
"""batch created""",5369,5369,5369,5369,5369,5369,5369,5369,0
"""RTC""",2234,2234,2234,2234,2234,2234,2234,2234,0
"""tall grass""",1890,1890,1890,1890,1890,1890,1890,1890,0
"""Mt Airy NEP 2013""",1485,1485,1485,1485,1485,1485,1485,1485,0
"""reissue to new owner""",1421,1421,1421,1421,1421,1421,1421,1421,0
"""couch""",1117,1117,1117,1117,1117,1117,1117,1117,0
"""Roselawn 2015 NEP""",1057,1057,1057,1057,1057,1057,1057,1057,0
"""POTHOLES""",1039,1039,1039,1039,1039,1039,1039,1039,0
"""Kennedy Heights 2012 NEP""",973,973,973,973,973,973,973,973,0
"""EPH NEP 2014""",915,915,915,915,915,915,915,915,0
"""COUCH""",888,888,888,888,888,888,888,888,0
"""4 tires""",864,864,864,864,864,864,864,864,0
"""TALL GRASS""",826,826,826,826,826,826,826,826,0
"""Carthage 2013 NEP""",768,768,768,768,768,768,768,768,0
"""POTHOLE""",743,743,743,743,743,743,743,743,0
"""2018 Flood FEMA Inspections""",654,654,654,654,654,654,654,654,0
"""PE SURVEY FOR CIVIL LITIGATION PER THE LAW DEPT""",650,650,650,650,650,650,650,650,0
"""ON FLASH""",649,649,649,649,649,649,649,649,0
"""FTC""",645,645,645,645,645,645,645,645,0
"""ftc yard waste """,619,619,619,619,619,619,619,619,0
"""mattress""",589,589,589,589,589,589,589,589,0
"""ROACHES""",583,583,583,583,583,583,583,583,0
"""TIRES""",551,551,551,551,551,551,551,551,0
"""REQUEST FOR SALT TREATMENT""",551,551,551,551,551,551,551,551,0
"""rtc yardwaste""",492,492,492,492,492,492,492,492,0
"""TALL GRASS/WEEDS""",466,466,466,466,466,466,466,466,0
"""RTC- CANS""",465,465,465,465,465,465,465,465,0
"""rtc trash""",447,447,447,447,447,447,447,447,0
...,...,...,...,...,...,...,...,...,...
"""Mayor Cranley,I want you to know that my yard waste has not been picked up since I contacted you last fall. I called the number you provided below. That office noted my complaint but said that nothing could be done till next Tuesday. I have multiple cans of yard waste since it cannot be picked up. Why can't this property (1429 Dana) have the normal yard waste service of other citizens of the city? It seems the only way the waste is ever collected if I contact you and every member of council. It is to the point where I am consider hiring a truck to drive the waste to another neighborhood where waste is collected.Tim White1429 Dana Ave.""",1,1,1,1,1,1,1,1,0
"""May be due to gas line replacement, lack of proper fill.""",1,1,1,1,1,1,1,1,0
"""McAuley HS """,1,1,1,1,1,1,1,1,0
"""McAuley High School is located at 6000 Oakwood Ave and I have noticed over the years that this road is never cleared when we have icy or snowy roads. Oakwood is very narrow with parking on both sides and can be very hazardous for experienced drivers much less new teen age drivers.""",1,1,1,1,1,1,1,1,0
"""McCORMICK & SCHMICK'S """,1,1,1,1,1,1,1,1,0
"""McCall Furneral Home""",1,1,1,1,1,1,1,1,0
"""McDonald Library""",1,1,1,1,1,1,1,1,0
"""McDonald's has no outside lighting at all at night time. Dirty inside and outside. not wearing gloves when preparing food. employees being very unprofessional wearing pants low underwear showing""",1,1,1,1,1,1,1,1,0
"""McDonald's on Reading is under construction. Water is dripping in on an area where employees work onto electrical equipment. """,1,1,1,1,1,1,1,1,0
"""May ceiling is about to cave in because of water damage""",1,1,1,1,1,1,1,1,0
"""May be a few more misc. small items that will not fit in trash can.""",1,1,1,1,1,1,1,1,0
"""Mattresses, box springs, furniture in rear of apt. bldg. for three months.""",1,1,1,1,1,1,1,1,0
"""Mattresses, tire, car grill, boxes ect. in Doerr Alley by the parking lot.""",1,1,1,1,1,1,1,1,0
"""Mattresses, couches""",1,1,1,1,1,1,1,1,0
"""Mattresses, couches, etc. at apt. bldg on corner of Hilton & Burnet.""",1,1,1,1,1,1,1,1,0
"""Mattresses, crib, and potentially several other items from cleaning out house.""",1,1,1,1,1,1,1,1,0
"""Mattresses, door, 2bikes, wheelchair grill, file cabinet""",1,1,1,1,1,1,1,1,0
"""Mattresses, furniture and other debris on vacant lot. Caller said you cannot see by driving by. You have to walk up the hill to see the debris.""",1,1,1,1,1,1,1,1,0
"""Mattresses, junk, litter in back of property where garage used to be before torn down. Will be able to see from driveway.""",1,1,1,1,1,1,1,1,0
"""Mattresses, large pile of brush, street litter in rear side of property. Can see from the alley.""",1,1,1,1,1,1,1,1,0
"""Mattresses/ furniture items out front been there for weeks""",1,1,1,1,1,1,1,1,0
"""May also be trash in the back & side""",1,1,1,1,1,1,1,1,0
"""Mattresses/dressers/clothes/applainces on front lawn thinks they moved out""",1,1,1,1,1,1,1,1,0
"""Mattresses/dressers/clothes/applainces on front lawn""",1,1,1,1,1,1,1,1,0
"""Mattresseswheelchairbikesdoorfile cabinetwood pieces""",1,1,1,1,1,1,1,1,0
"""Maufacturer""",1,1,1,1,1,1,1,1,0
"""Maui Wowi Hawaiian - Unit 3""",1,1,1,1,1,1,1,1,0
"""May I have 4 carts to share with the neighbors?""",1,1,1,1,1,1,1,1,0
"""May also be at 1180 Overlook Please remove ONE cart- RH5/15/2018 4:05 PM/RHENDERSON - also any older bins can be removed as well.""",1,1,1,1,1,1,1,1,0
"""â¢ Erection of Commercial Fence without a permit - cite building code section 1101-17 (e)â¢ Investigate proposed uses. The Auto Sales and the Commercial Vehicle Storage are PROHIBITED USES in the CC-P district. Granted we canât prohibit it if itâs not occurring, but we can inform the owner prior. """,1,1,1,1,1,1,1,1,0

In [18]:
df[df['CITY']=='US_BLOOMINGTON'].groupby(['COMPLAINT_1']).count().sort_values('COMPLAINT_ID', ascending=False)

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_2
COMPLAINT_1,,,,,,,,,
Recyclable items not properly sorted. Must be sorted for pick-up 945 las,2938,2938,2938,2938,2938,2938,2938,2938,0
no sticker,2098,2098,2098,2098,2098,2098,2098,2098,0
no stickers,1867,1867,1867,1867,1867,1867,1867,1867,0
S,1645,1645,1645,1645,1645,1645,1645,1645,0
Bags must have sticker attached.,1453,1453,1453,1453,1453,1453,1453,1453,0
can exceeds size limit,1260,1260,1260,1260,1260,1260,1260,1260,0
no tags,923,923,923,923,923,923,923,923,0
exceeds 35 gal,547,547,547,547,547,547,547,547,0
Recycable items not properly sorted.,508,508,508,508,508,508,508,508,0
S-no sticker,466,466,466,466,466,466,466,466,0
NO STICKER,453,453,453,453,453,453,453,453,0
Bags/cans must have sticker attached.,438,438,438,438,438,438,438,438,0
must be sorted,430,430,430,430,430,430,430,430,0
s,404,404,404,404,404,404,404,404,0
can exceeds 35 gal,393,393,393,393,393,393,393,393,0
not sorted,317,317,317,317,317,317,317,317,0
Bags must have sticker attached. 955,306,306,306,306,306,306,306,306,0
s-no sticker,305,305,305,305,305,305,305,305,0
Bags must have sticker attached. 944,290,290,290,290,290,290,290,290,0
###S#####,287,287,287,287,287,287,287,287,0
#S,275,275,275,275,275,275,275,275,0
please sort,263,263,263,263,263,263,263,263,0
exceeds 40 lbs,212,212,212,212,212,212,212,212,0
Exceeds can limit of 35 gallons.,199,199,199,199,199,199,199,199,0
too heavy,195,195,195,195,195,195,195,195,0
Missed pick-up/trash,188,188,188,188,188,188,188,188,0
B,179,179,179,179,179,179,179,179,0
Please sort,177,177,177,177,177,177,177,177,0
Recyclable items not properly sorted.,174,174,174,174,174,174,174,174,0
SEWER BACKUP,167,167,167,167,167,167,167,167,0
...,...,...,...,...,...,...,...,...,...
Missed pick-up/recycling: Please pick up boxes,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Please pick up his recycling - no notice left. Thanks CB,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Please pick up on Wednesday.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Please pick up recycling; CF,1,1,1,1,1,1,1,1,0
"Missed pick-up/recycling: Put them out last Friday, failed to pick them up. Put them othe this Friday, also failed to pick them up. Was no tag on them.",1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: R.C. not picked up,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Rec'd notice recycle not sorted correctly - will resort,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Recycle Bin - covered w/vinyl tablecloth to keep it dry,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed recycling bin.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed pick-up,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Did recyc. as always do. Put a clear plastic piece over the recycling - seperated into bags as they always do - covered due to the rain & steet. Lady was sick in bed so she did not know if a notice was left.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed paper products only - picked up everything else.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Failed to put trash outand wondered if could swing by and pick it up?,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Flag Stop --on porch,1,1,1,1,1,1,1,1,0
"Missed pick-up/recycling: Garbage can marked ""paper"" not picked up.",1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Gave to Martin over the phone.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Glass in trash can not picked up. All other recycling was taken.,1,1,1,1,1,1,1,1,0
"Missed pick-up/recycling: He has 2 trash cans marked ""recyclables"" that were not emptied. The red bins were but the the cans.",1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: He is upset b/c he says his recycleables have not been picked up from Friday. He was also concerned b/c it has happened twice in 2 months.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Her newspapers were not picked up.,1,1,1,1,1,1,1,1,0
"Missed pick-up/recycling: Her pizza boxes were not picked up w/recyling, they had some sauce on them - but they have been picked up before.",1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: His newspaper & boxes were not picked up.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: If something is wrong leave a note next to cardboard box.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: In Winslow Farm Dev. (over by the Y) The entire Street's recycling was missed.! Might also check Moss Creek Dr.,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: MIssed a trash can filled with paper,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed 2 weeks. Still sitting outside,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed his blue can of paper. faxed ddh,1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed it - no notice (Prow only goes b/w 10th & 9th st.),1,1,1,1,1,1,1,1,0
Missed pick-up/recycling: Missed last recycle day also ( duly noted),1,1,1,1,1,1,1,1,0
Â© 2023 by Name of Site. Proudly created with Wix.com\r\r\n\r\r\n\r\r\nDolores A McClure\r\r\n\r\r\ndmcclure31@yahoo.com\r\r\n\r\r\n8123608829\r\r\n\r\r\nThere are dead and dying trees behind 2111 S. Summerwood Ct. which is very close to me at 2115 S. Summerwood Ct. The owner is Leonard Sjogren. This is a danger to life and property. Can you help?,1,1,1,1,1,1,1,1,0

### Data cleaning - Comment cleanup

- Note: we will have to remove thousands of comments that are autogenerated
- Can try dict of lists for each city, or just make it universal

In [20]:
# Bloomington:
# S, B, #S #s###
    # strip specials like #, lowercase everything

droplist=['b','s','b/u','b/u-','hi','hello',\
          'Request entered through the Web. Refer to Intake Questions for further description.'.lower(),\
         " "]

In [21]:
df['model_x']=df['COMPLAINT_2']

In [26]:
df['model_x'][df['CITY'] =='US_CHICAGO']=df['COMPLAINT_1'][df['CITY'] =='US_CHICAGO']
df['model_x'][df['CITY'] =='US_BATON_ROUGE']=df['COMPLAINT_1'][df['CITY'] =='US_BATON_ROUGE']

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [27]:
display(df.head(2),df.tail(2))

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2,model_x
0,0,US_CHICAGO_1725,US_CHICAGO,10/03/2011,health_environment,permits issued by doe work order,environment,environment_general,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...,[INSPECTION LOG #: 1723 03-OCT-11 18:55:00] TH...,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...
1,1,US_CHICAGO_600301602,US_CHICAGO,07/14/2017,health_environment,illegal dumping work order,environment,environment_dumping,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...,[INSPECTION LOG #: 3439804 14-JUL-17 09:45:00]...,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,COMPLAINT_1,COMPLAINT_2,model_x
1278127,364700,SEECLICKFIX_539339,City of Chicago,2016-09-20T15:27:06-04:00,NaN,graffiti removal,vandalism,vandalism_graffiti,Graffiti Removal,NaN,NaN
1278128,364701,SEECLICKFIX_539340,OLD City of Richmond,2015-06-25T23:54:50-04:00,NaN,other,governance,governance_general,Missing sidewalk,Entire sidewalk on North side of street betwee...,Entire sidewalk on North side of street betwee...

In [28]:
df.drop(labels=['COMPLAINT_1','COMPLAINT_2'],axis=1,inplace=True)

In [29]:
df.head()

,index,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,model_x
0,0,US_CHICAGO_1725,US_CHICAGO,10/03/2011,health_environment,permits issued by doe work order,environment,environment_general,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...
1,1,US_CHICAGO_600301602,US_CHICAGO,07/14/2017,health_environment,illegal dumping work order,environment,environment_dumping,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...
2,2,US_CHICAGO_1106,US_CHICAGO,08/19/2011,health_environment,air pollution work order,environment,environment_air_pollution,REPLACING WINDOWS AND SANDBLASTING CAUSING DUS...
3,3,US_CHICAGO_2063,US_CHICAGO,10/26/2011,health_environment,air pollution work order,environment,environment_air_pollution,NaN
4,4,US_CHICAGO_2503,US_CHICAGO,12/14/2011,health_environment,abandoned site,environment,environment_abandoned_site,PROPERTY CAUSING HAZARDOUS CONDITIONS ON PUBLI...

In [33]:
df.dropna(axis=0,subset=['model_x'],inplace=True)

In [34]:
df.shape

(540532, 9)

In [35]:
df.to_csv(PATH+'/danicic_modeldata.tsv',sep='\t')

In [36]:
del df

In [37]:
df=pd.read_csv(PATH+'/danicic_modeldata.tsv',sep='\t')

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [40]:
df.drop(axis=1,labels=['Unnamed: 0','index'],inplace=True)

In [41]:
df.head()

,COMPLAINT_ID,CITY,COMPLAINT DATE,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,model_x
0,US_CHICAGO_1725,US_CHICAGO,10/03/2011,health_environment,permits issued by doe work order,environment,environment_general,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...
1,US_CHICAGO_600301602,US_CHICAGO,07/14/2017,health_environment,illegal dumping work order,environment,environment_dumping,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...
2,US_CHICAGO_1106,US_CHICAGO,08/19/2011,health_environment,air pollution work order,environment,environment_air_pollution,REPLACING WINDOWS AND SANDBLASTING CAUSING DUS...
3,US_CHICAGO_2503,US_CHICAGO,12/14/2011,health_environment,abandoned site,environment,environment_abandoned_site,PROPERTY CAUSING HAZARDOUS CONDITIONS ON PUBLI...
4,US_CHICAGO_2120,US_CHICAGO,10/27/2011,health_environment,air pollution work order,environment,environment_air_pollution,CONSTRUCTION WORK IS CAUSING DUST

In [43]:
df.drop(axis=1,labels=['COMPLAINT DATE'],inplace=True)

## MODEL BASICS

In [105]:
# Load packages
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

import seaborn as sns

from sklearn.metrics import confusion_matrix

In [91]:
df=pd.read_csv(PATH+'/danicic_modeldata.tsv',sep='\t')
df.drop(axis=1,labels=['Unnamed: 0','index','COMPLAINT DATE'],inplace=True)

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [92]:
groupclass_dict=dict()
count=1
for main in df['CATEGORY_MAIN'].unique():
    groupclass_dict[main]=count
    groupclass_dict[str(count)]=main
    count+=1
display(groupclass_dict)

df['model_y']=df['CATEGORY_MAIN'].map(lambda x: groupclass_dict[x])

{'1': 'environment',
 '10': 'fire',
 '2': 'public_order',
 '3': 'planning',
 '4': 'infrastructure',
 '5': 'street',
 '6': 'housing',
 '7': 'governance',
 '8': 'vandalism',
 '9': 'public_health',
 'environment': 1,
 'fire': 10,
 'governance': 7,
 'housing': 6,
 'infrastructure': 4,
 'planning': 3,
 'public_health': 9,
 'public_order': 2,
 'street': 5,
 'vandalism': 8}

In [93]:
df.head(2)

,COMPLAINT_ID,CITY,DEPT_311,CODE_311,CATEGORY_MAIN,CATEGORY_SUB,model_x,model_y
0,US_CHICAGO_1725,US_CHICAGO,health_environment,permits issued by doe work order,environment,environment_general,QUESTIONABLE BUSINESS PRACTICES REGARDING OILS...,1
1,US_CHICAGO_600301602,US_CHICAGO,health_environment,illegal dumping work order,environment,environment_dumping,CONSTRUCTION/DEMOLITION DEBRIS DUMPED IN BACK ...,1

In [94]:
df.groupby('CATEGORY_MAIN').count()

,COMPLAINT_ID,CITY,DEPT_311,CODE_311,CATEGORY_SUB,model_x,model_y
CATEGORY_MAIN,,,,,,,
environment,278133,278133,214901,278133,278133,278133,278133
fire,237,237,0,237,237,237,237
governance,44957,44957,2466,44957,44957,44957,44957
housing,10875,10875,5279,10875,10875,10875,10875
infrastructure,29999,29999,26793,29999,29999,29999,29999
planning,16446,16446,1365,16446,16446,16446,16446
public_health,2907,2907,0,2907,2907,2907,2907
public_order,16631,16631,8644,16631,16631,16631,16631
street,123516,123516,37770,123516,123516,123516,123516
vandalism,16831,16831,1144,16831,16831,16831,16831

- Split data stratified

In [95]:
y = df.pop('model_y')
x= df.pop('model_x')

count_vect = CountVectorizer()
x_counts = count_vect.fit_transform(x)
tfidf_transformer = TfidfTransformer()
x_tfidf = tfidf_transformer.fit_transform(x_counts)

In [96]:
x_train, x_test, y_train, y_test = train_test_split( x_tfidf, y, test_size=0.2, random_state=412, stratify=y)

In [97]:
#NB
clf = MultinomialNB().fit(x_train, y_train)

In [98]:
groupclass_dict[str(clf.predict(count_vect.transform(["fire escape"]))[0])]

'environment'

In [99]:
y_predict=clf.predict(x_test)

In [100]:
# creating a confusion matrix 
cm = confusion_matrix(y_test, y_predict)
cm

array([[52196,    16,     0,     6,  3088,     0,   314,     7,     0,
            0],
       [ 1637,  1140,     0,     0,   321,     0,   228,     0,     0,
            0],
       [ 1542,     7,   956,     1,   624,     0,   159,     0,     0,
            0],
       [ 2893,     2,     0,  1292,  1783,     0,    20,    10,     0,
            0],
       [ 2176,     0,     1,    75, 22268,     0,   177,     6,     0,
            0],
       [ 1849,     3,     0,     6,    97,   181,    33,     6,     0,
            0],
       [ 3526,    23,     0,    11,  3850,     1,  1550,    31,     0,
            0],
       [ 1169,     0,     3,     3,  1354,     0,   213,   624,     0,
            0],
       [  366,     1,     0,     0,   146,     0,    69,     0,     0,
            0],
       [   26,     0,     0,     0,    17,     0,     4,     0,     0,
            0]])

In [103]:


modelsvc = LinearSVC()
modelsvc.fit(x_train, y_train)
y_predict_svc = modelsvc.predict(x_test)

NameError: name 'y_predict_svm' is not defined

In [ ]:
cm_svc = confusion_matrix(y_test, y_predict_svc)
fig, ax = plt.subplots(figsize=(10,10))
sns.heatmap(cm_svc, annot=True, fmt='d')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()